%% T03_P1_multitaper_terreno.m
% Analisis Multitaper - P1 / LED terreno 1
%
% Antes de ejecutar este script, modificar las variables carpeta_ON
% y carpeta_OFF con las rutas locales donde se encuentran los archivos .csv
% de la medicion correspondiente.
%
% La carpeta_ON debe contener los archivos ON_P1_REP*.csv indicados
% en la lista archivos_ON.
% La carpeta_OFF debe contener los archivos OFF comunes indicados
% en la lista archivos_OFF.
%
% Ejemplo:
% carpeta_ON  = 'C:\Users\NombreUsuario\Desktop\Terreno_ON_M1';
% carpeta_OFF = 'C:\Users\NombreUsuario\Desktop\Terreno_OFF';

clear;
clc;
close all;

%% 1. Configuracion

carpeta_base = 'C:\Users\mudrood\Desktop\Modulo Prof\Archivos Tesis\Toma de Datos\Pruebas en terreno';

carpeta_ON = fullfile(carpeta_base, 'Terreno_ON_M1');
carpeta_OFF = fullfile(carpeta_base, 'Terreno_OFF');

carpeta_salida = fullfile( ...
    carpeta_base, ...
    'Resultados_Terreno', ...
    'P1_LED1', ...
    '03_Multitaper');

if ~exist(carpeta_salida, 'dir')
    mkdir(carpeta_salida);
end

% Eliminar archivos FIG heredados de versiones anteriores.
archivos_fig_anteriores = dir( ...
    fullfile(carpeta_salida, '*P1_multitaper*.fig'));

for k = 1:numel(archivos_fig_anteriores)

    delete(fullfile( ...
        archivos_fig_anteriores(k).folder, ...
        archivos_fig_anteriores(k).name));
end

nombre_punto = "P1";
nombre_led = "LED terreno 1";
nombre_metodo = "Multitaper";

nRep = 3;

archivos_ON = cell(nRep, 1);
archivos_OFF = cell(nRep, 1);

for r = 1:nRep

    archivos_ON{r} = fullfile( ...
        carpeta_ON, ...
        sprintf('ON_P1_REP%d.csv', r));

    archivos_OFF{r} = fullfile( ...
        carpeta_OFF, ...
        sprintf('OFF_REP%d.csv', r));
end

% Banda completa calculada y mostrada
fmin_Hz = 30e3;
fmax_Hz = 90e3;

% Referencia obtenida mediante Periodograma
f_ref_periodograma_Hz = 45.642e3;

% Ventana local usada para confirmar la frecuencia
semiancho_busqueda_local_Hz = 1e3;

% Criterio operativo
criterio_dB = 3;

% Candidatos locales
num_candidatos = 7;
distancia_minima_Hz = 150;
ventana_refinamiento_Hz = 100;
ventana_repetibilidad_Hz = 200;

% Adquisicion
Fs_configurada_Hz = 50e6;

% Multitaper
NW = 2.5;
NFFT = 2^20;

% Figura de rango amplio
fmax_amplio_Hz = 5e6;

limite_local_inferior_Hz = max( ...
    fmin_Hz, ...
    f_ref_periodograma_Hz - semiancho_busqueda_local_Hz);

limite_local_superior_Hz = min( ...
    fmax_Hz, ...
    f_ref_periodograma_Hz + semiancho_busqueda_local_Hz);

fprintf('\n============================================================\n');
fprintf('PUNTO 1 / LED TERRENO 1 - MULTITAPER\n');
fprintf('============================================================\n');
fprintf('Carpeta base:\n%s\n\n', carpeta_base);
fprintf('Carpeta salida:\n%s\n\n', carpeta_salida);
fprintf('Fs configurada: %.6f MSa/s\n', Fs_configurada_Hz/1e6);
fprintf('Banda completa: %.1f a %.1f kHz\n', ...
    fmin_Hz/1e3, fmax_Hz/1e3);
fprintf('Referencia Periodograma: %.4f kHz\n', ...
    f_ref_periodograma_Hz/1e3);
fprintf('Ventana local: %.4f a %.4f kHz\n', ...
    limite_local_inferior_Hz/1e3, ...
    limite_local_superior_Hz/1e3);
fprintf('NW: %.2f\n', NW);
fprintf('NFFT: %d\n', NFFT);
fprintf('Resolucion de grilla: %.6f Hz\n', ...
    Fs_configurada_Hz/NFFT);

%% 2. Verificacion de archivos

for r = 1:nRep

    if ~isfile(archivos_ON{r})

        error( ...
            'No existe el archivo ON de la repeticion %d:\n%s', ...
            r, archivos_ON{r});
    end

    if ~isfile(archivos_OFF{r})

        error( ...
            'No existe el archivo OFF de la repeticion %d:\n%s', ...
            r, archivos_OFF{r});
    end
end

fprintf('\nArchivos verificados correctamente.\n');

%% 3. Calculo Multitaper por repeticion

f_ref_Hz = [];
PSD_ON_mat_dB = [];
PSD_OFF_mat_dB = [];
info_repeticiones = table();

for r = 1:nRep

    fprintf('\n------------------------------------------------------------\n');
    fprintf('Repeticion %d/%d\n', r, nRep);
    fprintf('ON : %s\n', archivos_ON{r});
    fprintf('OFF: %s\n', archivos_OFF{r});

    [tON, xON] = leer_csv_rigol_terreno(archivos_ON{r});
    [tOFF, xOFF] = leer_csv_rigol_terreno(archivos_OFF{r});

    N_ON_original = numel(xON);
    N_OFF_original = numel(xOFF);
    N_usado = min(N_ON_original, N_OFF_original);

    if N_usado < 1000

        error( ...
            'La repeticion %d contiene muy pocas muestras validas.', ...
            r);
    end

    tON = tON(1:N_usado);
    xON = xON(1:N_usado);

    tOFF = tOFF(1:N_usado);
    xOFF = xOFF(1:N_usado);

    duracion_ON_s = tON(end) - tON(1);
    duracion_OFF_s = tOFF(end) - tOFF(1);

    if duracion_ON_s <= 0 || duracion_OFF_s <= 0

        error( ...
            'El vector de tiempo no posee una duracion valida.');
    end

    Fs_ON_duracion_Hz = ...
        (N_usado - 1)/duracion_ON_s;

    Fs_OFF_duracion_Hz = ...
        (N_usado - 1)/duracion_OFF_s;

    error_Fs_ON_pct = abs( ...
        Fs_ON_duracion_Hz - Fs_configurada_Hz) / ...
        Fs_configurada_Hz * 100;

    error_Fs_OFF_pct = abs( ...
        Fs_OFF_duracion_Hz - Fs_configurada_Hz) / ...
        Fs_configurada_Hz * 100;

    if error_Fs_ON_pct > 1

        warning( ...
            ['La Fs estimada para ON difiere mas de 1 %% ', ...
             'respecto de 50 MSa/s en la repeticion %d.'], ...
            r);
    end

    if error_Fs_OFF_pct > 1

        warning( ...
            ['La Fs estimada para OFF difiere mas de 1 %% ', ...
             'respecto de 50 MSa/s en la repeticion %d.'], ...
            r);
    end

    xON = xON - mean(xON, 'omitnan');
    xOFF = xOFF - mean(xOFF, 'omitnan');

    xON(~isfinite(xON)) = 0;
    xOFF(~isfinite(xOFF)) = 0;

    [Pxx_ON, fON_Hz] = pmtm( ...
        xON, ...
        NW, ...
        NFFT, ...
        Fs_configurada_Hz);

    [Pxx_OFF, fOFF_Hz] = pmtm( ...
        xOFF, ...
        NW, ...
        NFFT, ...
        Fs_configurada_Hz);

    fON_Hz = fON_Hz(:);
    fOFF_Hz = fOFF_Hz(:);

    PSD_ON_dB = 10*log10(Pxx_ON(:) + eps);
    PSD_OFF_dB = 10*log10(Pxx_OFF(:) + eps);

    if numel(fON_Hz) ~= numel(fOFF_Hz) || ...
            max(abs(fON_Hz - fOFF_Hz)) > 1e-9

        error( ...
            'Las grillas ON y OFF no coinciden en la repeticion %d.', ...
            r);
    end

    if max(fON_Hz) < fmax_Hz

        error( ...
            'La grilla Multitaper no cubre la banda de 30 a 90 kHz.');
    end

    if isempty(f_ref_Hz)

        f_ref_Hz = fON_Hz;

        PSD_ON_mat_dB = ...
            nan(numel(f_ref_Hz), nRep);

        PSD_OFF_mat_dB = ...
            nan(numel(f_ref_Hz), nRep);
    end

    PSD_ON_mat_dB(:, r) = interp1( ...
        fON_Hz, ...
        PSD_ON_dB, ...
        f_ref_Hz, ...
        'linear', ...
        NaN);

    PSD_OFF_mat_dB(:, r) = interp1( ...
        fOFF_Hz, ...
        PSD_OFF_dB, ...
        f_ref_Hz, ...
        'linear', ...
        NaN);

    info_repeticiones = [ ...
        info_repeticiones; ...
        crear_fila_info( ...
        string(archivos_ON{r}), ...
        "ON", ...
        r, ...
        N_ON_original, ...
        N_usado, ...
        duracion_ON_s, ...
        Fs_ON_duracion_Hz, ...
        Fs_configurada_Hz, ...
        error_Fs_ON_pct, ...
        NW, ...
        NFFT, ...
        Fs_configurada_Hz/NFFT)];

    info_repeticiones = [ ...
        info_repeticiones; ...
        crear_fila_info( ...
        string(archivos_OFF{r}), ...
        "OFF", ...
        r, ...
        N_OFF_original, ...
        N_usado, ...
        duracion_OFF_s, ...
        Fs_OFF_duracion_Hz, ...
        Fs_configurada_Hz, ...
        error_Fs_OFF_pct, ...
        NW, ...
        NFFT, ...
        Fs_configurada_Hz/NFFT)];

    fprintf('N usado             = %d muestras\n', N_usado);
    fprintf('Fs ON por duracion  = %.6f MSa/s\n', ...
        Fs_ON_duracion_Hz/1e6);
    fprintf('Fs OFF por duracion = %.6f MSa/s\n', ...
        Fs_OFF_duracion_Hz/1e6);

    clear tON tOFF xON xOFF
    clear Pxx_ON Pxx_OFF PSD_ON_dB PSD_OFF_dB
end

%% 4. Promedios y score ON-OFF

PSD_ON_prom_dB = mean( ...
    PSD_ON_mat_dB, ...
    2, ...
    'omitnan');

PSD_OFF_prom_dB = mean( ...
    PSD_OFF_mat_dB, ...
    2, ...
    'omitnan');

% Cada captura ON se compara con la referencia OFF promedio.
score_rep_dB = ...
    PSD_ON_mat_dB - PSD_OFF_prom_dB;

score_prom_dB = mean( ...
    score_rep_dB, ...
    2, ...
    'omitnan');

f_ref_Hz = f_ref_Hz(:);
PSD_ON_prom_dB = PSD_ON_prom_dB(:);
PSD_OFF_prom_dB = PSD_OFF_prom_dB(:);
score_prom_dB = score_prom_dB(:);

%% 5. Banda completa de analisis

idx_banda = ...
    f_ref_Hz >= fmin_Hz & ...
    f_ref_Hz <= fmax_Hz;

if ~any(idx_banda)

    error( ...
        'No existen puntos dentro de la banda de 30 a 90 kHz.');
end

f_banda_Hz = ...
    f_ref_Hz(idx_banda);

PSD_ON_banda_dB = ...
    PSD_ON_prom_dB(idx_banda);

PSD_OFF_banda_dB = ...
    PSD_OFF_prom_dB(idx_banda);

score_banda_dB = ...
    score_prom_dB(idx_banda);

PSD_ON_banda_reps_dB = ...
    PSD_ON_mat_dB(idx_banda, :);

PSD_OFF_banda_reps_dB = ...
    PSD_OFF_mat_dB(idx_banda, :);

score_banda_reps_dB = ...
    score_rep_dB(idx_banda, :);

idx_validos = ...
    isfinite(f_banda_Hz) & ...
    isfinite(PSD_ON_banda_dB) & ...
    isfinite(PSD_OFF_banda_dB) & ...
    isfinite(score_banda_dB);

f_banda_Hz = ...
    f_banda_Hz(idx_validos);

PSD_ON_banda_dB = ...
    PSD_ON_banda_dB(idx_validos);

PSD_OFF_banda_dB = ...
    PSD_OFF_banda_dB(idx_validos);

score_banda_dB = ...
    score_banda_dB(idx_validos);

PSD_ON_banda_reps_dB = ...
    PSD_ON_banda_reps_dB(idx_validos, :);

PSD_OFF_banda_reps_dB = ...
    PSD_OFF_banda_reps_dB(idx_validos, :);

score_banda_reps_dB = ...
    score_banda_reps_dB(idx_validos, :);

f_banda_kHz = f_banda_Hz/1e3;

%% 6. Maximo global solo como diagnostico

[score_max_global_dB, idx_max_global] = ...
    max(score_banda_dB);

f_max_global_Hz = ...
    f_banda_Hz(idx_max_global);

fprintf('\n============================================================\n');
fprintf('MAXIMO GLOBAL - SOLO DIAGNOSTICO\n');
fprintf('============================================================\n');
fprintf('Frecuencia global = %.4f kHz\n', ...
    f_max_global_Hz/1e3);
fprintf('Score global      = %.4f dB\n', ...
    score_max_global_dB);

%% 7. Ventana local de confirmacion

idx_busqueda_local = ...
    f_banda_Hz >= limite_local_inferior_Hz & ...
    f_banda_Hz <= limite_local_superior_Hz;

if ~any(idx_busqueda_local)

    error( ...
        'No existen puntos dentro de la ventana local Multitaper.');
end

f_busqueda_local_Hz = ...
    f_banda_Hz(idx_busqueda_local);

score_busqueda_local_dB = ...
    score_banda_dB(idx_busqueda_local);

[score_max_local_dB, idx_max_local] = ...
    max(score_busqueda_local_dB);

f_max_local_Hz = ...
    f_busqueda_local_Hz(idx_max_local);

fprintf('\n============================================================\n');
fprintf('MAXIMO LOCAL MULTITAPER\n');
fprintf('============================================================\n');
fprintf('Referencia Periodograma = %.4f kHz\n', ...
    f_ref_periodograma_Hz/1e3);
fprintf('Frecuencia local        = %.4f kHz\n', ...
    f_max_local_Hz/1e3);
fprintf('Score local             = %.4f dB\n', ...
    score_max_local_dB);

%% 8. Candidatos dentro de la ventana local

[picos_dB, frecuencias_picos_Hz] = findpeaks( ...
    score_busqueda_local_dB, ...
    f_busqueda_local_Hz, ...
    'MinPeakDistance', ...
    distancia_minima_Hz);

idx_picos_validos = ...
    isfinite(picos_dB) & ...
    isfinite(frecuencias_picos_Hz) & ...
    picos_dB > 0;

picos_dB = ...
    picos_dB(idx_picos_validos);

frecuencias_picos_Hz = ...
    frecuencias_picos_Hz(idx_picos_validos);

if isempty(picos_dB)

    picos_dB = ...
        score_max_local_dB;

    frecuencias_picos_Hz = ...
        f_max_local_Hz;
end

[picos_dB, idx_orden] = sort( ...
    picos_dB, ...
    'descend');

frecuencias_picos_Hz = ...
    frecuencias_picos_Hz(idx_orden);

num_candidatos_usados = min( ...
    num_candidatos, ...
    numel(picos_dB));

score_peak_dB = ...
    picos_dB(1:num_candidatos_usados);

fc_candidatas_Hz = ...
    frecuencias_picos_Hz(1:num_candidatos_usados);

nCandidatos = ...
    numel(fc_candidatas_Hz);

score_local_dB = ...
    nan(nCandidatos, 1);

f_local_Hz = ...
    nan(nCandidatos, 1);

ON_dB = ...
    nan(nCandidatos, 1);

OFF_dB = ...
    nan(nCandidatos, 1);

rep_positivas = ...
    zeros(nCandidatos, 1);

rep_3dB = ...
    zeros(nCandidatos, 1);

for i = 1:nCandidatos

    fc_Hz = ...
        fc_candidatas_Hz(i);

    idx_local = ...
        f_ref_Hz >= fc_Hz - ventana_refinamiento_Hz & ...
        f_ref_Hz <= fc_Hz + ventana_refinamiento_Hz & ...
        f_ref_Hz >= limite_local_inferior_Hz & ...
        f_ref_Hz <= limite_local_superior_Hz;

    f_local_temp_Hz = ...
        f_ref_Hz(idx_local);

    score_local_temp_dB = ...
        score_prom_dB(idx_local);

    if isempty(score_local_temp_dB)
        continue;
    end

    [score_local_dB(i), idx_max] = ...
        max(score_local_temp_dB);

    f_local_Hz(i) = ...
        f_local_temp_Hz(idx_max);

    ON_dB(i) = interp1( ...
        f_ref_Hz, ...
        PSD_ON_prom_dB, ...
        f_local_Hz(i), ...
        'linear', ...
        NaN);

    OFF_dB(i) = interp1( ...
        f_ref_Hz, ...
        PSD_OFF_prom_dB, ...
        f_local_Hz(i), ...
        'linear', ...
        NaN);

    idx_rep = ...
        f_ref_Hz >= ...
        f_local_Hz(i) - ventana_repetibilidad_Hz & ...
        f_ref_Hz <= ...
        f_local_Hz(i) + ventana_repetibilidad_Hz;

    for r = 1:nRep

        score_rep_local = ...
            score_rep_dB(idx_rep, r);

        score_rep_max_dB = ...
            max(score_rep_local, [], 'omitnan');

        if isfinite(score_rep_max_dB)

            rep_positivas(i) = ...
                rep_positivas(i) + ...
                double(score_rep_max_dB > 0);

            rep_3dB(i) = ...
                rep_3dB(i) + ...
                double(score_rep_max_dB >= criterio_dB);
        end
    end
end

idx_finitos = ...
    isfinite(f_local_Hz) & ...
    isfinite(score_local_dB) & ...
    isfinite(ON_dB) & ...
    isfinite(OFF_dB);

fc_candidatas_Hz = ...
    fc_candidatas_Hz(idx_finitos);

score_peak_dB = ...
    score_peak_dB(idx_finitos);

f_local_Hz = ...
    f_local_Hz(idx_finitos);

score_local_dB = ...
    score_local_dB(idx_finitos);

ON_dB = ...
    ON_dB(idx_finitos);

OFF_dB = ...
    OFF_dB(idx_finitos);

rep_positivas = ...
    rep_positivas(idx_finitos);

rep_3dB = ...
    rep_3dB(idx_finitos);

if isempty(f_local_Hz)

    error( ...
        'No fue posible obtener candidatos locales validos.');
end

% Evitar candidatos repetidos despues del refinamiento.
[f_local_unicos_Hz, idx_unicos] = unique( ...
    f_local_Hz, ...
    'stable');

f_local_Hz = ...
    f_local_unicos_Hz;

fc_candidatas_Hz = ...
    fc_candidatas_Hz(idx_unicos);

score_peak_dB = ...
    score_peak_dB(idx_unicos);

score_local_dB = ...
    score_local_dB(idx_unicos);

ON_dB = ...
    ON_dB(idx_unicos);

OFF_dB = ...
    OFF_dB(idx_unicos);

rep_positivas = ...
    rep_positivas(idx_unicos);

rep_3dB = ...
    rep_3dB(idx_unicos);

nCandidatos = ...
    numel(f_local_Hz);

supera_3dB = ...
    score_local_dB >= criterio_dB & ...
    rep_3dB == nRep;

tabla_candidatos = table( ...
    fc_candidatas_Hz, ...
    fc_candidatas_Hz/1e3, ...
    score_peak_dB, ...
    f_local_Hz, ...
    f_local_Hz/1e3, ...
    score_local_dB, ...
    ON_dB, ...
    OFF_dB, ...
    rep_positivas, ...
    rep_3dB, ...
    repmat(nRep, nCandidatos, 1), ...
    supera_3dB, ...
    'VariableNames', { ...
    'fc_Hz', ...
    'fc_kHz', ...
    'score_peak_dB', ...
    'f_local_Hz', ...
    'f_local_kHz', ...
    'score_local_dB', ...
    'ON_dB', ...
    'OFF_dB', ...
    'rep_positivas', ...
    'rep_3dB', ...
    'rep_totales', ...
    'supera_3dB'});

tabla_candidatos = sortrows( ...
    tabla_candidatos, ...
    'score_local_dB', ...
    'descend');

%% 9. Seleccion de frecuencia principal

idx_validos_3dB = ...
    tabla_candidatos.supera_3dB;

if any(idx_validos_3dB)

    tabla_validos = ...
        tabla_candidatos(idx_validos_3dB, :);

    [~, idx_mejor] = ...
        max(tabla_validos.score_local_dB);

    fila_principal = ...
        tabla_validos(idx_mejor, :);

else

    warning( ...
        ['Ningun candidato local supera 3 dB en las tres ', ...
         'repeticiones. Se utilizara el mayor candidato local ', ...
         'como resultado provisional.']);

    fila_principal = ...
        tabla_candidatos(1, :);
end

fc_principal_Hz = ...
    fila_principal.f_local_Hz;

fc_principal_kHz = ...
    fila_principal.f_local_kHz;

score_principal_dB = ...
    fila_principal.score_local_dB;

ON_principal_dB = ...
    fila_principal.ON_dB;

OFF_principal_dB = ...
    fila_principal.OFF_dB;

rep_positivas_principal = ...
    fila_principal.rep_positivas;

rep_3dB_principal = ...
    fila_principal.rep_3dB;

if score_principal_dB >= criterio_dB && ...
        rep_3dB_principal == nRep

    supera_criterio = "Si";

else

    supera_criterio = "No";
end

%% 10. Frecuencia y score por repeticion

idx_rep_principal = ...
    f_ref_Hz >= ...
    fc_principal_Hz - ventana_repetibilidad_Hz & ...
    f_ref_Hz <= ...
    fc_principal_Hz + ventana_repetibilidad_Hz;

f_rep_principal_Hz = ...
    f_ref_Hz(idx_rep_principal);

if isempty(f_rep_principal_Hz)

    error( ...
        'No existen puntos para evaluar la repetibilidad.');
end

fc_por_rep_Hz = ...
    nan(nRep, 1);

score_por_rep_dB = ...
    nan(nRep, 1);

score_positivo_0dB = ...
    false(nRep, 1);

score_positivo_3dB = ...
    false(nRep, 1);

for r = 1:nRep

    score_temp_dB = ...
        score_rep_dB(idx_rep_principal, r);

    [score_por_rep_dB(r), idx_rep_max] = ...
        max(score_temp_dB, [], 'omitnan');

    fc_por_rep_Hz(r) = ...
        f_rep_principal_Hz(idx_rep_max);

    score_positivo_0dB(r) = ...
        score_por_rep_dB(r) > 0;

    score_positivo_3dB(r) = ...
        score_por_rep_dB(r) >= criterio_dB;
end

%% 11. Tablas de resultados

tabla_resultado = table( ...
    nombre_punto, ...
    nombre_led, ...
    nombre_metodo, ...
    f_ref_periodograma_Hz/1e3, ...
    semiancho_busqueda_local_Hz/1e3, ...
    fc_principal_kHz, ...
    score_principal_dB, ...
    ON_principal_dB, ...
    OFF_principal_dB, ...
    rep_positivas_principal, ...
    rep_3dB_principal, ...
    nRep, ...
    criterio_dB, ...
    supera_criterio, ...
    NW, ...
    NFFT, ...
    Fs_configurada_Hz/NFFT, ...
    'VariableNames', { ...
    'punto', ...
    'led', ...
    'metodo', ...
    'f_ref_periodograma_kHz', ...
    'semiancho_local_kHz', ...
    'fc_detectada_kHz', ...
    'score_dB', ...
    'ON_prom_dB', ...
    'OFF_prom_dB', ...
    'rep_positivas', ...
    'rep_3dB', ...
    'rep_totales', ...
    'criterio_dB', ...
    'supera_3dB', ...
    'NW', ...
    'NFFT', ...
    'df_Hz'});

tabla_repeticiones = table( ...
    (1:nRep)', ...
    fc_por_rep_Hz, ...
    fc_por_rep_Hz/1e3, ...
    score_por_rep_dB, ...
    score_positivo_0dB, ...
    score_positivo_3dB, ...
    'VariableNames', { ...
    'repeticion', ...
    'fc_local_Hz', ...
    'fc_local_kHz', ...
    'score_local_dB', ...
    'score_positivo_0dB', ...
    'score_positivo_3dB'});

tabla_score = table( ...
    f_banda_kHz(:), ...
    PSD_ON_banda_dB(:), ...
    PSD_OFF_banda_dB(:), ...
    score_banda_dB(:), ...
    'VariableNames', { ...
    'f_kHz', ...
    'PSD_ON_prom_dB', ...
    'PSD_OFF_prom_dB', ...
    'score_prom_dB'});

fprintf('\n============================================================\n');
fprintf('RESULTADO MULTITAPER P1\n');
fprintf('============================================================\n');
fprintf('Referencia Periodograma = %.4f kHz\n', ...
    f_ref_periodograma_Hz/1e3);
fprintf('Frecuencia Multitaper   = %.4f kHz\n', ...
    fc_principal_kHz);
fprintf('Score principal         = %.4f dB\n', ...
    score_principal_dB);
fprintf('Repeticiones > 0 dB     = %d/%d\n', ...
    rep_positivas_principal, nRep);
fprintf('Repeticiones >= 3 dB    = %d/%d\n', ...
    rep_3dB_principal, nRep);
fprintf('Cumple criterio         = %s\n', ...
    supera_criterio);

disp(tabla_resultado);
disp(tabla_candidatos);
disp(tabla_repeticiones);

%% 12. Guardar tablas CSV

writetable( ...
    tabla_resultado, ...
    fullfile( ...
    carpeta_salida, ...
    'tabla_resultado_P1_multitaper.csv'));

writetable( ...
    tabla_candidatos, ...
    fullfile( ...
    carpeta_salida, ...
    'tabla_candidatos_P1_multitaper.csv'));

writetable( ...
    tabla_repeticiones, ...
    fullfile( ...
    carpeta_salida, ...
    'tabla_repeticiones_P1_multitaper.csv'));

writetable( ...
    tabla_score, ...
    fullfile( ...
    carpeta_salida, ...
    'score_promedio_P1_multitaper.csv'));

writetable( ...
    info_repeticiones, ...
    fullfile( ...
    carpeta_salida, ...
    'info_repeticiones_P1_multitaper.csv'));

%% 13. Tabla de candidatos como figura PNG

tabla_candidatos_fig = ...
    tabla_candidatos;

tabla_candidatos_fig.fc_Hz = [];
tabla_candidatos_fig.f_local_Hz = [];

tabla_candidatos_fig.Properties.VariableNames = { ...
    'fc_kHz', ...
    'score_peak', ...
    'f_local_kHz', ...
    'score_local', ...
    'ON_dB', ...
    'OFF_dB', ...
    'rep_positivas', ...
    'rep_3dB', ...
    'rep_totales', ...
    'supera_3dB'};

guardar_tabla_png( ...
    tabla_candidatos_fig, ...
    'TABLA DE CANDIDATOS MULTITAPER P1 - LED TERRENO 1', ...
    fullfile( ...
    carpeta_salida, ...
    '05_P1_multitaper_tabla_candidatos.png'));

%% 14. Tabla resumen como figura PNG

tabla_resultado_fig = ...
    tabla_resultado;

columnas_eliminar = { ...
    'punto', ...
    'led', ...
    'metodo', ...
    'NFFT'};

for c = 1:numel(columnas_eliminar)

    if ismember( ...
            columnas_eliminar{c}, ...
            tabla_resultado_fig.Properties.VariableNames)

        tabla_resultado_fig.(columnas_eliminar{c}) = [];
    end
end

tabla_resultado_fig.Properties.VariableNames = { ...
    'f_ref_kHz', ...
    'ventana_kHz', ...
    'fc_kHz', ...
    'score_dB', ...
    'ON_dB', ...
    'OFF_dB', ...
    'rep_positivas', ...
    'rep_3dB', ...
    'rep_totales', ...
    'criterio_dB', ...
    'supera_3dB', ...
    'NW', ...
    'df_Hz'};

guardar_tabla_png( ...
    tabla_resultado_fig, ...
    'TABLA RESUMEN MULTITAPER P1 - LED TERRENO 1', ...
    fullfile( ...
    carpeta_salida, ...
    '12_P1_multitaper_tabla_resumen.png'));

%% 15. Tabla de repeticiones como figura PNG

tabla_repeticiones_fig = ...
    tabla_repeticiones;

tabla_repeticiones_fig.fc_local_Hz = [];

tabla_repeticiones_fig.Properties.VariableNames = { ...
    'repeticion', ...
    'fc_local_kHz', ...
    'score_local', ...
    'score_positivo_0dB', ...
    'score_positivo_3dB'};

guardar_tabla_png( ...
    tabla_repeticiones_fig, ...
    'TABLA REPETICIONES MULTITAPER P1 - LED TERRENO 1', ...
    fullfile( ...
    carpeta_salida, ...
    '13_P1_multitaper_tabla_repeticiones.png'));

%% 16. Figura 1: score ON-OFF en banda completa

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1500 850]);

plot( ...
    f_banda_kHz, ...
    score_banda_dB, ...
    'LineWidth', 1.5);

hold on;
grid on;
box on;

yline( ...
    0, ...
    '--', ...
    '0 dB', ...
    'HandleVisibility', 'off');

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'HandleVisibility', 'off');

xline( ...
    f_ref_periodograma_Hz/1e3, ...
    '--', ...
    sprintf('Referencia %.3f kHz', ...
    f_ref_periodograma_Hz/1e3), ...
    'LineWidth', 1.1, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

xline( ...
    fc_principal_kHz, ...
    ':', ...
    sprintf('Multitaper %.3f kHz', ...
    fc_principal_kHz), ...
    'LineWidth', 1.3, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');

title( ...
    'P1 / LED terreno 1 - Multitaper: score ON-OFF', ...
    'Interpreter', 'none');

xlim([fmin_Hz fmax_Hz]/1e3);

guardar_figura_png( ...
    fig, ...
    carpeta_salida, ...
    '01_P1_multitaper_score_ON_OFF');

%% 17. Figura 2: candidatos locales

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1200 700]);

x = 1:height(tabla_candidatos);

bar( ...
    x, ...
    tabla_candidatos.score_local_dB, ...
    0.65);

hold on;
grid on;
box on;

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'LineWidth', 1.1, ...
    'LabelHorizontalAlignment', 'right', ...
    'HandleVisibility', 'off');

[~, idx_principal_barra] = min(abs( ...
    tabla_candidatos.f_local_Hz - fc_principal_Hz));

plot( ...
    idx_principal_barra, ...
    tabla_candidatos.score_local_dB(idx_principal_barra) + 0.45, ...
    'kp', ...
    'MarkerSize', 16, ...
    'LineWidth', 2, ...
    'DisplayName', 'Candidato principal');

xlabel('Frecuencia candidata [kHz]');
ylabel('Score local ON-OFF [dB]');

title( ...
    'P1 / LED terreno 1 - Multitaper: candidatos locales', ...
    'Interpreter', 'none');

xticks(x);

xticklabels(compose( ...
    '%.3f', ...
    tabla_candidatos.f_local_kHz));

xtickangle(45);

for i = 1:height(tabla_candidatos)

    if i == idx_principal_barra
        desplazamiento = 0.95;
    else
        desplazamiento = 0.25;
    end

    text( ...
        x(i), ...
        tabla_candidatos.score_local_dB(i) + desplazamiento, ...
        sprintf( ...
        '%.2f dB\n%d/%d', ...
        tabla_candidatos.score_local_dB(i), ...
        tabla_candidatos.rep_3dB(i), ...
        tabla_candidatos.rep_totales(i)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'FontSize', 9);
end

ylim([ ...
    min(0, min(tabla_candidatos.score_local_dB) - 1), ...
    max(criterio_dB + 1, ...
    max(tabla_candidatos.score_local_dB) + 2)]);

legend( ...
    {'Score local ON-OFF', 'Candidato principal'}, ...
    'Location', 'best');

guardar_figura_png( ...
    fig, ...
    carpeta_salida, ...
    '02_P1_multitaper_barras_candidatos');

%% 18. Figura 3: PSD promedio ON/OFF

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1500 850]);

plot( ...
    f_banda_kHz, ...
    PSD_ON_banda_dB, ...
    'LineWidth', 1.5);

hold on;

plot( ...
    f_banda_kHz, ...
    PSD_OFF_banda_dB, ...
    'LineWidth', 1.5);

xline( ...
    f_ref_periodograma_Hz/1e3, ...
    '--', ...
    sprintf('Referencia %.3f kHz', ...
    f_ref_periodograma_Hz/1e3), ...
    'LineWidth', 1.1, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

xline( ...
    fc_principal_kHz, ...
    ':', ...
    sprintf('Multitaper %.3f kHz', ...
    fc_principal_kHz), ...
    'LineWidth', 1.3, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('PSD Multitaper [dB/Hz]');

title( ...
    'P1 / LED terreno 1 - Multitaper: PSD promedio ON/OFF', ...
    'Interpreter', 'none');

legend( ...
    'ON P1 promedio', ...
    'OFF promedio', ...
    'Location', 'best');

xlim([fmin_Hz fmax_Hz]/1e3);

guardar_figura_png( ...
    fig, ...
    carpeta_salida, ...
    '03_P1_multitaper_PSD_promedio_ON_OFF');

%% 19. Figura 4: score por repeticion

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1500 850]);

hold on;

for r = 1:nRep

    plot( ...
        f_banda_kHz, ...
        score_banda_reps_dB(:, r), ...
        'LineWidth', 0.9);
end

plot( ...
    f_banda_kHz, ...
    score_banda_dB, ...
    'k', ...
    'LineWidth', 1.8);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');

title( ...
    'P1 / LED terreno 1 - Multitaper: score por repeticion', ...
    'Interpreter', 'none');

leyenda = cell(nRep + 1, 1);

for r = 1:nRep
    leyenda{r} = sprintf('REP%d', r);
end

leyenda{nRep + 1} = 'Promedio';

legend( ...
    leyenda, ...
    'Location', 'best', ...
    'AutoUpdate', 'off');

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'HandleVisibility', 'off');

yline( ...
    0, ...
    '--', ...
    '0 dB', ...
    'HandleVisibility', 'off');

xline( ...
    f_ref_periodograma_Hz/1e3, ...
    '--', ...
    'LineWidth', 1.0, ...
    'HandleVisibility', 'off');

xline( ...
    fc_principal_kHz, ...
    ':', ...
    'LineWidth', 1.2, ...
    'HandleVisibility', 'off');

xlim([fmin_Hz fmax_Hz]/1e3);

guardar_figura_png( ...
    fig, ...
    carpeta_salida, ...
    '04_P1_multitaper_score_repeticiones');

%% 20. Figura 6: rango amplio

fmax_amplio_usado_Hz = min( ...
    fmax_amplio_Hz, ...
    max(f_ref_Hz));

idx_amplio = ...
    f_ref_Hz >= 0 & ...
    f_ref_Hz <= fmax_amplio_usado_Hz;

[f_amplio_MHz, PSD_ON_amplio_dB, PSD_OFF_amplio_dB] = ...
    reducir_puntos_grafico( ...
    f_ref_Hz(idx_amplio)/1e6, ...
    PSD_ON_prom_dB(idx_amplio), ...
    PSD_OFF_prom_dB(idx_amplio), ...
    80000);

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1200 700]);

plot( ...
    f_amplio_MHz, ...
    PSD_ON_amplio_dB, ...
    'LineWidth', 1.2);

hold on;

plot( ...
    f_amplio_MHz, ...
    PSD_OFF_amplio_dB, ...
    'LineWidth', 1.2);

grid on;
box on;

xlabel('Frecuencia [MHz]');
ylabel('PSD Multitaper [dB/Hz]');

title( ...
    ['P1 / LED terreno 1 - Multitaper: ', ...
     'PSD promedio ON/OFF, rango amplio'], ...
    'Interpreter', 'none');

legend( ...
    'LED encendido', ...
    'LED apagado', ...
    'Location', 'best');

xlim([0 fmax_amplio_usado_Hz/1e6]);

guardar_figura_png( ...
    fig, ...
    carpeta_salida, ...
    '06_P1_multitaper_ON_OFF_rango_amplio');

%% 21. Figura 7: repeticiones ON

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1200 700]);

plot( ...
    f_banda_kHz, ...
    PSD_ON_banda_reps_dB, ...
    'LineWidth', 1.0);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('PSD Multitaper [dB/Hz]');

title( ...
    ['P1 / LED terreno 1 - Multitaper: ', ...
     'repeticiones ON en banda de analisis'], ...
    'Interpreter', 'none');

legend( ...
    compose('ON P1 rep %d', 1:nRep), ...
    'Location', 'best');

xlim([fmin_Hz fmax_Hz]/1e3);

guardar_figura_png( ...
    fig, ...
    carpeta_salida, ...
    '07_P1_multitaper_repeticiones_ON_30_90kHz');

%% 22. Figura 8: repeticiones OFF

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1200 700]);

plot( ...
    f_banda_kHz, ...
    PSD_OFF_banda_reps_dB, ...
    'LineWidth', 1.0);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('PSD Multitaper [dB/Hz]');

title( ...
    ['P1 / LED terreno 1 - Multitaper: ', ...
     'repeticiones OFF en banda de analisis'], ...
    'Interpreter', 'none');

legend( ...
    compose('OFF rep %d', 1:nRep), ...
    'Location', 'best');

xlim([fmin_Hz fmax_Hz]/1e3);

guardar_figura_png( ...
    fig, ...
    carpeta_salida, ...
    '08_P1_multitaper_repeticiones_OFF_30_90kHz');

%% 23. Figura 9: zona local de confirmacion

idx_zoom = ...
    f_banda_Hz >= limite_local_inferior_Hz & ...
    f_banda_Hz <= limite_local_superior_Hz;

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1500 850]);

plot( ...
    f_banda_kHz(idx_zoom), ...
    score_banda_dB(idx_zoom), ...
    'LineWidth', 1.5);

hold on;
grid on;
box on;

yline( ...
    0, ...
    '--', ...
    '0 dB', ...
    'HandleVisibility', 'off');

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'HandleVisibility', 'off');

xline( ...
    f_ref_periodograma_Hz/1e3, ...
    '--', ...
    sprintf('Referencia %.3f kHz', ...
    f_ref_periodograma_Hz/1e3), ...
    'LineWidth', 1.1, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

xline( ...
    fc_principal_kHz, ...
    ':', ...
    sprintf('Multitaper %.3f kHz', ...
    fc_principal_kHz), ...
    'LineWidth', 1.3, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');

title( ...
    ['P1 / LED terreno 1 - Multitaper: ', ...
     'zona local de confirmacion'], ...
    'Interpreter', 'none');

xlim([ ...
    limite_local_inferior_Hz/1e3, ...
    limite_local_superior_Hz/1e3]);

guardar_figura_png( ...
    fig, ...
    carpeta_salida, ...
    '09_P1_multitaper_zoom_local');

%% 24. Figura 10: frecuencia detectada por repeticion

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1200 700]);

bar( ...
    1:nRep, ...
    fc_por_rep_Hz/1e3, ...
    0.65);

hold on;
grid on;
box on;

yline( ...
    fc_principal_kHz, ...
    ':', ...
    sprintf('Resultado %.3f kHz', ...
    fc_principal_kHz), ...
    'LineWidth', 1.3, ...
    'LabelHorizontalAlignment', 'right', ...
    'HandleVisibility', 'off');

xlabel('Repeticion');
ylabel('Frecuencia local [kHz]');

title( ...
    ['P1 / LED terreno 1 - Multitaper: ', ...
     'frecuencia detectada por repeticion'], ...
    'Interpreter', 'none');

xticks(1:nRep);

frecuencia_minima = min([ ...
    fc_por_rep_Hz/1e3; ...
    fc_principal_kHz]);

frecuencia_maxima = max([ ...
    fc_por_rep_Hz/1e3; ...
    fc_principal_kHz]);

margen_frecuencia = max( ...
    0.1, ...
    0.20*(frecuencia_maxima - frecuencia_minima + eps));

ylim([ ...
    frecuencia_minima - margen_frecuencia, ...
    frecuencia_maxima + margen_frecuencia]);

for r = 1:nRep

    text( ...
        r, ...
        fc_por_rep_Hz(r)/1e3 + 0.03, ...
        sprintf('%.3f kHz', ...
        fc_por_rep_Hz(r)/1e3), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'FontSize', 9);
end

guardar_figura_png( ...
    fig, ...
    carpeta_salida, ...
    '10_P1_multitaper_frecuencia_por_repeticion');

%% 25. Figura 11: score maximo por repeticion

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1200 700]);

bar( ...
    1:nRep, ...
    score_por_rep_dB, ...
    0.65);

hold on;
grid on;
box on;

yline( ...
    0, ...
    '--', ...
    '0 dB', ...
    'HandleVisibility', 'off');

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'LineWidth', 1.1, ...
    'LabelHorizontalAlignment', 'right', ...
    'HandleVisibility', 'off');

xlabel('Repeticion');
ylabel('Score local maximo [dB]');

title( ...
    ['P1 / LED terreno 1 - Multitaper: ', ...
     'score maximo por repeticion'], ...
    'Interpreter', 'none');

xticks(1:nRep);

ylim([ ...
    min(0, min(score_por_rep_dB) - 1), ...
    max([criterio_dB, score_por_rep_dB']) + 1.5]);

for r = 1:nRep

    if score_por_rep_dB(r) >= 0

        alineacion = 'bottom';
        desplazamiento = 0.15;

    else

        alineacion = 'top';
        desplazamiento = -0.15;
    end

    text( ...
        r, ...
        score_por_rep_dB(r) + desplazamiento, ...
        sprintf( ...
        '%.2f dB\n%.3f kHz', ...
        score_por_rep_dB(r), ...
        fc_por_rep_Hz(r)/1e3), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', alineacion, ...
        'FontSize', 9);
end

guardar_figura_png( ...
    fig, ...
    carpeta_salida, ...
    '11_P1_multitaper_score_por_repeticion');

%% 26. Guardar un unico archivo MAT

save( ...
    fullfile( ...
    carpeta_salida, ...
    'datos_P1_multitaper.mat'), ...
    'f_ref_Hz', ...
    'f_banda_Hz', ...
    'f_banda_kHz', ...
    'PSD_ON_mat_dB', ...
    'PSD_OFF_mat_dB', ...
    'PSD_ON_prom_dB', ...
    'PSD_OFF_prom_dB', ...
    'PSD_ON_banda_dB', ...
    'PSD_OFF_banda_dB', ...
    'PSD_ON_banda_reps_dB', ...
    'PSD_OFF_banda_reps_dB', ...
    'score_rep_dB', ...
    'score_prom_dB', ...
    'score_banda_dB', ...
    'score_banda_reps_dB', ...
    'tabla_resultado', ...
    'tabla_candidatos', ...
    'tabla_repeticiones', ...
    'tabla_score', ...
    'info_repeticiones', ...
    'f_ref_periodograma_Hz', ...
    'semiancho_busqueda_local_Hz', ...
    'limite_local_inferior_Hz', ...
    'limite_local_superior_Hz', ...
    'f_max_global_Hz', ...
    'score_max_global_dB', ...
    'fc_principal_Hz', ...
    'fc_principal_kHz', ...
    'score_principal_dB', ...
    'fc_por_rep_Hz', ...
    'score_por_rep_dB', ...
    'criterio_dB', ...
    'Fs_configurada_Hz', ...
    'NW', ...
    'NFFT', ...
    'distancia_minima_Hz', ...
    'ventana_refinamiento_Hz', ...
    'ventana_repetibilidad_Hz');

fprintf('\n============================================================\n');
fprintf('ANALISIS MULTITAPER FINALIZADO\n');
fprintf('Resultados guardados en:\n%s\n', carpeta_salida);
fprintf('No se generaron archivos FIG ni copias adicionales.\n');
fprintf('============================================================\n');

%% Funciones locales

function [t, y] = leer_csv_rigol_terreno(nombre_archivo)

    if ~isfile(nombre_archivo)

        error( ...
            'No se encuentra el archivo:\n%s', ...
            nombre_archivo);
    end

    M = readmatrix(nombre_archivo);

    if size(M, 2) < 2

        error( ...
            ['El archivo no contiene al menos dos columnas ', ...
             'numericas:\n%s'], ...
            nombre_archivo);
    end

    columnas_validas = [];

    for c = 1:size(M, 2)

        if sum(isfinite(M(:, c))) > 10

            columnas_validas = [ ...
                columnas_validas, ...
                c]; %#ok<AGROW>
        end
    end

    if numel(columnas_validas) < 2

        error( ...
            ['No se detectaron dos columnas numericas validas ', ...
             'en:\n%s'], ...
            nombre_archivo);
    end

    t = M(:, columnas_validas(1));
    y = M(:, columnas_validas(2));

    idx_validos = ...
        isfinite(t) & ...
        isfinite(y);

    t = t(idx_validos);
    y = y(idx_validos);

    t = t(:);
    y = y(:);

    if numel(y) < 10

        error( ...
            ['El archivo contiene muy pocas muestras validas ', ...
             'en:\n%s'], ...
            nombre_archivo);
    end
end

function fila = crear_fila_info( ...
    archivo, ...
    condicion, ...
    repeticion, ...
    muestras_originales, ...
    muestras_usadas, ...
    duracion_s, ...
    Fs_duracion_Hz, ...
    Fs_usada_Hz, ...
    error_Fs_pct, ...
    NW, ...
    NFFT, ...
    df_Hz)

    fila = table( ...
        archivo, ...
        condicion, ...
        repeticion, ...
        muestras_originales, ...
        muestras_usadas, ...
        duracion_s, ...
        Fs_duracion_Hz, ...
        Fs_usada_Hz, ...
        error_Fs_pct, ...
        NW, ...
        NFFT, ...
        df_Hz, ...
        'VariableNames', { ...
        'Archivo', ...
        'Condicion', ...
        'Repeticion', ...
        'Muestras_originales', ...
        'Muestras_usadas', ...
        'Duracion_s', ...
        'Fs_duracion_Hz', ...
        'Fs_usada_Hz', ...
        'Error_Fs_pct', ...
        'NW', ...
        'NFFT', ...
        'df_Hz'});
end

function guardar_figura_png( ...
    fig, ...
    carpeta_salida, ...
    nombre_archivo)

    archivo_png = fullfile( ...
        carpeta_salida, ...
        [nombre_archivo '.png']);

    try

        exportgraphics( ...
            fig, ...
            archivo_png, ...
            'Resolution', 300);

    catch

        print( ...
            fig, ...
            archivo_png, ...
            '-dpng', ...
            '-r300');
    end
end

function guardar_tabla_png( ...
    tabla, ...
    titulo_tabla, ...
    archivo_png)

    if isempty(tabla)

        warning( ...
            'La tabla esta vacia. No se guardara la figura.');

        return;
    end

    datos = ...
        formatear_tabla_para_figura(tabla);

    nombres = ...
        tabla.Properties.VariableNames;

    nFilas = ...
        height(tabla);

    nColumnas = ...
        width(tabla);

    ancho_columnas = ...
        zeros(1, nColumnas);

    for c = 1:nColumnas

        largo_maximo = ...
            length(nombres{c});

        for i = 1:nFilas

            largo_maximo = max( ...
                largo_maximo, ...
                length(datos{i, c}));
        end

        ancho_columnas(c) = max( ...
            75, ...
            min(155, 8*largo_maximo + 24));
    end

    margen_izquierdo = 30;
    margen_derecho = 30;
    margen_inferior = 25;

    alto_titulo = 55;
    alto_fila = 28;
    alto_encabezado = 30;

    ancho_tabla = ...
        sum(ancho_columnas);

    alto_tabla = ...
        alto_encabezado + nFilas*alto_fila;

    ancho_figura = ...
        margen_izquierdo + ancho_tabla + margen_derecho;

    alto_figura = ...
        margen_inferior + alto_tabla + alto_titulo + 15;

    fig = figure( ...
        'Color', 'w', ...
        'Units', 'pixels', ...
        'Position', [ ...
        100, ...
        100, ...
        ancho_figura, ...
        alto_figura]);

    ax = axes( ...
        'Parent', fig, ...
        'Units', 'pixels', ...
        'Position', [ ...
        0, ...
        0, ...
        ancho_figura, ...
        alto_figura]);

    axis(ax, [0 ancho_figura 0 alto_figura]);
    axis(ax, 'off');
    hold(ax, 'on');

    text( ...
        ax, ...
        ancho_figura/2, ...
        alto_figura - 28, ...
        titulo_tabla, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontWeight', 'bold', ...
        'FontSize', 15, ...
        'Interpreter', 'none');

    x0 = margen_izquierdo;
    y0 = margen_inferior + alto_tabla;

    color_encabezado = [0.93 0.93 0.93];
    color_fila_1 = [1 1 1];
    color_fila_2 = [0.94 0.94 0.94];
    color_borde = [0.65 0.65 0.65];

    x = x0;

    for c = 1:nColumnas

        rectangle( ...
            ax, ...
            'Position', [ ...
            x, ...
            y0 - alto_encabezado, ...
            ancho_columnas(c), ...
            alto_encabezado], ...
            'FaceColor', color_encabezado, ...
            'EdgeColor', color_borde, ...
            'LineWidth', 0.8);

        text( ...
            ax, ...
            x + ancho_columnas(c)/2, ...
            y0 - alto_encabezado/2, ...
            nombres{c}, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontWeight', 'bold', ...
            'FontSize', 9, ...
            'Interpreter', 'none');

        x = x + ancho_columnas(c);
    end

    for i = 1:nFilas

        y = ...
            y0 - alto_encabezado - i*alto_fila;

        if mod(i, 2) == 0

            color_fila = color_fila_2;

        else

            color_fila = color_fila_1;
        end

        x = x0;

        for c = 1:nColumnas

            rectangle( ...
                ax, ...
                'Position', [ ...
                x, ...
                y, ...
                ancho_columnas(c), ...
                alto_fila], ...
                'FaceColor', color_fila, ...
                'EdgeColor', [0.88 0.88 0.88], ...
                'LineWidth', 0.5);

            text( ...
                ax, ...
                x + ancho_columnas(c)/2, ...
                y + alto_fila/2, ...
                datos{i, c}, ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'middle', ...
                'FontSize', 9, ...
                'Interpreter', 'none');

            x = x + ancho_columnas(c);
        end
    end

    drawnow;

    print( ...
        fig, ...
        archivo_png, ...
        '-dpng', ...
        '-r300');
end

function datos = formatear_tabla_para_figura(tabla)

    nFilas = ...
        height(tabla);

    nColumnas = ...
        width(tabla);

    datos = ...
        cell(nFilas, nColumnas);

    nombres = ...
        tabla.Properties.VariableNames;

    for c = 1:nColumnas

        nombre = ...
            nombres{c};

        columna = ...
            tabla.(nombre);

        for i = 1:nFilas

            if iscell(columna)

                valor = ...
                    columna{i};

            else

                valor = ...
                    columna(i);
            end

            if isnumeric(valor)

                if isnan(valor)

                    texto = '';

                elseif contains( ...
                        nombre, ...
                        'kHz', ...
                        'IgnoreCase', true)

                    texto = ...
                        sprintf('%.4f', valor);

                elseif contains( ...
                        nombre, ...
                        'Hz', ...
                        'IgnoreCase', true)

                    texto = ...
                        sprintf('%.4f', valor);

                elseif contains( ...
                        nombre, ...
                        'dB', ...
                        'IgnoreCase', true)

                    texto = ...
                        sprintf('%.4f', valor);

                elseif contains( ...
                        nombre, ...
                        'rep', ...
                        'IgnoreCase', true)

                    texto = ...
                        sprintf('%.0f', valor);

                elseif contains( ...
                        nombre, ...
                        'NW', ...
                        'IgnoreCase', true)

                    texto = ...
                        sprintf('%.2f', valor);

                else

                    texto = ...
                        sprintf('%.4f', valor);
                end

            elseif islogical(valor)

                if valor

                    texto = 'Si';

                else

                    texto = 'No';
                end

            elseif isstring(valor)

                texto = ...
                    char(valor);

            elseif ischar(valor)

                texto = ...
                    valor;

            else

                texto = ...
                    char(string(valor));
            end

            datos{i, c} = ...
                texto;
        end
    end
end

function [x_salida, y1_salida, y2_salida] = ...
    reducir_puntos_grafico( ...
    x, ...
    y1, ...
    y2, ...
    nMaximo)

    x = x(:);
    y1 = y1(:);
    y2 = y2(:);

    nPuntos = ...
        numel(x);

    if nPuntos > nMaximo

        indices = round( ...
            linspace(1, nPuntos, nMaximo));

    else

        indices = ...
            1:nPuntos;
    end

    x_salida = ...
        x(indices);

    y1_salida = ...
        y1(indices);

    y2_salida = ...
        y2(indices);
end