%% LED2_03_multitaper_V2_afinada_local.m
%
% INSTRUCCIONES DE USO
% Antes de ejecutar este script, revisar la variable carpeta_csv
% y modificarla si los archivos .csv se encuentran en otra ruta local.
% La carpeta indicada debe contener los archivos ON_LED2_rep*.csv
% y OFF_LED2_rep*.csv definidos en las listas archivos_ON
% y archivos_OFF.
%
% Ejemplo:
% carpeta_csv = 'C:\Users\NombreUsuario\Desktop\Pruebas LED 2';

clear; 
clc; 
close all;

%% 1. Configuracion general

carpeta_csv = 'C:\Users\mudrood\Desktop\Modulo Prof\Archivos Tesis\Toma de Datos\Pruebas LED 2';

carpeta_general = fullfile(carpeta_csv, 'Resultados_LED2_modificados');
carpeta_salida = fullfile(carpeta_general, '03_Multitaper');

if ~exist(carpeta_general, 'dir')
    mkdir(carpeta_general);
end

if ~exist(carpeta_salida, 'dir')
    mkdir(carpeta_salida);
end

archivos_ON = {
    'ON_LED2_rep1.csv'
    'ON_LED2_rep2.csv'
    'ON_LED2_rep3.csv'
    'ON_LED2_rep4.csv'
};

archivos_OFF = {
    'OFF_LED2_rep1.csv'
    'OFF_LED2_rep2.csv'
    'OFF_LED2_rep3.csv'
    'OFF_LED2_rep4.csv'
};

nrep = numel(archivos_ON);

%% 2. Parametros Multitaper local

fc_ref_Hz = 45375;

ancho_local_Hz = 1000;

fmin_local = fc_ref_Hz - ancho_local_Hz;
fmax_local = fc_ref_Hz + ancho_local_Hz;

NW = 2.5;

umbralScoreRep_dB = 3;
ventana_rep_Hz = 200;

fprintf('\n============================================\n');
fprintf('MULTITAPER LOCAL LED 2\n');
fprintf('============================================\n');
fprintf('Carpeta entrada:\n%s\n', carpeta_csv);
fprintf('\nCarpeta salida:\n%s\n', carpeta_salida);
fprintf('\nFrecuencia referencia = %.3f Hz = %.3f kHz\n', fc_ref_Hz, fc_ref_Hz/1e3);
fprintf('Ventana local = %.1f Hz a %.1f Hz\n', fmin_local, fmax_local);
fprintf('NW = %.2f\n', NW);

%% 3. Lectura y calculo Multitaper por repeticion

P_ON = [];
P_OFF = [];
score_por_rep = [];
fc_por_rep = zeros(nrep,1);
score_local_max = zeros(nrep,1);
score_positivo_0dB = false(nrep,1);
score_positivo_3dB = false(nrep,1);

info_archivos = table();

for k = 1:nrep

    archivo_on = fullfile(carpeta_csv, archivos_ON{k});
    archivo_off = fullfile(carpeta_csv, archivos_OFF{k});

    [t_on, y_on] = leer_csv_rigol_simple_local(archivo_on);
    [t_off, y_off] = leer_csv_rigol_simple_local(archivo_off);

    Fs = 1 / median(diff(t_on));

    Fs_mean_on = 1 / mean(diff(t_on));
    Fs_median_on = 1 / median(diff(t_on));
    Fs_mean_off = 1 / mean(diff(t_off));
    Fs_median_off = 1 / median(diff(t_off));

    N_on = numel(y_on);
    N_off = numel(y_off);

    N = N_on;

    T_on = t_on(end) - t_on(1);
    T_off = t_off(end) - t_off(1);

    fprintf('\n--------------------------------------------\n');
    fprintf('Repeticion %d/%d\n', k, nrep);
    fprintf('ON : %s\n', archivos_ON{k});
    fprintf('OFF: %s\n', archivos_OFF{k});
    fprintf('N ON  = %d muestras\n', N_on);
    fprintf('N OFF = %d muestras\n', N_off);
    fprintf('Fs usada = %.6f MSa/s\n', Fs/1e6);
    fprintf('Duracion ON  = %.9f s\n', T_on);
    fprintf('Duracion OFF = %.9f s\n', T_off);

    info_archivos = [info_archivos; crear_fila_info( ...
        string(archivos_ON{k}), "ON", k, N_on, Fs_mean_on, Fs_median_on, T_on)];

    info_archivos = [info_archivos; crear_fila_info( ...
        string(archivos_OFF{k}), "OFF", k, N_off, Fs_mean_off, Fs_median_off, T_off)];

    if N_on ~= N_off
        warning('La repeticion %d tiene distinto numero de muestras ON/OFF.', k);
    end

    NFFT = N;

    [Pxx_on, f] = pmtm(y_on, NW, NFFT, Fs);
    [Pxx_off, f_off] = pmtm(y_off, NW, NFFT, Fs);

    if numel(f) ~= numel(f_off) || max(abs(f - f_off)) > 1e-9
        error('La grilla de frecuencia ON/OFF no coincide en la repeticion %d.', k);
    end

    P_ON(:,k) = 10*log10(Pxx_on + eps);
    P_OFF(:,k) = 10*log10(Pxx_off + eps);

    score_por_rep(:,k) = P_ON(:,k) - P_OFF(:,k);

    idx_local = f >= fmin_local & f <= fmax_local;

    if ~any(idx_local)
        error('La mascara local quedo vacia. Revisar fc_ref_Hz, ancho_local_Hz, Fs o NFFT.');
    end

    f_local = f(idx_local);
    score_local_rep = score_por_rep(idx_local,k);

    [score_local_max(k), idx_max] = max(score_local_rep);
    fc_por_rep(k) = f_local(idx_max);

    score_positivo_0dB(k) = score_local_max(k) > 0;
    score_positivo_3dB(k) = score_local_max(k) >= umbralScoreRep_dB;

    fprintf('fc local rep %d = %.3f Hz = %.3f kHz | score = %.4f dB\n', ...
        k, fc_por_rep(k), fc_por_rep(k)/1e3, score_local_max(k));
end

%% 4. Promedios generales

P_ON_prom = mean(P_ON, 2);
P_OFF_prom = mean(P_OFF, 2);

score_prom = P_ON_prom - P_OFF_prom;

idx_local = f >= fmin_local & f <= fmax_local;

f_local = f(idx_local);
P_ON_local = P_ON_prom(idx_local);
P_OFF_local = P_OFF_prom(idx_local);
score_local = score_prom(idx_local);

[score_local_prom_max, idx_max_prom] = max(score_local);

fc_local = f_local(idx_max_prom);

ON_dB = P_ON_local(idx_max_prom);
OFF_dB = P_OFF_local(idx_max_prom);

rep_positivas_0dB = sum(score_positivo_0dB);
rep_positivas_3dB = sum(score_positivo_3dB);

fprintf('\n============================================\n');
fprintf('RESULTADO MULTITAPER LOCAL LED 2\n');
fprintf('============================================\n');
fprintf('fc referencia = %.3f Hz = %.3f kHz\n', fc_ref_Hz, fc_ref_Hz/1e3);
fprintf('fc local promedio = %.3f Hz = %.3f kHz\n', fc_local, fc_local/1e3);
fprintf('score local promedio = %.4f dB\n', score_local_prom_max);
fprintf('ON  = %.4f dB/Hz\n', ON_dB);
fprintf('OFF = %.4f dB/Hz\n', OFF_dB);
fprintf('Repeticiones positivas > 0 dB: %d/%d\n', rep_positivas_0dB, nrep);
fprintf('Repeticiones positivas >= %.1f dB: %d/%d\n', ...
    umbralScoreRep_dB, rep_positivas_3dB, nrep);

%% 5. Tabla por repeticion

tabla_repeticiones = table( ...
    (1:nrep)', ...
    round(fc_por_rep), ...
    fc_por_rep/1e3, ...
    score_local_max, ...
    strings(nrep,1), ...
    strings(nrep,1), ...
    'VariableNames', { ...
    'repeticion', ...
    'fc_local_Hz', ...
    'fc_local_kHz', ...
    'score_local_dB', ...
    'score_positivo_0dB', ...
    'score_positivo_3dB'});

for k = 1:nrep
    if score_positivo_0dB(k)
        tabla_repeticiones.score_positivo_0dB(k) = "Si";
    else
        tabla_repeticiones.score_positivo_0dB(k) = "No";
    end

    if score_positivo_3dB(k)
        tabla_repeticiones.score_positivo_3dB(k) = "Si";
    else
        tabla_repeticiones.score_positivo_3dB(k) = "No";
    end
end

%% 6. Tabla resumen

tabla_resumen = table( ...
    fc_ref_Hz, ...
    fc_ref_Hz/1e3, ...
    ancho_local_Hz, ...
    fmin_local, ...
    fmax_local, ...
    round(fc_local), ...
    fc_local/1e3, ...
    score_local_prom_max, ...
    ON_dB, ...
    OFF_dB, ...
    rep_positivas_0dB, ...
    rep_positivas_3dB, ...
    nrep, ...
    umbralScoreRep_dB, ...
    ventana_rep_Hz, ...
    NW, ...
    NFFT, ...
    f(2)-f(1), ...
    'VariableNames', { ...
    'fc_ref_Hz', ...
    'fc_ref_kHz', ...
    'ancho_local_Hz', ...
    'fmin_local_Hz', ...
    'fmax_local_Hz', ...
    'fc_local_Hz', ...
    'fc_local_kHz', ...
    'score_local_dB', ...
    'ON_dB', ...
    'OFF_dB', ...
    'rep_positivas_0dB', ...
    'rep_positivas_3dB', ...
    'rep_totales', ...
    'umbral_repetibilidad_dB', ...
    'ventana_repetibilidad_Hz', ...
    'NW', ...
    'NFFT', ...
    'df_grilla_Hz'});

fprintf('\n============================================\n');
fprintf('TABLA REPETICIONES MULTITAPER LOCAL LED 2\n');
fprintf('============================================\n');
disp(tabla_repeticiones);

fprintf('\n============================================\n');
fprintf('TABLA RESUMEN MULTITAPER LOCAL LED 2\n');
fprintf('============================================\n');
disp(tabla_resumen);

%% 7. Guardar tablas CSV

writetable(tabla_repeticiones, ...
    fullfile(carpeta_salida, 'tabla_MT_LED2_V2_local_repeticiones.csv'));

writetable(tabla_resumen, ...
    fullfile(carpeta_salida, 'tabla_MT_LED2_V2_local_resumen.csv'));

writetable(info_archivos, ...
    fullfile(carpeta_salida, 'info_archivos_MT_LED2_V2_local.csv'));

%% 8. Figura 1: score por repeticion alrededor de fc_ref

fig = figure('Color','w','Position',[100 100 1350 720]);
hold on;

for k = 1:nrep
    plot(f_local/1e3, score_por_rep(idx_local,k), 'LineWidth', 1.0, ...
        'DisplayName', sprintf('Rep %d', k));
end

plot(f_local/1e3, score_local, 'k', 'LineWidth', 2.0, ...
    'DisplayName','Promedio');

yline(0, '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.0, ...
    'HandleVisibility','off');

yline(umbralScoreRep_dB, '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.1, ...
    'HandleVisibility','off');

xline(fc_ref_Hz/1e3, '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth', 1.2, ...
    'HandleVisibility','off');

xline(fc_local/1e3, ':', ...
    'Color',[0.15 0.15 0.15], ...
    'LineWidth', 1.3, ...
    'HandleVisibility','off');

grid on;
box on;
xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');
title('LED 2 - Multitaper local: score por repeticion alrededor de 45.375 kHz', ...
    'Interpreter','none');

xlim([fmin_local fmax_local]/1e3);
ylim([-20 20]);

legend('Location','eastoutside');

xl = xlim;
yl = ylim;
xr = xl(2) - xl(1);
yr = yl(2) - yl(1);
xoff = 0.012 * xr;

text(xl(2)-0.02*xr, umbralScoreRep_dB+0.35, ...
    sprintf('Criterio %.1f dB', umbralScoreRep_dB), ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(xl(2)-0.02*xr, 0+0.35, ...
    '0 dB', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(fc_local/1e3 - xoff, yl(1) + 0.78*yr, ...
    sprintf('LOCAL\n%.3f kHz', fc_local/1e3), ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'Color','k', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'BackgroundColor','white', ...
    'Margin',2, ...
    'Clipping','on');

text(fc_ref_Hz/1e3 + xoff, yl(1) + 0.90*yr, ...
    sprintf('REF.\n%.3f kHz', fc_ref_Hz/1e3), ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'Color','k', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'BackgroundColor','white', ...
    'Margin',2, ...
    'Clipping','on');

saveas(fig, fullfile(carpeta_salida, 'MT_LED2_V2_local_score_repeticiones_45kHz.png'));
savefig(fig, fullfile(carpeta_salida, 'MT_LED2_V2_local_score_repeticiones_45kHz.fig'));

%% 9. Figura 2: score promedio local

fig = figure('Color','w','Position',[100 100 1350 720]);

plot(f_local/1e3, score_local, 'LineWidth', 1.5, ...
    'DisplayName','Score promedio');
hold on;

plot(fc_local/1e3, score_local_prom_max, 'o', ...
    'MarkerSize', 8, ...
    'LineWidth', 1.8, ...
    'DisplayName','Maximo local');

yline(0, '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.0, ...
    'HandleVisibility','off');

yline(umbralScoreRep_dB, '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.1, ...
    'HandleVisibility','off');

xline(fc_ref_Hz/1e3, '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth', 1.2, ...
    'HandleVisibility','off');

xline(fc_local/1e3, ':', ...
    'Color',[0.15 0.15 0.15], ...
    'LineWidth', 1.3, ...
    'HandleVisibility','off');

grid on;
box on;
xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');
title('LED 2 - Multitaper local: score ON-OFF alrededor de 45.375 kHz', ...
    'Interpreter','none');

xlim([fmin_local fmax_local]/1e3);
ylim([-6 8]);

legend('Location','eastoutside');

xl = xlim;
yl = ylim;
xr = xl(2) - xl(1);
yr = yl(2) - yl(1);
xoff = 0.012 * xr;

text(xl(2)-0.02*xr, umbralScoreRep_dB+0.25, ...
    sprintf('Criterio %.1f dB', umbralScoreRep_dB), ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(xl(2)-0.02*xr, 0+0.25, ...
    '0 dB', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(fc_local/1e3 - xoff, yl(1) + 0.78*yr, ...
    sprintf('LOCAL\n%.3f kHz', fc_local/1e3), ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'Color','k', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'BackgroundColor','white', ...
    'Margin',2, ...
    'Clipping','on');

text(fc_ref_Hz/1e3 + xoff, yl(1) + 0.90*yr, ...
    sprintf('REF.\n%.3f kHz', fc_ref_Hz/1e3), ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'Color','k', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'BackgroundColor','white', ...
    'Margin',2, ...
    'Clipping','on');

saveas(fig, fullfile(carpeta_salida, 'MT_LED2_V2_local_score_45kHz.png'));
savefig(fig, fullfile(carpeta_salida, 'MT_LED2_V2_local_score_45kHz.fig'));

%% 10. Figura 3: PSD promedio ON/OFF local

fig = figure('Color','w','Position',[100 100 1350 720]);

plot(f_local/1e3, P_ON_local, 'LineWidth', 1.5, ...
    'DisplayName','LED encendido');
hold on;

plot(f_local/1e3, P_OFF_local, 'LineWidth', 1.5, ...
    'DisplayName','LED apagado');

xline(fc_ref_Hz/1e3, '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth', 1.2, ...
    'HandleVisibility','off');

xline(fc_local/1e3, ':', ...
    'Color',[0.15 0.15 0.15], ...
    'LineWidth', 1.3, ...
    'HandleVisibility','off');

grid on;
box on;
xlabel('Frecuencia [kHz]');
ylabel('PSD Multitaper [dB/Hz]');
title('LED 2 - Multitaper local: PSD ON/OFF, referencia 45.375 kHz', ...
    'Interpreter','none');

xlim([fmin_local fmax_local]/1e3);

legend('Location','eastoutside');

xl = xlim;
yl = ylim;
xr = xl(2) - xl(1);
yr = yl(2) - yl(1);
xoff = 0.012 * xr;

text(fc_local/1e3 - xoff, yl(1) + 0.78*yr, ...
    sprintf('LOCAL\n%.3f kHz', fc_local/1e3), ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'Color','k', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','middle', ...
    'BackgroundColor','white', ...
    'Margin',2, ...
    'Clipping','on');

text(fc_ref_Hz/1e3 + xoff, yl(1) + 0.90*yr, ...
    sprintf('REF.\n%.3f kHz', fc_ref_Hz/1e3), ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'Color','k', ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','middle', ...
    'BackgroundColor','white', ...
    'Margin',2, ...
    'Clipping','on');

saveas(fig, fullfile(carpeta_salida, 'MT_LED2_V2_local_ON_OFF_45kHz.png'));
savefig(fig, fullfile(carpeta_salida, 'MT_LED2_V2_local_ON_OFF_45kHz.fig'));

%% 11. Figura 4: frecuencia detectada por repeticion

fig = figure('Color','w','Position',[100 100 1350 720]);

bar(1:nrep, fc_por_rep/1e3);
hold on;
grid on;
box on;

yline(fc_ref_Hz/1e3, '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth', 1.2, ...
    'HandleVisibility','off');

yline(fc_local/1e3, ':', ...
    'Color',[0.15 0.15 0.15], ...
    'LineWidth', 1.3, ...
    'HandleVisibility','off');

xlabel('Repeticion');
ylabel('Frecuencia local [kHz]');
title('LED 2 - Multitaper local: frecuencia detectada por repeticion', ...
    'Interpreter','none');

xticks(1:nrep);
xlim([0.5 nrep+0.5]);

ymin = min([fc_por_rep(:); fc_ref_Hz; fc_local])/1e3 - 0.8;
ymax = max([fc_por_rep(:); fc_ref_Hz; fc_local])/1e3 + 0.8;
ylim([ymin ymax]);

xl = xlim;

text(xl(2)-0.05, fc_ref_Hz/1e3 + 0.08, ...
    sprintf('Referencia %.3f kHz', fc_ref_Hz/1e3), ...
    'HorizontalAlignment','right', ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(xl(2)-0.05, fc_local/1e3 - 0.12, ...
    sprintf('Local promedio %.3f kHz', fc_local/1e3), ...
    'HorizontalAlignment','right', ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'BackgroundColor','w', ...
    'Margin',0.5);

for k = 1:nrep
    text(k, fc_por_rep(k)/1e3 + 0.08, ...
        sprintf('%.3f kHz', fc_por_rep(k)/1e3), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',9);
end

saveas(fig, fullfile(carpeta_salida, 'MT_LED2_V2_local_frecuencia_por_repeticion.png'));
savefig(fig, fullfile(carpeta_salida, 'MT_LED2_V2_local_frecuencia_por_repeticion.fig'));

%% 12. Figura 5: score maximo por repeticion

fig = figure('Color','w','Position',[100 100 1350 720]);

bar(1:nrep, score_local_max);
hold on;
grid on;
box on;

yline(0, '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth',1.0, ...
    'HandleVisibility','off');

yline(umbralScoreRep_dB, '--', ...
    'Color',[0.35 0.35 0.35], ...
    'LineWidth', 1.2, ...
    'HandleVisibility','off');

xlabel('Repeticion');
ylabel('Score local maximo [dB]');
title('LED 2 - Multitaper local: score maximo por repeticion', ...
    'Interpreter','none');

xticks(1:nrep);
xlim([0.5 nrep+0.5]);

ylim([0, max(score_local_max) + 2.0]);

xl = xlim;

text(xl(2)-0.05, umbralScoreRep_dB + 0.25, ...
    sprintf('Criterio %.1f dB', umbralScoreRep_dB), ...
    'HorizontalAlignment','right', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(xl(2)-0.05, 0 + 0.25, ...
    '0 dB', ...
    'HorizontalAlignment','right', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

for k = 1:nrep
    text(k, score_local_max(k)+0.35, ...
        sprintf('%.2f dB\n%.3f kHz', score_local_max(k), fc_por_rep(k)/1e3), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',9);
end

saveas(fig, fullfile(carpeta_salida, 'MT_LED2_V2_local_score_por_repeticion.png'));
savefig(fig, fullfile(carpeta_salida, 'MT_LED2_V2_local_score_por_repeticion.fig'));

%% 13. Guardar tablas como figuras

tabla_repeticiones_fig = tabla_repeticiones;

if ismember('fc_local_Hz', tabla_repeticiones_fig.Properties.VariableNames)
    tabla_repeticiones_fig.fc_local_Hz = [];
end

tabla_repeticiones_fig.Properties.VariableNames = { ...
    'repeticion', ...
    'fc_local_kHz', ...
    'score_local', ...
    'score_positivo_0dB', ...
    'score_positivo_3dB'};

guardar_tabla_como_figura_compacta( ...
    tabla_repeticiones_fig, ...
    'TABLA REPETICIONES MULTITAPER LOCAL LED 2', ...
    fullfile(carpeta_salida, 'tabla_MT_LED2_V2_local_repeticiones.png'), ...
    fullfile(carpeta_salida, 'tabla_MT_LED2_V2_local_repeticiones.fig'));

tabla_resumen_fig = tabla_resumen;

cols_eliminar = { ...
    'fc_ref_Hz', ...
    'ancho_local_Hz', ...
    'fmin_local_Hz', ...
    'fmax_local_Hz', ...
    'fc_local_Hz', ...
    'ventana_repetibilidad_Hz', ...
    'NFFT', ...
    'df_grilla_Hz'};

for c = 1:numel(cols_eliminar)
    if ismember(cols_eliminar{c}, tabla_resumen_fig.Properties.VariableNames)
        tabla_resumen_fig.(cols_eliminar{c}) = [];
    end
end

tabla_resumen_fig.Properties.VariableNames = { ...
    'fc_ref_kHz', ...
    'fc_local_kHz', ...
    'score_local', ...
    'ON_dB', ...
    'OFF_dB', ...
    'rep_0dB', ...
    'rep_3dB', ...
    'rep_totales', ...
    'umbral_3dB', ...
    'NW'};

guardar_tabla_como_figura_compacta( ...
    tabla_resumen_fig, ...
    'TABLA RESUMEN MULTITAPER LOCAL LED 2', ...
    fullfile(carpeta_salida, 'tabla_MT_LED2_V2_local_resumen.png'), ...
    fullfile(carpeta_salida, 'tabla_MT_LED2_V2_local_resumen.fig'));

%% 14. Guardar variables

save(fullfile(carpeta_salida, 'datos_MT_LED2_V2_local_45kHz.mat'), ...
    'f', ...
    'P_ON', ...
    'P_OFF', ...
    'P_ON_prom', ...
    'P_OFF_prom', ...
    'score_prom', ...
    'score_por_rep', ...
    'tabla_repeticiones', ...
    'tabla_resumen', ...
    'info_archivos', ...
    'fc_ref_Hz', ...
    'fc_local', ...
    'fc_por_rep', ...
    'score_local_max', ...
    'score_local_prom_max', ...
    'rep_positivas_0dB', ...
    'rep_positivas_3dB', ...
    'fmin_local', ...
    'fmax_local', ...
    'ancho_local_Hz', ...
    'ventana_rep_Hz', ...
    'umbralScoreRep_dB', ...
    'NW', ...
    'NFFT', ...
    'nrep');

fprintf('\n============================================\n');
fprintf('Multitaper local LED2 terminado.\n');
fprintf('Resultados guardados en:\n%s\n', carpeta_salida);
fprintf('============================================\n');

%% ============================================================
% Funcion local para leer CSV Rigol

function [t, y] = leer_csv_rigol_simple_local(nombre_archivo)

    if ~isfile(nombre_archivo)
        error('No se encuentra el archivo: %s', nombre_archivo);
    end

    T = readtable(nombre_archivo, 'VariableNamingRule', 'preserve');

    M = [];

    for c = 1:width(T)

        col = T{:, c};

        if iscell(col)
            col_num = str2double(col);
        elseif isstring(col)
            col_num = str2double(col);
        else
            col_num = double(col);
        end

        if sum(~isnan(col_num)) > 10
            M = [M, col_num]; %#ok<AGROW>
        end
    end

    M = M(all(~isnan(M), 2), :);

    if size(M, 2) < 2
        error('No se detectaron dos columnas numericas en: %s', nombre_archivo);
    end

    t = M(:,1);
    y = M(:,2);

    t = t(:);
    y = y(:);

    [t, idx] = unique(t, 'stable');
    y = y(idx);

    y = y - mean(y, 'omitnan');
end

%% ============================================================
% Funcion local para tabla de informacion

function fila = crear_fila_info(archivo, condicion, repeticion, muestras, Fs_mean_Hz, Fs_median_Hz, duracion_s)

    diferencia_mean_median_pct = abs(Fs_mean_Hz - Fs_median_Hz) / Fs_median_Hz * 100;

    fila = table( ...
        archivo, ...
        condicion, ...
        repeticion, ...
        muestras, ...
        Fs_mean_Hz, ...
        Fs_median_Hz, ...
        diferencia_mean_median_pct, ...
        duracion_s, ...
        'VariableNames', { ...
        'Archivo', ...
        'Condicion', ...
        'Repeticion', ...
        'Muestras', ...
        'Fs_mean_Hz', ...
        'Fs_median_Hz', ...
        'Diferencia_mean_median_pct', ...
        'Duracion_s'} );
end

%% ============================================================
% Funcion local para guardar tablas como figura compacta

function guardar_tabla_como_figura_compacta(T, titulo_figura, archivo_png, archivo_fig)

    if isempty(T)
        warning('La tabla esta vacia. No se generara figura: %s', titulo_figura);
        return;
    end

    T_cell = table2cell(T);
    nombres = T.Properties.VariableNames;

    datos_txt = cell(size(T_cell));

    for i = 1:size(T_cell,1)
        for j = 1:size(T_cell,2)

            valor = T_cell{i,j};
            nombre_col = nombres{j};

            if isnumeric(valor)

                if contains(nombre_col, 'rep', 'IgnoreCase', true)
                    datos_txt{i,j} = sprintf('%.0f', valor);

                elseif contains(nombre_col, 'kHz', 'IgnoreCase', true)
                    datos_txt{i,j} = sprintf('%.4f', valor);

                elseif contains(nombre_col, 'dB', 'IgnoreCase', true)
                    datos_txt{i,j} = sprintf('%.4f', valor);

                elseif strcmpi(nombre_col, 'NW')
                    datos_txt{i,j} = sprintf('%.2f', valor);

                else
                    datos_txt{i,j} = sprintf('%.4f', valor);
                end

            elseif islogical(valor)

                if valor
                    datos_txt{i,j} = 'Si';
                else
                    datos_txt{i,j} = 'No';
                end

            elseif isstring(valor)

                datos_txt{i,j} = char(valor);

            elseif ischar(valor)

                datos_txt{i,j} = valor;

            else

                datos_txt{i,j} = char(string(valor));
            end
        end
    end

    nfilas = size(datos_txt,1);
    ncols = size(datos_txt,2);

    %% Tamaño compacto

    margen_izq = 30;
    margen_der = 30;
    margen_sup = 18;
    margen_inf = 25;

    alto_titulo = 55;
    alto_header = 36;
    alto_fila = 34;

    ancho_col = zeros(1,ncols);

    for c = 1:ncols

        nombre_col = nombres{c};

        switch nombre_col

            case {'fc_ref_kHz','fc_local_kHz'}
                ancho_col(c) = 115;

            case {'score_local','ON_dB','OFF_dB'}
                ancho_col(c) = 115;

            case {'rep_0dB','rep_3dB','rep_totales'}
                ancho_col(c) = 105;

            case {'umbral_3dB','NW'}
                ancho_col(c) = 105;

            case {'repeticion'}
                ancho_col(c) = 95;

            case {'score_positivo_0dB','score_positivo_3dB'}
                ancho_col(c) = 155;

            otherwise
                ancho_col(c) = 120;
        end
    end

    ancho_tabla = sum(ancho_col);
    alto_tabla = alto_header + nfilas*alto_fila;

    ancho_fig = margen_izq + ancho_tabla + margen_der;
    alto_fig = margen_sup + alto_titulo + alto_tabla + margen_inf;

    fig = figure('Color','w', ...
        'Units','pixels', ...
        'Position',[80 80 ancho_fig alto_fig], ...
        'Name',titulo_figura, ...
        'NumberTitle','off');

    ax = axes('Parent',fig, ...
        'Units','pixels', ...
        'Position',[0 0 ancho_fig alto_fig]);

    axis(ax, [0 ancho_fig 0 alto_fig]);
    axis(ax, 'off');
    hold(ax, 'on');

    %% Titulo

    text(ax, ancho_fig/2, alto_fig - margen_sup - alto_titulo/2, titulo_figura, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontWeight','bold', ...
        'FontSize',22, ...
        'Interpreter','none');

    %% Tabla

    x0 = margen_izq;
    y0 = margen_inf + alto_tabla;

    color_header = [0.86 0.86 0.86];
    color_fila_1 = [1 1 1];
    color_fila_2 = [0.92 0.92 0.92];
    color_borde = [0.65 0.65 0.65];

    x = x0;

    for c = 1:ncols

        rectangle(ax, ...
            'Position',[x, y0 - alto_header, ancho_col(c), alto_header], ...
            'FaceColor',color_header, ...
            'EdgeColor',color_borde, ...
            'LineWidth',0.9);

        text(ax, x + ancho_col(c)/2, y0 - alto_header/2, nombres{c}, ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontWeight','bold', ...
            'FontSize',10, ...
            'Interpreter','none');

        x = x + ancho_col(c);
    end

    for r = 1:nfilas

        y = y0 - alto_header - r*alto_fila;

        if mod(r,2) == 0
            color_fila = color_fila_2;
        else
            color_fila = color_fila_1;
        end

        x = x0;

        for c = 1:ncols

            rectangle(ax, ...
                'Position',[x, y, ancho_col(c), alto_fila], ...
                'FaceColor',color_fila, ...
                'EdgeColor',[0.82 0.82 0.82], ...
                'LineWidth',0.7);

            text(ax, x + ancho_col(c)/2, y + alto_fila/2, datos_txt{r,c}, ...
                'HorizontalAlignment','center', ...
                'VerticalAlignment','middle', ...
                'FontSize',10, ...
                'Interpreter','none');

            x = x + ancho_col(c);
        end
    end

    drawnow;

    print(fig, archivo_png, '-dpng', '-r300');
    savefig(fig, archivo_fig);
end