%% LED2_04_comparativa_local_45kHz.m
%
% INSTRUCCIONES DE USO
% Antes de ejecutar este script, revisar la variable carpeta_base
% y modificarla si los resultados del LED 2 se encuentran en otra ruta local.
% La carpeta indicada debe contener las subcarpetas 01_Periodogram,
% 02_Welch y 03_Multitaper, con los archivos .mat generados previamente
% por los scripts de cada metodo.
%
% Ejemplo:
% carpeta_base = 'C:\Users\NombreUsuario\Desktop\Pruebas LED 2\Resultados_LED2_modificados';

clear; 
clc; 
close all;

%% 1. Carpetas

carpeta_base = 'C:\Users\mudrood\Desktop\Modulo Prof\Archivos Tesis\Toma de Datos\Pruebas LED 2\Resultados_LED2_modificados';

carpeta_periodograma = fullfile(carpeta_base, '01_Periodogram');
carpeta_welch        = fullfile(carpeta_base, '02_Welch');
carpeta_mt           = fullfile(carpeta_base, '03_Multitaper');

carpeta_salida = fullfile(carpeta_base, '04_Comparativa');

if ~exist(carpeta_salida, 'dir')
    mkdir(carpeta_salida);
end

%% 2. Parametros generales

fc_ref_Hz  = 45375;
fc_ref_kHz = fc_ref_Hz / 1e3;

ancho_local_Hz = 2500;

fmin_local = fc_ref_Hz - ancho_local_Hz;
fmax_local = fc_ref_Hz + ancho_local_Hz;

criterio_dB = 3;

c_per = [0.0000 0.4470 0.7410]; 
c_wel = [0.8500 0.3250 0.0980];  
c_mt  = [0.9290 0.6940 0.1250];  

c_ref  = [0.20 0.20 0.20];
c_prom = [0.35 0.35 0.35];
c_crit = [0.45 0.45 0.45];

fprintf('\n============================================\n');
fprintf('COMPARATIVA LOCAL LED 2\n');
fprintf('============================================\n');
fprintf('Carpeta base:\n%s\n', carpeta_base);
fprintf('\nFrecuencia referencia = %.3f Hz = %.3f kHz\n', fc_ref_Hz, fc_ref_kHz);
fprintf('Rango comparativo = %.3f a %.3f kHz\n', fmin_local/1e3, fmax_local/1e3);

%% 3. Buscar archivos .mat

archivo_periodograma = buscar_archivo_mat(carpeta_periodograma, { ...
    'datos_periodogram_LED2_graficas_v2.mat', ...
    'datos_periodograma_LED2_graficas_v2.mat', ...
    'datos_periodogram_LED2*.mat', ...
    'datos_periodograma_LED2*.mat', ...
    '*periodogram*LED2*.mat', ...
    '*periodograma*LED2*.mat'});

archivo_welch = buscar_archivo_mat(carpeta_welch, { ...
    'datos_welch_LED2_graficas_v2.mat', ...
    'datos_welch_LED2*.mat', ...
    '*welch*LED2*.mat'});

archivo_mt = buscar_archivo_mat(carpeta_mt, { ...
    'datos_MT_LED2_V2_local_45kHz.mat', ...
    'datos_MT_LED2_V2_local*.mat', ...
    '*MT*LED2*local*.mat', ...
    '*multitaper*LED2*local*.mat'});

fprintf('\nArchivo Periodograma:\n%s\n', archivo_periodograma);
fprintf('\nArchivo Welch:\n%s\n', archivo_welch);
fprintf('\nArchivo Multitaper:\n%s\n', archivo_mt);

%% 4. Cargar datos

Sper = load(archivo_periodograma);
Swel = load(archivo_welch);
Smt  = load(archivo_mt);

%% 5. Extraer curvas de score

[f_per, score_per] = extraer_curva_score(Sper, 'Periodograma');
[f_wel, score_wel] = extraer_curva_score(Swel, 'Welch');
[f_mt,  score_mt]  = extraer_curva_score(Smt,  'Multitaper local');

f_per = normalizar_frecuencia_Hz(f_per(:));
f_wel = normalizar_frecuencia_Hz(f_wel(:));
f_mt  = normalizar_frecuencia_Hz(f_mt(:));

score_per = score_per(:);
score_wel = score_wel(:);
score_mt  = score_mt(:);

%% 6. Extraer resumen de cada metodo

res_per = extraer_resumen_metodo(Sper, 'Periodograma');
res_wel = extraer_resumen_metodo(Swel, 'Welch');
res_mt  = extraer_resumen_metodo(Smt,  'Multitaper local');

%% 7. Tabla resumen comparativa

tabla_resumen = table( ...
    ["Periodograma"; "Welch"; "Multitaper local"], ...
    [res_per.fc_kHz; res_wel.fc_kHz; res_mt.fc_kHz], ...
    [res_per.score_dB; res_wel.score_dB; res_mt.score_dB], ...
    [res_per.ON_dB; res_wel.ON_dB; res_mt.ON_dB], ...
    [res_per.OFF_dB; res_wel.OFF_dB; res_mt.OFF_dB], ...
    [res_per.rep_0dB; res_wel.rep_0dB; res_mt.rep_0dB], ...
    [res_per.rep_3dB; res_wel.rep_3dB; res_mt.rep_3dB], ...
    [res_per.rep_total; res_wel.rep_total; res_mt.rep_total], ...
    strings(3,1), ...
    abs([res_per.fc_kHz; res_wel.fc_kHz; res_mt.fc_kHz] - fc_ref_kHz), ...
    abs([res_per.fc_kHz; res_wel.fc_kHz; res_mt.fc_kHz] - fc_ref_kHz)/fc_ref_kHz*100, ...
    'VariableNames', { ...
    'Metodo', ...
    'fc_kHz', ...
    'score_max', ...
    'ON_dB', ...
    'OFF_dB', ...
    'rep_0dB', ...
    'rep_3dB', ...
    'rep_total', ...
    'supera_3dB', ...
    'err_ref_kHz', ...
    'err_ref_pct'});

for i = 1:height(tabla_resumen)
    if tabla_resumen.score_max(i) >= criterio_dB
        tabla_resumen.supera_3dB(i) = "Si";
    else
        tabla_resumen.supera_3dB(i) = "No";
    end
end

idx_validados = tabla_resumen.score_max >= criterio_dB;

fc_promedio_kHz = mean(tabla_resumen.fc_kHz, 'omitnan');

if any(idx_validados)
    fc_promedio_validado_kHz = mean(tabla_resumen.fc_kHz(idx_validados), 'omitnan');
else
    fc_promedio_validado_kHz = NaN;
end

if ~isnan(fc_promedio_validado_kHz)
    fc_texto_prom_kHz = fc_promedio_validado_kHz;
else
    fc_texto_prom_kHz = fc_promedio_kHz;
end

tabla_parametros = table( ...
    fc_ref_kHz, ...
    ancho_local_Hz/1e3, ...
    fmin_local/1e3, ...
    fmax_local/1e3, ...
    fc_promedio_kHz, ...
    fc_promedio_validado_kHz, ...
    criterio_dB, ...
    sum(idx_validados), ...
    height(tabla_resumen), ...
    'VariableNames', { ...
    'fc_ref_kHz', ...
    'ancho_kHz', ...
    'fmin_local_kHz', ...
    'fmax_local_kHz', ...
    'fc_prom_gen_kHz', ...
    'fc_prom_val_kHz', ...
    'criterio_dB', ...
    'met_val', ...
    'met_total'});

fprintf('\n============================================\n');
fprintf('TABLA RESUMEN COMPARATIVA LED 2\n');
fprintf('============================================\n');
disp(tabla_resumen);

fprintf('\n============================================\n');
fprintf('PARAMETROS COMPARATIVA LED 2\n');
fprintf('============================================\n');
disp(tabla_parametros);

%% 7.b Tablas auxiliares para figuras

tabla_resumen_fig = tabla_resumen;
tabla_resumen_fig.Properties.VariableNames = { ...
    'Metodo', ...
    'fc_kHz', ...
    'score_max', ...
    'ON_dB', ...
    'OFF_dB', ...
    'rep_0dB', ...
    'rep_3dB', ...
    'rep_total', ...
    'sup_3dB', ...
    'err_kHz', ...
    'err_pct'};

tabla_parametros_fig = tabla_parametros;
tabla_parametros_fig.Properties.VariableNames = { ...
    'fc_ref_kHz', ...
    'ancho_kHz', ...
    'fmin_kHz', ...
    'fmax_kHz', ...
    'fc_prom_kHz', ...
    'fc_val_kHz', ...
    'crit_dB', ...
    'met_val', ...
    'met_total'};

%% 8. Guardar tablas CSV

writetable(tabla_resumen, fullfile(carpeta_salida, 'tabla_comparativa_LED2_resumen.csv'));
writetable(tabla_parametros, fullfile(carpeta_salida, 'tabla_comparativa_LED2_parametros.csv'));

%% 9. Recortar curvas al rango local

idx_per = f_per >= fmin_local & f_per <= fmax_local;
idx_wel = f_wel >= fmin_local & f_wel <= fmax_local;
idx_mt  = f_mt  >= fmin_local & f_mt  <= fmax_local;

f_per_l = f_per(idx_per);
s_per_l = score_per(idx_per);

f_wel_l = f_wel(idx_wel);
s_wel_l = score_wel(idx_wel);

f_mt_l = f_mt(idx_mt);
s_mt_l = score_mt(idx_mt);

if isempty(f_per_l)
    error('Curva local Periodograma vacia. Revisar unidades de frecuencia.');
end

if isempty(f_wel_l)
    error('Curva local Welch vacia. Revisar unidades de frecuencia.');
end

if isempty(f_mt_l)
    error('Curva local Multitaper vacia. Revisar unidades de frecuencia.');
end

%% 10. Tabla parametros como figura

guardar_tabla_como_figura_ajustada( ...
    tabla_parametros_fig, ...
    'PARAMETROS COMPARATIVA LOCAL LED 2', ...
    fullfile(carpeta_salida, 'tabla_comparativa_LED2_parametros.png'), ...
    fullfile(carpeta_salida, 'tabla_comparativa_LED2_parametros.fig'));

%% 11. Tabla resumen como figura

guardar_tabla_como_figura_ajustada( ...
    tabla_resumen_fig, ...
    'TABLA RESUMEN COMPARATIVA LED 2', ...
    fullfile(carpeta_salida, 'tabla_comparativa_LED2_resumen.png'), ...
    fullfile(carpeta_salida, 'tabla_comparativa_LED2_resumen.fig'));

%% 12. Grafico 2D: comparativa local de score

fig = figure('Color','w','Position',[100 100 1350 760]);
hold on;

plot(f_per_l/1e3, s_per_l, ...
    'Color', c_per, ...
    'LineWidth', 1.0, ...
    'DisplayName','Periodograma');

plot(f_wel_l/1e3, s_wel_l, ...
    'Color', c_wel, ...
    'LineWidth', 1.0, ...
    'DisplayName','Welch');

plot(f_mt_l/1e3, s_mt_l, ...
    'Color', c_mt, ...
    'LineWidth', 1.2, ...
    'DisplayName','Multitaper local');

plot(res_per.fc_kHz, res_per.score_dB, 'o', ...
    'Color','k', ...
    'MarkerFaceColor','w', ...
    'MarkerSize',8, ...
    'LineWidth',1.8, ...
    'DisplayName','Max. Periodograma');

plot(res_wel.fc_kHz, res_wel.score_dB, 's', ...
    'Color','k', ...
    'MarkerFaceColor','w', ...
    'MarkerSize',8, ...
    'LineWidth',1.8, ...
    'DisplayName','Max. Welch');

plot(res_mt.fc_kHz, res_mt.score_dB, '*', ...
    'Color','k', ...
    'MarkerSize',10, ...
    'LineWidth',1.8, ...
    'DisplayName','Max. Multitaper');

xline(fc_ref_kHz, '--', ...
    'Color', c_ref, ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xline(fc_texto_prom_kHz, ':', ...
    'Color', c_prom, ...
    'LineWidth',1.4, ...
    'HandleVisibility','off');

yline(0, '--', ...
    'Color', c_crit, ...
    'LineWidth',1.0, ...
    'HandleVisibility','off');

yline(criterio_dB, '--', ...
    'Color', c_crit, ...
    'LineWidth',1.1, ...
    'HandleVisibility','off');

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');
title('LED 2 - Comparativa local de score ON-OFF entre metodos', ...
    'Interpreter','none');

xlim([fmin_local fmax_local]/1e3);

yl = ylim;
dy = yl(2) - yl(1);
xl = xlim;
dx = xl(2) - xl(1);

text(fc_texto_prom_kHz - 0.03, yl(2) - 0.07*dy, ...
    sprintf('PROM.\n%.3f kHz', fc_texto_prom_kHz), ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontWeight','bold', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',1);

text(fc_ref_kHz + 0.18, yl(2) - 0.05*dy, ...
    sprintf('REF.\n%.3f kHz', fc_ref_kHz), ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontWeight','bold', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',1);

text(xl(2)-0.02*dx, criterio_dB+0.15, ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',1);

text(xl(2)-0.02*dx, 0+0.15, ...
    '0 dB', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',1);

text(res_per.fc_kHz - 0.07, res_per.score_dB - 1.1, ...
    sprintf('%.3f kHz\n%.2f dB', res_per.fc_kHz, res_per.score_dB), ...
    'HorizontalAlignment','right', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(res_wel.fc_kHz - 0.05, res_wel.score_dB + 0.7, ...
    sprintf('%.3f kHz\n%.2f dB', res_wel.fc_kHz, res_wel.score_dB), ...
    'HorizontalAlignment','right', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(res_mt.fc_kHz - 0.05, res_mt.score_dB + 0.8, ...
    sprintf('%.3f kHz\n%.2f dB', res_mt.fc_kHz, res_mt.score_dB), ...
    'HorizontalAlignment','right', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

legend('Location','northeastoutside');

saveas(fig, fullfile(carpeta_salida, 'Comparativa_LED2_score_local_2D.png'));
savefig(fig, fullfile(carpeta_salida, 'Comparativa_LED2_score_local_2D.fig'));

%% 13. Grafico de barras: maximos por metodo

fig = figure('Color','w','Position',[100 100 1200 680]);
hold on;

score_met = tabla_resumen.score_max;
fc_met = tabla_resumen.fc_kHz;

b = bar(1:height(tabla_resumen), score_met, 0.70, ...
    'FaceColor','flat', ...
    'EdgeColor','k');

b.CData = [
    c_per
    c_wel
    c_mt
];

yline(criterio_dB, '--', ...
    'Color', c_crit, ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

grid on;
box on;

xticks(1:height(tabla_resumen));
xticklabels(tabla_resumen.Metodo);

xlabel('Metodo');
ylabel('Score maximo local ON-OFF [dB]');
title('LED 2 - Maximos locales de score ON-OFF por metodo', ...
    'Interpreter','none');

ylim([0, max(score_met) + 2.2]);

xl = xlim;

text(xl(2)-0.05, criterio_dB + 0.20, ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',10, ...
    'BackgroundColor','w', ...
    'Margin',1);

for i = 1:height(tabla_resumen)
    text(i, score_met(i)+0.35, ...
        sprintf('%.3f kHz\n%.2f dB', fc_met(i), score_met(i)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',10);
end

saveas(fig, fullfile(carpeta_salida, 'Comparativa_LED2_barras_maximos.png'));
savefig(fig, fullfile(carpeta_salida, 'Comparativa_LED2_barras_maximos.fig'));

%% 14. Grafico tipo cascada 2D desplazado

offset_per = 0;
offset_wel = 25;
offset_mt  = 50;

fig = figure('Color','w','Position',[100 100 1400 760]);
hold on;

plot(f_per_l/1e3, s_per_l + offset_per, ...
    'Color', c_per, ...
    'LineWidth', 1.0, ...
    'DisplayName','Periodograma');

plot(f_wel_l/1e3, s_wel_l + offset_wel, ...
    'Color', c_wel, ...
    'LineWidth', 1.0, ...
    'DisplayName','Welch');

plot(f_mt_l/1e3, s_mt_l + offset_mt, ...
    'Color', c_mt, ...
    'LineWidth', 1.1, ...
    'DisplayName','Multitaper local');

yline(offset_per, ':', ...
    'Color',[0.60 0.60 0.60], ...
    'HandleVisibility','off');

yline(offset_wel, ':', ...
    'Color',[0.60 0.60 0.60], ...
    'HandleVisibility','off');

yline(offset_mt, ':', ...
    'Color',[0.60 0.60 0.60], ...
    'HandleVisibility','off');

yline(offset_per + criterio_dB, '--', ...
    'Color',[0.55 0.55 0.55], ...
    'HandleVisibility','off');

yline(offset_wel + criterio_dB, '--', ...
    'Color',[0.55 0.55 0.55], ...
    'HandleVisibility','off');

yline(offset_mt + criterio_dB, '--', ...
    'Color',[0.55 0.55 0.55], ...
    'HandleVisibility','off');

plot(res_per.fc_kHz, res_per.score_dB + offset_per, 'o', ...
    'Color','k', ...
    'MarkerFaceColor','w', ...
    'MarkerSize',8, ...
    'LineWidth',1.8, ...
    'DisplayName','Maximo Periodograma');

plot(res_wel.fc_kHz, res_wel.score_dB + offset_wel, 's', ...
    'Color','k', ...
    'MarkerFaceColor','w', ...
    'MarkerSize',8, ...
    'LineWidth',1.8, ...
    'DisplayName','Maximo Welch');

plot(res_mt.fc_kHz, res_mt.score_dB + offset_mt, '*', ...
    'Color','k', ...
    'MarkerSize',10, ...
    'LineWidth',1.8, ...
    'DisplayName','Maximo Multitaper');

xline(fc_ref_kHz, '--', ...
    'Color', c_ref, ...
    'LineWidth',1.2, ...
    'HandleVisibility','off');

xline(fc_texto_prom_kHz, ':', ...
    'Color', c_prom, ...
    'LineWidth',1.3, ...
    'HandleVisibility','off');

text(res_per.fc_kHz + 0.04, res_per.score_dB + offset_per + 1.0, ...
    sprintf('%.3f kHz\n%.2f dB', res_per.fc_kHz, res_per.score_dB), ...
    'HorizontalAlignment','left', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(res_wel.fc_kHz - 0.05, res_wel.score_dB + offset_wel + 1.0, ...
    sprintf('%.3f kHz\n%.2f dB', res_wel.fc_kHz, res_wel.score_dB), ...
    'HorizontalAlignment','right', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(res_mt.fc_kHz - 0.08, res_mt.score_dB + 50 + 0.45, ...
    sprintf('%.3f kHz\n%.2f dB', res_mt.fc_kHz, res_mt.score_dB), ...
    'HorizontalAlignment','right', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

x_text = fmin_local/1e3 + 0.08;

text(x_text, offset_per + 1.5, 'Periodograma', ...
    'FontWeight','bold', ...
    'FontSize',10, ...
    'Color', 'k', ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(x_text, offset_wel + 1.5, 'Welch', ...
    'FontWeight','bold', ...
    'FontSize',10, ...
    'Color', 'k', ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(x_text, offset_mt + 1.5, 'Multitaper local', ...
    'FontWeight','bold', ...
    'FontSize',10, ...
    'Color', 'k', ...
    'BackgroundColor','w', ...
    'Margin',0.5);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('Score ON-OFF desplazado [dB]');
title('LED 2 - Comparativa tipo cascada de score ON-OFF entre metodos', ...
    'Interpreter','none');

xlim([fmin_local fmax_local]/1e3);

ylim([
    min(s_per_l) - 4, ...
    offset_mt + max(s_mt_l) + 8
]);

yl = ylim;
dy = yl(2) - yl(1);

text(fc_texto_prom_kHz - 0.035, yl(2) - 0.025*dy, ...
    sprintf('PROM.\n%.3f kHz', fc_texto_prom_kHz), ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'FontWeight','bold', ...
    'FontSize',8.5, ...
    'BackgroundColor','w', ...
    'Margin',0.3);

text(fc_ref_kHz + 0.08, yl(2) - 0.025*dy, ...
    sprintf('REF.\n%.3f kHz', fc_ref_kHz), ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'FontWeight','bold', ...
    'FontSize',8.5, ...
    'BackgroundColor','w', ...
    'Margin',1);

legend('Location','eastoutside');

saveas(fig, fullfile(carpeta_salida, 'Comparativa_LED2_score_cascada_2D.png'));
savefig(fig, fullfile(carpeta_salida, 'Comparativa_LED2_score_cascada_2D.fig'));

%% 15. Grafico 3D: comparativa por metodo

fig = figure('Color','w','Position',[100 100 1400 760]);
hold on;

y_per = ones(size(f_per_l)) * 1;
y_wel = ones(size(f_wel_l)) * 2;
y_mt  = ones(size(f_mt_l))  * 3;

plot3(f_per_l/1e3, y_per, s_per_l, ...
    'Color', c_per, ...
    'LineWidth', 1.0, ...
    'DisplayName','Periodograma');

plot3(f_wel_l/1e3, y_wel, s_wel_l, ...
    'Color', c_wel, ...
    'LineWidth', 1.0, ...
    'DisplayName','Welch');

plot3(f_mt_l/1e3, y_mt, s_mt_l, ...
    'Color', c_mt, ...
    'LineWidth', 1.3, ...
    'DisplayName','Multitaper local');

plot3(res_per.fc_kHz, 1, res_per.score_dB, 'o', ...
    'Color','k', ...
    'MarkerFaceColor','w', ...
    'MarkerSize',8, ...
    'LineWidth',1.8, ...
    'DisplayName','Maximo Periodograma');

plot3(res_wel.fc_kHz, 2, res_wel.score_dB, 's', ...
    'Color','k', ...
    'MarkerFaceColor','w', ...
    'MarkerSize',8, ...
    'LineWidth',1.8, ...
    'DisplayName','Maximo Welch');

plot3(res_mt.fc_kHz, 3, res_mt.score_dB, '*', ...
    'Color','k', ...
    'MarkerSize',10, ...
    'LineWidth',1.8, ...
    'DisplayName','Maximo Multitaper');

text(res_per.fc_kHz, 1, res_per.score_dB + 1.0, ...
    sprintf('%.3f kHz\n%.2f dB', res_per.fc_kHz, res_per.score_dB), ...
    'HorizontalAlignment','center', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(res_wel.fc_kHz, 2, res_wel.score_dB + 1.0, ...
    sprintf('%.3f kHz\n%.2f dB', res_wel.fc_kHz, res_wel.score_dB), ...
    'HorizontalAlignment','center', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(res_mt.fc_kHz, 3, res_mt.score_dB + 1.0, ...
    sprintf('%.3f kHz\n%.2f dB', res_mt.fc_kHz, res_mt.score_dB), ...
    'HorizontalAlignment','center', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

[Xp, Yp] = meshgrid([fmin_local fmax_local]/1e3, [0.8 3.2]);
Zp = criterio_dB * ones(size(Xp));

surf(Xp, Yp, Zp, ...
    'FaceColor',[0.75 0.95 0.95], ...
    'FaceAlpha',0.16, ...
    'EdgeColor','none', ...
    'DisplayName','Plano criterio 3 dB');

for yy = 1:3
    plot3([fc_ref_kHz fc_ref_kHz], [yy yy], [-15 20], '--', ...
        'Color', c_ref, ...
        'LineWidth',1.0, ...
        'HandleVisibility','off');

    plot3([fc_texto_prom_kHz fc_texto_prom_kHz], [yy yy], [-15 20], ':', ...
        'Color', c_prom, ...
        'LineWidth',1.0, ...
        'HandleVisibility','off');
end

plot3([fc_ref_kHz fc_ref_kHz], [1 3], [0 0], '--', ...
    'Color', c_ref, ...
    'LineWidth',1.3, ...
    'DisplayName',sprintf('Referencia %.3f kHz', fc_ref_kHz));

plot3([fc_texto_prom_kHz fc_texto_prom_kHz], [1 3], [0 0], ':', ...
    'Color', c_prom, ...
    'LineWidth',1.3, ...
    'DisplayName',sprintf('Promedio %.3f kHz', fc_texto_prom_kHz));

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('Metodo');
zlabel('Score ON-OFF [dB]');
title('LED 2 - Comparativa 3D de score ON-OFF', ...
    'Interpreter','none');

yticks([1 2 3]);
yticklabels({'Periodograma','Welch','Multitaper local'});

xlim([fmin_local fmax_local]/1e3);
ylim([0.8 3.2]);
zlim([-15 20]);

view(45, 24);
legend('Location','northeastoutside');

saveas(fig, fullfile(carpeta_salida, 'Comparativa_LED2_score_3D.png'));
savefig(fig, fullfile(carpeta_salida, 'Comparativa_LED2_score_3D.fig'));

%% 16. Grafico 3D tipo cascada con planos suaves

fig = figure('Color','w','Position',[100 100 1400 760]);
hold on;

plot3(f_per_l/1e3, y_per, s_per_l, ...
    'Color', c_per, ...
    'LineWidth', 1.0, ...
    'DisplayName','Periodograma');

plot3(f_wel_l/1e3, y_wel, s_wel_l, ...
    'Color', c_wel, ...
    'LineWidth', 1.0, ...
    'DisplayName','Welch');

plot3(f_mt_l/1e3, y_mt, s_mt_l, ...
    'Color', c_mt, ...
    'LineWidth', 1.3, ...
    'DisplayName','Multitaper local');

agregar_plano_metodo(fmin_local/1e3, fmax_local/1e3, 1, -15, 20, c_per);
agregar_plano_metodo(fmin_local/1e3, fmax_local/1e3, 2, -15, 20, c_wel);
agregar_plano_metodo(fmin_local/1e3, fmax_local/1e3, 3, -15, 20, c_mt);

surf(Xp, Yp, Zp, ...
    'FaceColor',[0.75 0.95 0.95], ...
    'FaceAlpha',0.13, ...
    'EdgeColor','none', ...
    'DisplayName','Criterio 3 dB');

plot3(res_per.fc_kHz, 1, res_per.score_dB, 'o', ...
    'Color','k', ...
    'MarkerFaceColor','w', ...
    'MarkerSize',8, ...
    'LineWidth',1.8, ...
    'DisplayName','Maximo Periodograma');

plot3(res_wel.fc_kHz, 2, res_wel.score_dB, 's', ...
    'Color','k', ...
    'MarkerFaceColor','w', ...
    'MarkerSize',8, ...
    'LineWidth',1.8, ...
    'DisplayName','Maximo Welch');

plot3(res_mt.fc_kHz, 3, res_mt.score_dB, '*', ...
    'Color','k', ...
    'MarkerSize',10, ...
    'LineWidth',1.8, ...
    'DisplayName','Maximo Multitaper');

text(res_per.fc_kHz, 1, res_per.score_dB + 1.0, ...
    sprintf('%.3f kHz\n%.2f dB', res_per.fc_kHz, res_per.score_dB), ...
    'HorizontalAlignment','center', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(res_wel.fc_kHz, 2, res_wel.score_dB + 1.0, ...
    sprintf('%.3f kHz\n%.2f dB', res_wel.fc_kHz, res_wel.score_dB), ...
    'HorizontalAlignment','center', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

text(res_mt.fc_kHz, 3, res_mt.score_dB + 1.0, ...
    sprintf('%.3f kHz\n%.2f dB', res_mt.fc_kHz, res_mt.score_dB), ...
    'HorizontalAlignment','center', ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'Margin',0.5);

for yy = 1:3
    plot3([fc_ref_kHz fc_ref_kHz], [yy yy], [-15 20], '--', ...
        'Color', c_ref, ...
        'LineWidth',1.0, ...
        'HandleVisibility','off');

    plot3([fc_texto_prom_kHz fc_texto_prom_kHz], [yy yy], [-15 20], ':', ...
        'Color', c_prom, ...
        'LineWidth',1.0, ...
        'HandleVisibility','off');
end

plot3([fc_ref_kHz fc_ref_kHz], [1 3], [0 0], '--', ...
    'Color', c_ref, ...
    'LineWidth',1.3, ...
    'DisplayName',sprintf('Referencia %.3f kHz', fc_ref_kHz));

plot3([fc_texto_prom_kHz fc_texto_prom_kHz], [1 3], [0 0], ':', ...
    'Color', c_prom, ...
    'LineWidth',1.3, ...
    'DisplayName',sprintf('Promedio %.3f kHz', fc_texto_prom_kHz));

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('Metodo');
zlabel('Score ON-OFF [dB]');
title('LED 2 - Comparativa 3D tipo cascada de score ON-OFF', ...
    'Interpreter','none');

yticks([1 2 3]);
yticklabels({'Periodograma','Welch','Multitaper local'});

xlim([fmin_local fmax_local]/1e3);
ylim([0.8 3.2]);
zlim([-15 20]);

view(45, 24);
legend('Location','northeastoutside');

saveas(fig, fullfile(carpeta_salida, 'Comparativa_LED2_score_3D_cascada.png'));
savefig(fig, fullfile(carpeta_salida, 'Comparativa_LED2_score_3D_cascada.fig'));

%% 17. Guardar variables

save(fullfile(carpeta_salida, 'datos_comparativa_LED2_local_45kHz.mat'), ...
    'tabla_resumen', ...
    'tabla_parametros', ...
    'tabla_resumen_fig', ...
    'tabla_parametros_fig', ...
    'fc_ref_Hz', ...
    'fc_ref_kHz', ...
    'fc_promedio_kHz', ...
    'fc_promedio_validado_kHz', ...
    'fc_texto_prom_kHz', ...
    'fmin_local', ...
    'fmax_local', ...
    'ancho_local_Hz', ...
    'criterio_dB', ...
    'f_per_l', ...
    's_per_l', ...
    'f_wel_l', ...
    's_wel_l', ...
    'f_mt_l', ...
    's_mt_l', ...
    'res_per', ...
    'res_wel', ...
    'res_mt');

fprintf('\n============================================\n');
fprintf('Comparativa LED 2 terminada.\n');
fprintf('Resultados guardados en:\n%s\n', carpeta_salida);
fprintf('============================================\n');

%% ============================================================
% FUNCIONES LOCALES

function archivo = buscar_archivo_mat(carpeta, patrones)

    if ~exist(carpeta, 'dir')
        error('No existe la carpeta: %s', carpeta);
    end

    archivo = '';

    for i = 1:numel(patrones)
        D = dir(fullfile(carpeta, patrones{i}));

        if ~isempty(D)
            archivo = fullfile(D(1).folder, D(1).name);
            return;
        end
    end

    D = dir(fullfile(carpeta, '*.mat'));

    if isempty(D)
        error('No se encontro ningun archivo .mat en la carpeta: %s', carpeta);
    end

    fprintf('\nArchivos .mat encontrados en %s:\n', carpeta);
    for k = 1:numel(D)
        fprintf('  %d) %s\n', k, D(k).name);
    end

    error('No se encontro ningun archivo esperado en la carpeta: %s', carpeta);
end

function [f, score] = extraer_curva_score(S, nombre_metodo)

    if isfield(S, 'f')
        f = S.f;
    elseif isfield(S, 'f_Hz')
        f = S.f_Hz;
    elseif isfield(S, 'freq')
        f = S.freq;
    else
        error('No se encontro variable de frecuencia en %s.', nombre_metodo);
    end

    if isfield(S, 'score_prom_dB')
        score = S.score_prom_dB;
    elseif isfield(S, 'score_prom')
        score = S.score_prom;
    elseif isfield(S, 'score_local')
        score = S.score_local;
    elseif isfield(S, 'score_local_dB')
        score = S.score_local_dB;
    elseif isfield(S, 'P_ON_prom_dB') && isfield(S, 'P_OFF_prom_dB')
        score = S.P_ON_prom_dB - S.P_OFF_prom_dB;
    elseif isfield(S, 'P_ON_prom') && isfield(S, 'P_OFF_prom')
        score = S.P_ON_prom - S.P_OFF_prom;
    elseif isfield(S, 'Pxx_ON_prom_dB') && isfield(S, 'Pxx_OFF_prom_dB')
        score = S.Pxx_ON_prom_dB - S.Pxx_OFF_prom_dB;
    else
        error('No se encontro curva de score valida en %s.', nombre_metodo);
    end

    f = f(:);
    score = score(:);

    if numel(f) ~= numel(score)
        error('f y score tienen distinto largo en %s.', nombre_metodo);
    end
end

function f_Hz = normalizar_frecuencia_Hz(f)

    f = f(:);

    if max(f, [], 'omitnan') < 1000
        f_Hz = f * 1e3;
    else
        f_Hz = f;
    end
end

function res = extraer_resumen_metodo(S, nombre_metodo)

    res = struct();
    res.fc_Hz = NaN;
    res.fc_kHz = NaN;
    res.score_dB = NaN;
    res.ON_dB = NaN;
    res.OFF_dB = NaN;
    res.rep_0dB = NaN;
    res.rep_3dB = NaN;
    res.rep_total = NaN;

    if isfield(S, 'tabla_candidatos') && istable(S.tabla_candidatos) && height(S.tabla_candidatos) >= 1
        T = S.tabla_candidatos;
    elseif isfield(S, 'tabla') && istable(S.tabla) && height(S.tabla) >= 1
        T = S.tabla;
    elseif isfield(S, 'tabla_resumen') && istable(S.tabla_resumen) && height(S.tabla_resumen) >= 1
        T = S.tabla_resumen;
    else
        error('No se encontro tabla valida en %s.', nombre_metodo);
    end

    vars = T.Properties.VariableNames;

    if ismember('fc_Hz', vars)
        res.fc_Hz = tomar_valor(T.fc_Hz, 1);
    elseif ismember('f_local_Hz', vars)
        res.fc_Hz = tomar_valor(T.f_local_Hz, 1);
    elseif ismember('fc_local_Hz', vars)
        res.fc_Hz = tomar_valor(T.fc_local_Hz, 1);
    end

    if ismember('fc_kHz', vars)
        res.fc_kHz = tomar_valor(T.fc_kHz, 1);
    elseif ismember('f_local_kHz', vars)
        res.fc_kHz = tomar_valor(T.f_local_kHz, 1);
    elseif ismember('fc_local_kHz', vars)
        res.fc_kHz = tomar_valor(T.fc_local_kHz, 1);
    elseif ~isnan(res.fc_Hz)
        res.fc_kHz = res.fc_Hz / 1e3;
    end

    if isnan(res.fc_Hz) && ~isnan(res.fc_kHz)
        res.fc_Hz = res.fc_kHz * 1e3;
    end

    if ismember('score_local_dB', vars)
        res.score_dB = tomar_valor(T.score_local_dB, 1);
    elseif ismember('score_peak_dB', vars)
        res.score_dB = tomar_valor(T.score_peak_dB, 1);
    elseif ismember('score_max_dB', vars)
        res.score_dB = tomar_valor(T.score_max_dB, 1);
    elseif ismember('score_max', vars)
        res.score_dB = tomar_valor(T.score_max, 1);
    end

    if ismember('ON_dB', vars)
        res.ON_dB = tomar_valor(T.ON_dB, 1);
    end

    if ismember('OFF_dB', vars)
        res.OFF_dB = tomar_valor(T.OFF_dB, 1);
    end

    if ismember('rep_positivas_0dB', vars)
        res.rep_0dB = tomar_valor(T.rep_positivas_0dB, 1);
    elseif ismember('rep_0dB', vars)
        res.rep_0dB = tomar_valor(T.rep_0dB, 1);
    elseif ismember('rep_positivas', vars)
        res.rep_0dB = tomar_valor(T.rep_positivas, 1);
    end

    if ismember('rep_positivas_3dB', vars)
        res.rep_3dB = tomar_valor(T.rep_positivas_3dB, 1);
    elseif ismember('rep_3dB', vars)
        res.rep_3dB = tomar_valor(T.rep_3dB, 1);
    elseif ismember('rep_positivas', vars)
        res.rep_3dB = tomar_valor(T.rep_positivas, 1);
    end

    if ismember('rep_totales', vars)
        res.rep_total = tomar_valor(T.rep_totales, 1);
    elseif ismember('rep_total', vars)
        res.rep_total = tomar_valor(T.rep_total, 1);
    end

    fprintf('\nResumen %s:\n', nombre_metodo);
    fprintf('fc = %.3f Hz = %.4f kHz\n', res.fc_Hz, res.fc_kHz);
    fprintf('score = %.4f dB\n', res.score_dB);
end

function valor = tomar_valor(columna, idx)

    if iscell(columna)
        valor = columna{idx};
    else
        valor = columna(idx);
    end

    if isstring(valor)
        valor = str2double(valor);
    elseif ischar(valor)
        valor = str2double(valor);
    elseif islogical(valor)
        valor = double(valor);
    end

    if isempty(valor)
        valor = NaN;
    end
end

function guardar_tabla_como_figura_ajustada(T, titulo_figura, archivo_png, archivo_fig)

    if isempty(T)
        warning('La tabla esta vacia. No se generara figura: %s', titulo_figura);
        return;
    end

    nombres = T.Properties.VariableNames;
    nFilas = height(T);
    nCols = width(T);

    datos_txt = cell(nFilas, nCols);

    for r = 1:nFilas
        for c = 1:nCols

            valor = T{r,c};
            nombre_col = nombres{c};

            if iscell(valor)
                valor = valor{1};
            end

            nombre_col_lower = lower(nombre_col);

            if isnumeric(valor)
                if contains(nombre_col_lower, 'rep') || contains(nombre_col_lower, 'met_')
                    datos_txt{r,c} = sprintf('%d', round(valor));
                elseif contains(nombre_col_lower, 'pct')
                    datos_txt{r,c} = sprintf('%.2f', valor);
                elseif contains(nombre_col_lower, 'khz')
                    datos_txt{r,c} = sprintf('%.4f', valor);
                elseif contains(nombre_col_lower, 'db') || contains(nombre_col_lower, 'score')
                    datos_txt{r,c} = sprintf('%.4f', valor);
                else
                    datos_txt{r,c} = sprintf('%.4f', valor);
                end

            elseif isstring(valor)
                datos_txt{r,c} = char(valor);

            elseif ischar(valor)
                datos_txt{r,c} = valor;

            elseif islogical(valor)
                if valor
                    datos_txt{r,c} = 'Si';
                else
                    datos_txt{r,c} = 'No';
                end

            else
                datos_txt{r,c} = char(string(valor));
            end
        end
    end

    %% Tamano de figura

    alto_titulo = 75;
    alto_header = 52;
    alto_fila   = 52;
    margen_inf  = 30;
    margen_sup  = 22;

    alto_fig = alto_titulo + alto_header + nFilas*alto_fila + margen_inf + margen_sup;

    ancho_col = zeros(1,nCols);

    for c = 1:nCols
        nombre_col = nombres{c};

        switch nombre_col
            case 'Metodo'
                ancho_col(c) = 180;

            case {'score_max','ON_dB','OFF_dB'}
                ancho_col(c) = 135;

            case {'rep_0dB','rep_3dB','rep_total','met_val','met_total'}
                ancho_col(c) = 115;

            case {'sup_3dB'}
                ancho_col(c) = 120;

            case {'err_kHz','err_pct'}
                ancho_col(c) = 125;

            case {'fc_kHz','fc_ref_kHz','ancho_kHz','fmin_kHz','fmax_kHz','fc_prom_kHz','fc_val_kHz','crit_dB'}
                ancho_col(c) = 135;

            otherwise
                ancho_col(c) = 130;
        end
    end

    margen_izq = 35;
    margen_der = 35;

    ancho_fig = margen_izq + sum(ancho_col) + margen_der;

    fig = figure('Color','w', ...
        'Units','pixels', ...
        'Position',[80 100 ancho_fig alto_fig], ...
        'Name', titulo_figura, ...
        'NumberTitle','off');

    ax = axes('Parent',fig, ...
        'Units','pixels', ...
        'Position',[0 0 ancho_fig alto_fig]);

    axis(ax, [0 ancho_fig 0 alto_fig]);
    axis(ax, 'off');
    hold(ax, 'on');

    %% Titulo

    text(ax, ancho_fig/2, alto_fig - margen_sup - alto_titulo/2, titulo_figura, ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontWeight','bold', ...
        'FontSize',24, ...
        'Interpreter','none');

    %% Tabla

    x0 = margen_izq;
    y0 = margen_inf + alto_header + nFilas*alto_fila;

    color_header = [0.86 0.86 0.86];
    color_fila_1 = [1 1 1];
    color_fila_2 = [0.92 0.92 0.92];
    color_borde = [0.65 0.65 0.65];

    x = x0;

    for c = 1:nCols

        rectangle(ax, ...
            'Position',[x, y0 - alto_header, ancho_col(c), alto_header], ...
            'FaceColor',color_header, ...
            'EdgeColor',color_borde, ...
            'LineWidth',0.9);

        text(ax, x + ancho_col(c)/2, y0 - alto_header/2, nombres{c}, ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontWeight','bold', ...
            'FontSize',11, ...
            'Interpreter','none');

        x = x + ancho_col(c);
    end

    for r = 1:nFilas

        y = y0 - alto_header - r*alto_fila;

        if mod(r,2) == 0
            color_fila = color_fila_2;
        else
            color_fila = color_fila_1;
        end

        x = x0;

        for c = 1:nCols

            rectangle(ax, ...
                'Position',[x, y, ancho_col(c), alto_fila], ...
                'FaceColor',color_fila, ...
                'EdgeColor',[0.82 0.82 0.82], ...
                'LineWidth',0.7);

            text(ax, x + ancho_col(c)/2, y + alto_fila/2, datos_txt{r,c}, ...
                'HorizontalAlignment','center', ...
                'VerticalAlignment','middle', ...
                'FontSize',11.5, ...
                'Interpreter','none');

            x = x + ancho_col(c);
        end
    end

    drawnow;

    set(fig, 'PaperPositionMode', 'auto');

    print(fig, archivo_png, '-dpng', '-r220');
    savefig(fig, archivo_fig);
end

function agregar_plano_metodo(xmin, xmax, yvalor, zmin, zmax, color_rgb)

    X = [xmin xmax; xmin xmax];
    Y = [yvalor yvalor; yvalor yvalor];
    Z = [zmin zmin; zmax zmax];

    surf(X, Y, Z, ...
        'FaceColor', color_rgb, ...
        'FaceAlpha', 0.06, ...
        'EdgeColor', 'none', ...
        'HandleVisibility','off');
end