%% T10_P1_comparativa_LED1_LED2_terreno.m
% Comparativa espectral - P1 / Influencia LED 1 y LED 2
%
% Punto evaluado:
%   P1
%
% LEDs evaluados:
%   LED 1: 45.642 kHz  -> principal en P1
%   LED 2: 40.623 kHz  -> influencia secundaria esperada
%
% Metodologia:
%   - Periodograma: metodo principal, con busqueda local estricta.
%   - Welch: metodo complementario, con busqueda local.
%   - Multitaper: metodo complementario, con busqueda local.
%
% Antes de ejecutar este script, modificar las variables carpeta_ON
% y carpeta_OFF con las rutas locales donde se encuentran los archivos .csv
% de la medicion correspondiente.
%
% La carpeta_ON debe contener los archivos ON_P1_REP*.csv indicados
% en la lista archivos_ON.
% La carpeta_OFF debe contener los archivos OFF comunes indicados
% en la lista archivos_OFF.
%
% Ejemplo:
% carpeta_ON  = 'C:\Users\NombreUsuario\Desktop\Terreno_ON_M1';
% carpeta_OFF = 'C:\Users\NombreUsuario\Desktop\Terreno_OFF';
%
% Salidas:
% Resultados_Terreno\Comparativas\P1_LEDs_1_2\01_Periodogram
% Resultados_Terreno\Comparativas\P1_LEDs_1_2\02_Welch
% Resultados_Terreno\Comparativas\P1_LEDs_1_2\03_Multitaper

clear;
clc;
close all;

%% 1. Configuracion general

carpeta_base = 'C:\Users\berni\OneDrive\Escritorio\Modulo Prof\Archivos Tesis\Toma de Datos\Pruebas en terreno';

carpeta_ON = fullfile(carpeta_base, 'Terreno_ON_M1');
carpeta_OFF = fullfile(carpeta_base, 'Terreno_OFF');

carpeta_salida_base = fullfile( ...
    carpeta_base, ...
    'Resultados_Terreno', ...
    'Comparativas', ...
    'P1_LEDs_1_2');

carpeta_salida_periodogram = fullfile(carpeta_salida_base, '01_Periodogram');
carpeta_salida_welch = fullfile(carpeta_salida_base, '02_Welch');
carpeta_salida_multitaper = fullfile(carpeta_salida_base, '03_Multitaper');

crear_carpeta(carpeta_salida_base);
crear_carpeta(carpeta_salida_periodogram);
crear_carpeta(carpeta_salida_welch);
crear_carpeta(carpeta_salida_multitaper);

nombre_punto = "P1";
nombre_comparativa = "P1_LEDs_1_2";

nRep = 3;

archivos_ON = cell(nRep, 1);
archivos_OFF = cell(nRep, 1);

for r = 1:nRep

    archivos_ON{r} = fullfile( ...
        carpeta_ON, ...
        sprintf('ON_P1_REP%d.csv', r));

    archivos_OFF{r} = fullfile( ...
        carpeta_OFF, ...
        sprintf('OFF_REP%d.csv', r));
end

%% 2. Frecuencias de referencia

leds = table( ...
    ["LED 1"; "LED 2"], ...
    ["Principal en P1"; "Influencia secundaria esperada"], ...
    [45.642; 40.623], ...
    'VariableNames', { ...
    'led', ...
    'tipo', ...
    'f_ref_kHz'});

%% 3. Parametros generales

parametros.fmin_Hz = 30e3;
parametros.fmax_Hz = 90e3;
parametros.Fs_configurada_Hz = 50e6;

parametros.criterio_dB = 3;
parametros.umbral_repeticiones = nRep;

% Para Periodograma se evalua directamente la frecuencia de referencia.
parametros.semiancho_periodogram_Hz = 0;

% Para Welch y Multitaper se permite una busqueda local acotada.
parametros.semiancho_welch_Hz = 1000;
parametros.semiancho_multitaper_Hz = 1000;

% Ventana para repetibilidad en metodos complementarios.
parametros.ventana_repetibilidad_Hz = 200;

% Welch.
parametros.Nseg_welch = 2^20;
parametros.fraccion_solapamiento_welch = 0.50;

% Multitaper.
parametros.NW_multitaper = 2.5;
parametros.NFFT_multitaper = 2^20;

% Figuras.
parametros.ancho_zoom_Hz = 2e3;
parametros.ancho_grafica_tipo_laboratorio_kHz = 2.5;

%% 4. Configuracion de metodos

metodos = struct();

metodos(1).nombre = "Periodogram";
metodos(1).nombre_visible = "Periodograma";
metodos(1).rol = "Principal";
metodos(1).carpeta = carpeta_salida_periodogram;
metodos(1).modo_evaluacion = "Referencia fija";
metodos(1).semiancho_busqueda_Hz = parametros.semiancho_periodogram_Hz;

metodos(2).nombre = "Welch";
metodos(2).nombre_visible = "Welch";
metodos(2).rol = "Complementario";
metodos(2).carpeta = carpeta_salida_welch;
metodos(2).modo_evaluacion = "Busqueda local";
metodos(2).semiancho_busqueda_Hz = parametros.semiancho_welch_Hz;

metodos(3).nombre = "Multitaper";
metodos(3).nombre_visible = "Multitaper";
metodos(3).rol = "Complementario";
metodos(3).carpeta = carpeta_salida_multitaper;
metodos(3).modo_evaluacion = "Busqueda local";
metodos(3).semiancho_busqueda_Hz = parametros.semiancho_multitaper_Hz;

fprintf('\n============================================================\n');
fprintf('COMPARATIVA P1 - LED 1 Y LED 2\n');
fprintf('============================================================\n');
fprintf('Carpeta base:\n%s\n\n', carpeta_base);
fprintf('Carpeta ON:\n%s\n\n', carpeta_ON);
fprintf('Carpeta OFF:\n%s\n\n', carpeta_OFF);
fprintf('Carpeta salida base:\n%s\n\n', carpeta_salida_base);

fprintf('Frecuencias evaluadas:\n');
disp(leds);

%% 5. Verificacion de archivos

for r = 1:nRep

    if ~exist(archivos_ON{r}, 'file')

        error( ...
            'No existe el archivo ON de la repeticion %d:\n%s', ...
            r, ...
            archivos_ON{r});
    end

    if ~exist(archivos_OFF{r}, 'file')

        error( ...
            'No existe el archivo OFF de la repeticion %d:\n%s', ...
            r, ...
            archivos_OFF{r});
    end
end

fprintf('Archivos verificados correctamente.\n');

%% 6. Ejecucion de los tres metodos

tabla_global = table();
resultados_metodos = struct([]);

for m = 1:numel(metodos)

    metodo_actual = metodos(m);

    fprintf('\n============================================================\n');
    fprintf('EJECUTANDO METODO: %s\n', metodo_actual.nombre_visible);
    fprintf('MODO DE EVALUACION: %s\n', metodo_actual.modo_evaluacion);
    fprintf('============================================================\n');

    resultado = calcular_metodo_comparativo( ...
        metodo_actual, ...
        archivos_ON, ...
        archivos_OFF, ...
        parametros);

    tabla_comparativa = evaluar_frecuencias_leds( ...
        resultado, ...
        leds, ...
        metodo_actual, ...
        nombre_punto, ...
        parametros);

    resultados_metodos(m).nombre = metodo_actual.nombre;
    resultados_metodos(m).nombre_visible = metodo_actual.nombre_visible;
    resultados_metodos(m).resultado = resultado;
    resultados_metodos(m).tabla_comparativa = tabla_comparativa;

    nombre_archivo_metodo = lower(char(metodo_actual.nombre));

    writetable( ...
        tabla_comparativa, ...
        fullfile( ...
        metodo_actual.carpeta, ...
        sprintf('tabla_comparativa_%s_%s.csv', ...
        char(nombre_comparativa), ...
        nombre_archivo_metodo)));

    writetable( ...
        resultado.tabla_score, ...
        fullfile( ...
        metodo_actual.carpeta, ...
        sprintf('score_promedio_%s_%s.csv', ...
        char(nombre_comparativa), ...
        nombre_archivo_metodo)));

    writetable( ...
        resultado.info_repeticiones, ...
        fullfile( ...
        metodo_actual.carpeta, ...
        sprintf('info_repeticiones_%s_%s.csv', ...
        char(nombre_comparativa), ...
        nombre_archivo_metodo)));

    save( ...
        fullfile( ...
        metodo_actual.carpeta, ...
        sprintf('datos_%s_%s.mat', ...
        char(nombre_comparativa), ...
        nombre_archivo_metodo)), ...
        'resultado', ...
        'tabla_comparativa', ...
        'leds', ...
        'parametros', ...
        'metodo_actual');

    guardar_tabla_png( ...
        tabla_comparativa, ...
        sprintf('TABLA COMPARATIVA %s - %s', ...
        char(nombre_comparativa), ...
        char(metodo_actual.nombre_visible)), ...
        fullfile( ...
        metodo_actual.carpeta, ...
        sprintf('05_tabla_comparativa_%s_%s.png', ...
        char(nombre_comparativa), ...
        nombre_archivo_metodo)));

    generar_figuras_metodo( ...
        resultado, ...
        tabla_comparativa, ...
        leds, ...
        metodo_actual, ...
        nombre_comparativa, ...
        parametros);

    tabla_global = [tabla_global; tabla_comparativa]; %#ok<AGROW>

    fprintf('\nResultado comparativo - %s:\n', metodo_actual.nombre_visible);
    disp(tabla_comparativa);
end

%% 7. Resumen global

writetable( ...
    tabla_global, ...
    fullfile( ...
    carpeta_salida_base, ...
    'tabla_resumen_global_P1_LEDs_1_2.csv'));

guardar_tabla_png( ...
    tabla_global, ...
    'TABLA RESUMEN GLOBAL - COMPARATIVA P1 LED 1 Y LED 2', ...
    fullfile( ...
    carpeta_salida_base, ...
    'tabla_resumen_global_P1_LEDs_1_2.png'));

generar_figura_global( ...
    tabla_global, ...
    leds, ...
    metodos, ...
    carpeta_salida_base, ...
    parametros);

generar_figuras_locales_tipo_laboratorio_terreno( ...
    resultados_metodos, ...
    tabla_global, ...
    leds, ...
    nombre_punto, ...
    nombre_comparativa, ...
    carpeta_salida_base, ...
    parametros);

save( ...
    fullfile(carpeta_salida_base, 'datos_resumen_global_P1_LEDs_1_2.mat'), ...
    'tabla_global', ...
    'leds', ...
    'parametros', ...
    'metodos', ...
    'resultados_metodos');

fprintf('\n============================================================\n');
fprintf('COMPARATIVA P1 FINALIZADA\n');
fprintf('Resultados guardados en:\n%s\n', carpeta_salida_base);
fprintf('============================================================\n');

%% Funciones locales

function crear_carpeta(carpeta)

    if ~exist(carpeta, 'dir')
        mkdir(carpeta);
    end
end

function resultado = calcular_metodo_comparativo( ...
    metodo_actual, ...
    archivos_ON, ...
    archivos_OFF, ...
    parametros)

    nRep = numel(archivos_ON);

    f_ref_Hz = [];
    PSD_ON_mat_dB = [];
    PSD_OFF_mat_dB = [];

    info_repeticiones = table();

    for r = 1:nRep

        fprintf('\n------------------------------------------------------------\n');
        fprintf('Metodo %s - Repeticion %d/%d\n', ...
            metodo_actual.nombre_visible, ...
            r, ...
            nRep);

        fprintf('ON : %s\n', archivos_ON{r});
        fprintf('OFF: %s\n', archivos_OFF{r});

        [tON, xON, Fs_ON_estimado_Hz, N_ON_original] = ...
            leer_csv_rigol_terreno( ...
            archivos_ON{r}, ...
            parametros.Fs_configurada_Hz);

        [tOFF, xOFF, Fs_OFF_estimado_Hz, N_OFF_original] = ...
            leer_csv_rigol_terreno( ...
            archivos_OFF{r}, ...
            parametros.Fs_configurada_Hz);

        xON = xON(:);
        xOFF = xOFF(:);

        N_usado = min(numel(xON), numel(xOFF));

        tON = tON(1:N_usado);
        tOFF = tOFF(1:N_usado);

        xON = xON(1:N_usado);
        xOFF = xOFF(1:N_usado);

        duracion_ON_s = tON(end) - tON(1);
        duracion_OFF_s = tOFF(end) - tOFF(1);

        if duracion_ON_s <= 0 || ~isfinite(duracion_ON_s)
            duracion_ON_s = (N_usado - 1)/parametros.Fs_configurada_Hz;
        end

        if duracion_OFF_s <= 0 || ~isfinite(duracion_OFF_s)
            duracion_OFF_s = (N_usado - 1)/parametros.Fs_configurada_Hz;
        end

        Fs_usada_Hz = parametros.Fs_configurada_Hz;

        xON = xON - mean(xON, 'omitnan');
        xOFF = xOFF - mean(xOFF, 'omitnan');

        xON(~isfinite(xON)) = 0;
        xOFF(~isfinite(xOFF)) = 0;

        switch char(metodo_actual.nombre)

            case 'Periodogram'

                nfft = N_usado;

                [Pxx_ON, fON_Hz] = periodogram( ...
                    xON, ...
                    rectwin(N_usado), ...
                    nfft, ...
                    Fs_usada_Hz, ...
                    'psd');

                [Pxx_OFF, fOFF_Hz] = periodogram( ...
                    xOFF, ...
                    rectwin(N_usado), ...
                    nfft, ...
                    Fs_usada_Hz, ...
                    'psd');

                parametro_1 = nfft;
                parametro_2 = NaN;
                df_Hz = Fs_usada_Hz/nfft;

            case 'Welch'

                if N_usado < parametros.Nseg_welch

                    error( ...
                        ['La repeticion %d contiene menos muestras que ', ...
                        'Nseg_welch = %d.'], ...
                        r, ...
                        parametros.Nseg_welch);
                end

                Nseg = min(parametros.Nseg_welch, N_usado);
                noverlap = floor(parametros.fraccion_solapamiento_welch*Nseg);

                if noverlap >= Nseg
                    noverlap = Nseg - 1;
                end

                nfft = Nseg;
                ventana_welch = hann(Nseg, 'periodic');

                [Pxx_ON, fON_Hz] = pwelch( ...
                    xON, ...
                    ventana_welch, ...
                    noverlap, ...
                    nfft, ...
                    Fs_usada_Hz, ...
                    'onesided');

                [Pxx_OFF, fOFF_Hz] = pwelch( ...
                    xOFF, ...
                    ventana_welch, ...
                    noverlap, ...
                    nfft, ...
                    Fs_usada_Hz, ...
                    'onesided');

                parametro_1 = Nseg;
                parametro_2 = noverlap;
                df_Hz = Fs_usada_Hz/nfft;

            case 'Multitaper'

                [Pxx_ON, fON_Hz] = pmtm( ...
                    xON, ...
                    parametros.NW_multitaper, ...
                    parametros.NFFT_multitaper, ...
                    Fs_usada_Hz);

                [Pxx_OFF, fOFF_Hz] = pmtm( ...
                    xOFF, ...
                    parametros.NW_multitaper, ...
                    parametros.NFFT_multitaper, ...
                    Fs_usada_Hz);

                parametro_1 = parametros.NW_multitaper;
                parametro_2 = parametros.NFFT_multitaper;
                df_Hz = Fs_usada_Hz/parametros.NFFT_multitaper;

            otherwise

                error('Metodo no reconocido.');
        end

        fON_Hz = fON_Hz(:);
        fOFF_Hz = fOFF_Hz(:);

        PSD_ON_dB = 10*log10(Pxx_ON(:) + eps);
        PSD_OFF_dB = 10*log10(Pxx_OFF(:) + eps);

        if isempty(f_ref_Hz)

            f_ref_Hz = fON_Hz;

            PSD_ON_mat_dB = nan(numel(f_ref_Hz), nRep);
            PSD_OFF_mat_dB = nan(numel(f_ref_Hz), nRep);
        end

        PSD_ON_mat_dB(:, r) = interp1( ...
            fON_Hz, ...
            PSD_ON_dB, ...
            f_ref_Hz, ...
            'linear', ...
            NaN);

        PSD_OFF_mat_dB(:, r) = interp1( ...
            fOFF_Hz, ...
            PSD_OFF_dB, ...
            f_ref_Hz, ...
            'linear', ...
            NaN);

        error_Fs_ON_pct = ...
            abs(Fs_ON_estimado_Hz - parametros.Fs_configurada_Hz) / ...
            parametros.Fs_configurada_Hz * 100;

        error_Fs_OFF_pct = ...
            abs(Fs_OFF_estimado_Hz - parametros.Fs_configurada_Hz) / ...
            parametros.Fs_configurada_Hz * 100;

        fila_info = table( ...
            string(metodo_actual.nombre_visible), ...
            string(metodo_actual.modo_evaluacion), ...
            r, ...
            string(archivos_ON{r}), ...
            string(archivos_OFF{r}), ...
            N_ON_original, ...
            N_OFF_original, ...
            N_usado, ...
            duracion_ON_s, ...
            duracion_OFF_s, ...
            Fs_ON_estimado_Hz, ...
            Fs_OFF_estimado_Hz, ...
            Fs_usada_Hz, ...
            error_Fs_ON_pct, ...
            error_Fs_OFF_pct, ...
            parametro_1, ...
            parametro_2, ...
            df_Hz, ...
            'VariableNames', { ...
            'metodo', ...
            'modo_evaluacion', ...
            'repeticion', ...
            'archivo_ON', ...
            'archivo_OFF', ...
            'N_ON_original', ...
            'N_OFF_original', ...
            'N_usado', ...
            'duracion_ON_s', ...
            'duracion_OFF_s', ...
            'Fs_ON_estimado_Hz', ...
            'Fs_OFF_estimado_Hz', ...
            'Fs_usada_Hz', ...
            'error_Fs_ON_pct', ...
            'error_Fs_OFF_pct', ...
            'parametro_1', ...
            'parametro_2', ...
            'df_Hz'});

        info_repeticiones = [info_repeticiones; fila_info]; %#ok<AGROW>

        fprintf('N usado       = %d muestras\n', N_usado);
        fprintf('Fs usada      = %.6f MSa/s\n', Fs_usada_Hz/1e6);
        fprintf('df aproximada = %.6f Hz\n', df_Hz);
    end

    PSD_ON_prom_dB = mean(PSD_ON_mat_dB, 2, 'omitnan');
    PSD_OFF_prom_dB = mean(PSD_OFF_mat_dB, 2, 'omitnan');

    % Misma logica usada en los analisis anteriores:
    % cada repeticion ON se compara con el OFF promedio.
    PSD_OFF_ref_dB = repmat(PSD_OFF_prom_dB, 1, nRep);
    score_mat_dB = PSD_ON_mat_dB - PSD_OFF_ref_dB;

    score_prom_dB = mean(score_mat_dB, 2, 'omitnan');

    idx_banda = ...
        f_ref_Hz >= parametros.fmin_Hz & ...
        f_ref_Hz <= parametros.fmax_Hz;

    f_banda_Hz = f_ref_Hz(idx_banda);
    PSD_ON_banda_dB = PSD_ON_prom_dB(idx_banda);
    PSD_OFF_banda_dB = PSD_OFF_prom_dB(idx_banda);
    score_banda_dB = score_prom_dB(idx_banda);
    score_banda_reps_dB = score_mat_dB(idx_banda, :);

    idx_validos = ...
        isfinite(f_banda_Hz) & ...
        isfinite(PSD_ON_banda_dB) & ...
        isfinite(PSD_OFF_banda_dB) & ...
        isfinite(score_banda_dB);

    f_banda_Hz = f_banda_Hz(idx_validos);
    PSD_ON_banda_dB = PSD_ON_banda_dB(idx_validos);
    PSD_OFF_banda_dB = PSD_OFF_banda_dB(idx_validos);
    score_banda_dB = score_banda_dB(idx_validos);
    score_banda_reps_dB = score_banda_reps_dB(idx_validos, :);

    tabla_score = table( ...
        f_banda_Hz(:)/1e3, ...
        PSD_ON_banda_dB(:), ...
        PSD_OFF_banda_dB(:), ...
        score_banda_dB(:), ...
        'VariableNames', { ...
        'f_kHz', ...
        'PSD_ON_prom_dB', ...
        'PSD_OFF_prom_dB', ...
        'score_prom_dB'});

    for r = 1:nRep

        tabla_score.(sprintf('score_rep%d_dB', r)) = ...
            score_banda_reps_dB(:, r);
    end

    resultado = struct();

    resultado.metodo = metodo_actual.nombre_visible;
    resultado.rol = metodo_actual.rol;
    resultado.modo_evaluacion = metodo_actual.modo_evaluacion;

    resultado.f_ref_Hz = f_ref_Hz;
    resultado.PSD_ON_mat_dB = PSD_ON_mat_dB;
    resultado.PSD_OFF_mat_dB = PSD_OFF_mat_dB;
    resultado.PSD_ON_prom_dB = PSD_ON_prom_dB;
    resultado.PSD_OFF_prom_dB = PSD_OFF_prom_dB;
    resultado.score_mat_dB = score_mat_dB;
    resultado.score_prom_dB = score_prom_dB;

    resultado.f_banda_Hz = f_banda_Hz;
    resultado.f_banda_kHz = f_banda_Hz/1e3;
    resultado.PSD_ON_banda_dB = PSD_ON_banda_dB;
    resultado.PSD_OFF_banda_dB = PSD_OFF_banda_dB;
    resultado.score_banda_dB = score_banda_dB;
    resultado.score_banda_reps_dB = score_banda_reps_dB;

    resultado.tabla_score = tabla_score;
    resultado.info_repeticiones = info_repeticiones;
end

function tabla_comparativa = evaluar_frecuencias_leds( ...
    resultado, ...
    leds, ...
    metodo_actual, ...
    nombre_punto, ...
    parametros)

    nLED = height(leds);
    nRep = size(resultado.score_banda_reps_dB, 2);

    punto = strings(nLED, 1);
    metodo = strings(nLED, 1);
    rol_metodo = strings(nLED, 1);
    modo_evaluacion = strings(nLED, 1);
    led_evaluado = strings(nLED, 1);
    tipo_led = strings(nLED, 1);

    f_ref_kHz = nan(nLED, 1);
    f_evaluada_kHz = nan(nLED, 1);
    delta_kHz = nan(nLED, 1);
    semiancho_busqueda_kHz = nan(nLED, 1);

    score_dB = nan(nLED, 1);
    ON_prom_dB = nan(nLED, 1);
    OFF_prom_dB = nan(nLED, 1);

    rep_0dB = zeros(nLED, 1);
    rep_3dB = zeros(nLED, 1);
    rep_total = repmat(nRep, nLED, 1);

    criterio_dB = repmat(parametros.criterio_dB, nLED, 1);

    supera_3dB = strings(nLED, 1);
    interpretacion = strings(nLED, 1);

    score_rep1_dB = nan(nLED, 1);
    score_rep2_dB = nan(nLED, 1);
    score_rep3_dB = nan(nLED, 1);

    for i = 1:nLED

        f_ref_Hz = leds.f_ref_kHz(i)*1e3;

        if metodo_actual.modo_evaluacion == "Referencia fija"

            % Periodograma: se evalua la frecuencia de referencia ya cerrada.
            [~, idx_detectado] = min(abs(resultado.f_banda_Hz - f_ref_Hz));

            f_evaluada_Hz = resultado.f_banda_Hz(idx_detectado);

            score_maximo = resultado.score_banda_dB(idx_detectado);

            score_reps = resultado.score_banda_reps_dB(idx_detectado, :);

        else

            % Welch y Multitaper: se permite una busqueda local acotada.
            idx_local = ...
                resultado.f_banda_Hz >= f_ref_Hz - metodo_actual.semiancho_busqueda_Hz & ...
                resultado.f_banda_Hz <= f_ref_Hz + metodo_actual.semiancho_busqueda_Hz & ...
                isfinite(resultado.score_banda_dB);

            idx_local_abs = find(idx_local);

            if isempty(idx_local_abs)

                warning( ...
                    'No hay datos en la ventana local de %s.', ...
                    leds.led(i));

                continue;
            end

            [score_maximo, idx_rel] = ...
                max(resultado.score_banda_dB(idx_local_abs));

            idx_detectado = idx_local_abs(idx_rel);

            f_evaluada_Hz = resultado.f_banda_Hz(idx_detectado);

            idx_rep = ...
                resultado.f_banda_Hz >= f_evaluada_Hz - parametros.ventana_repetibilidad_Hz & ...
                resultado.f_banda_Hz <= f_evaluada_Hz + parametros.ventana_repetibilidad_Hz;

            score_reps = nan(1, nRep);

            for r = 1:nRep

                score_temp = resultado.score_banda_reps_dB(idx_rep, r);
                score_temp = score_temp(isfinite(score_temp));

                if isempty(score_temp)
                    score_reps(r) = NaN;
                else
                    score_reps(r) = max(score_temp);
                end
            end
        end

        punto(i) = nombre_punto;
        metodo(i) = metodo_actual.nombre_visible;
        rol_metodo(i) = metodo_actual.rol;
        modo_evaluacion(i) = metodo_actual.modo_evaluacion;
        led_evaluado(i) = leds.led(i);
        tipo_led(i) = leds.tipo(i);

        f_ref_kHz(i) = leds.f_ref_kHz(i);
        f_evaluada_kHz(i) = f_evaluada_Hz/1e3;
        delta_kHz(i) = f_evaluada_kHz(i) - f_ref_kHz(i);
        semiancho_busqueda_kHz(i) = metodo_actual.semiancho_busqueda_Hz/1e3;

        score_dB(i) = score_maximo;
        ON_prom_dB(i) = resultado.PSD_ON_banda_dB(idx_detectado);
        OFF_prom_dB(i) = resultado.PSD_OFF_banda_dB(idx_detectado);

        rep_0dB(i) = sum(score_reps > 0);
        rep_3dB(i) = sum(score_reps >= parametros.criterio_dB);

        if nRep >= 1
            score_rep1_dB(i) = score_reps(1);
        end

        if nRep >= 2
            score_rep2_dB(i) = score_reps(2);
        end

        if nRep >= 3
            score_rep3_dB(i) = score_reps(3);
        end

        if score_dB(i) >= parametros.criterio_dB && ...
                rep_3dB(i) >= parametros.umbral_repeticiones

            supera_3dB(i) = "Si";
            interpretacion(i) = "Confirmado";

        elseif score_dB(i) >= parametros.criterio_dB && ...
                rep_3dB(i) < parametros.umbral_repeticiones

            supera_3dB(i) = "No";
            interpretacion(i) = "Indicio parcial";

        elseif score_dB(i) > 0

            supera_3dB(i) = "No";
            interpretacion(i) = "Indicio debil";

        else

            supera_3dB(i) = "No";
            interpretacion(i) = "No confirmado";
        end
    end

    tabla_comparativa = table( ...
        punto, ...
        metodo, ...
        rol_metodo, ...
        modo_evaluacion, ...
        led_evaluado, ...
        tipo_led, ...
        f_ref_kHz, ...
        f_evaluada_kHz, ...
        delta_kHz, ...
        semiancho_busqueda_kHz, ...
        score_dB, ...
        ON_prom_dB, ...
        OFF_prom_dB, ...
        rep_0dB, ...
        rep_3dB, ...
        rep_total, ...
        criterio_dB, ...
        supera_3dB, ...
        interpretacion, ...
        score_rep1_dB, ...
        score_rep2_dB, ...
        score_rep3_dB, ...
        'VariableNames', { ...
        'punto', ...
        'metodo', ...
        'rol_metodo', ...
        'modo_evaluacion', ...
        'led_evaluado', ...
        'tipo_led', ...
        'f_ref_kHz', ...
        'f_evaluada_kHz', ...
        'delta_kHz', ...
        'semiancho_busqueda_kHz', ...
        'score_dB', ...
        'ON_prom_dB', ...
        'OFF_prom_dB', ...
        'rep_0dB', ...
        'rep_3dB', ...
        'rep_total', ...
        'criterio_dB', ...
        'supera_3dB', ...
        'interpretacion', ...
        'score_rep1_dB', ...
        'score_rep2_dB', ...
        'score_rep3_dB'});
end

function generar_figuras_metodo( ...
    resultado, ...
    tabla_comparativa, ...
    leds, ...
    metodo_actual, ...
    nombre_comparativa, ...
    parametros)

    carpeta_salida = metodo_actual.carpeta;
    nombre_archivo_metodo = lower(char(metodo_actual.nombre));

    %% Figura 1: score ON-OFF completo

    fig = figure( ...
        'Color', 'w', ...
        'Position', [100 100 1500 850]);

    plot( ...
        resultado.f_banda_kHz, ...
        resultado.score_banda_dB, ...
        'LineWidth', 1.5);

    hold on;
    grid on;
    box on;

    yline( ...
        0, ...
        '--', ...
        '0 dB', ...
        'HandleVisibility', 'off');

    yline( ...
        parametros.criterio_dB, ...
        '--', ...
        sprintf('Criterio %.1f dB', parametros.criterio_dB), ...
        'HandleVisibility', 'off');

    for i = 1:height(tabla_comparativa)

        xline( ...
            tabla_comparativa.f_ref_kHz(i), ...
            '--', ...
            sprintf('%s ref %.3f kHz', ...
            tabla_comparativa.led_evaluado(i), ...
            tabla_comparativa.f_ref_kHz(i)), ...
            'LineWidth', 1.1, ...
            'LabelOrientation', 'aligned', ...
            'HandleVisibility', 'off');

        if abs(tabla_comparativa.delta_kHz(i)) > 0.02

            xline( ...
                tabla_comparativa.f_evaluada_kHz(i), ...
                ':', ...
                sprintf('%s eval %.3f kHz', ...
                tabla_comparativa.led_evaluado(i), ...
                tabla_comparativa.f_evaluada_kHz(i)), ...
                'LineWidth', 1.2, ...
                'LabelOrientation', 'aligned', ...
                'HandleVisibility', 'off');
        end
    end

    xlabel('Frecuencia [kHz]');
    ylabel('Score ON - OFF [dB]');

    title( ...
        sprintf('%s - %s: score ON-OFF', ...
        char(nombre_comparativa), ...
        char(metodo_actual.nombre_visible)), ...
        'Interpreter', 'none');

    xlim([parametros.fmin_Hz parametros.fmax_Hz]/1e3);

    guardar_figura_png( ...
        fig, ...
        fullfile( ...
        carpeta_salida, ...
        sprintf('01_%s_%s_score_ON_OFF.png', ...
        char(nombre_comparativa), ...
        nombre_archivo_metodo)));

    %% Figura 2: barras comparativas sin barras negativas

    score_grafico = tabla_comparativa.score_dB;
    score_grafico(score_grafico < 0) = 0;

    fig = figure( ...
        'Color', 'w', ...
        'Position', [100 100 1200 700]);

    x = 1:height(tabla_comparativa);

    bar( ...
        x, ...
        score_grafico, ...
        0.65);

    hold on;
    grid on;
    box on;

    yline( ...
        parametros.criterio_dB, ...
        '--', ...
        sprintf('Criterio %.1f dB', parametros.criterio_dB), ...
        'LineWidth', 1.1, ...
        'HandleVisibility', 'off');

    xlabel('LED evaluado');
    ylabel('Score local ON-OFF [dB]');

    title( ...
        sprintf('%s - %s: comparativa de influencia', ...
        char(nombre_comparativa), ...
        char(metodo_actual.nombre_visible)), ...
        'Interpreter', 'none');

    xticks(x);
    xticklabels(tabla_comparativa.led_evaluado);
    xtickangle(0);

    for i = 1:height(tabla_comparativa)

        text( ...
            x(i), ...
            score_grafico(i) + 0.35, ...
            sprintf('%.2f dB\n%d/%d\n%s', ...
            tabla_comparativa.score_dB(i), ...
            tabla_comparativa.rep_3dB(i), ...
            tabla_comparativa.rep_total(i), ...
            char(tabla_comparativa.interpretacion(i))), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'bottom', ...
            'FontSize', 9);
    end

    ylim([ ...
        0, ...
        max(parametros.criterio_dB + 1.5, max(score_grafico) + 3)]);

    guardar_figura_png( ...
        fig, ...
        fullfile( ...
        carpeta_salida, ...
        sprintf('02_%s_%s_barras_comparativas.png', ...
        char(nombre_comparativa), ...
        nombre_archivo_metodo)));

    %% Figuras de zoom por LED

    for i = 1:height(tabla_comparativa)

        f_ref_Hz = tabla_comparativa.f_ref_kHz(i)*1e3;

        idx_zoom = ...
            resultado.f_banda_Hz >= f_ref_Hz - parametros.ancho_zoom_Hz & ...
            resultado.f_banda_Hz <= f_ref_Hz + parametros.ancho_zoom_Hz;

        fig = figure( ...
            'Color', 'w', ...
            'Position', [100 100 1500 850]);

        plot( ...
            resultado.f_banda_kHz(idx_zoom), ...
            resultado.score_banda_dB(idx_zoom), ...
            'LineWidth', 1.5);

        hold on;
        grid on;
        box on;

        yline( ...
            0, ...
            '--', ...
            '0 dB', ...
            'HandleVisibility', 'off');

        yline( ...
            parametros.criterio_dB, ...
            '--', ...
            sprintf('Criterio %.1f dB', parametros.criterio_dB), ...
            'HandleVisibility', 'off');

        xline( ...
            tabla_comparativa.f_ref_kHz(i), ...
            '--', ...
            sprintf('Ref %.3f kHz', tabla_comparativa.f_ref_kHz(i)), ...
            'LineWidth', 1.2, ...
            'LabelOrientation', 'aligned', ...
            'HandleVisibility', 'off');

        if abs(tabla_comparativa.delta_kHz(i)) > 0.02

            xline( ...
                tabla_comparativa.f_evaluada_kHz(i), ...
                ':', ...
                sprintf('Eval %.3f kHz', tabla_comparativa.f_evaluada_kHz(i)), ...
                'LineWidth', 1.3, ...
                'LabelOrientation', 'aligned', ...
                'HandleVisibility', 'off');
        end

        xlabel('Frecuencia [kHz]');
        ylabel('Score ON - OFF [dB]');

        title( ...
            sprintf('%s - %s: zona local %s', ...
            char(nombre_comparativa), ...
            char(metodo_actual.nombre_visible), ...
            char(tabla_comparativa.led_evaluado(i))), ...
            'Interpreter', 'none');

        xlim([ ...
            (f_ref_Hz - parametros.ancho_zoom_Hz)/1e3, ...
            (f_ref_Hz + parametros.ancho_zoom_Hz)/1e3]);

        guardar_figura_png( ...
            fig, ...
            fullfile( ...
            carpeta_salida, ...
            sprintf('03_%s_%s_zoom_%s.png', ...
            char(nombre_comparativa), ...
            nombre_archivo_metodo, ...
            limpiar_nombre(char(tabla_comparativa.led_evaluado(i))))));
    end

    %% Figura PSD promedio ON/OFF

    fig = figure( ...
        'Color', 'w', ...
        'Position', [100 100 1500 850]);

    plot( ...
        resultado.f_banda_kHz, ...
        resultado.PSD_ON_banda_dB, ...
        'LineWidth', 1.5);

    hold on;

    plot( ...
        resultado.f_banda_kHz, ...
        resultado.PSD_OFF_banda_dB, ...
        'LineWidth', 1.5);

    grid on;
    box on;

    for i = 1:height(leds)

        xline( ...
            leds.f_ref_kHz(i), ...
            '--', ...
            sprintf('%s %.3f kHz', ...
            leds.led(i), ...
            leds.f_ref_kHz(i)), ...
            'LineWidth', 1.1, ...
            'LabelOrientation', 'aligned', ...
            'HandleVisibility', 'off');
    end

    xlabel('Frecuencia [kHz]');
    ylabel('PSD [dB/Hz]');

    title( ...
        sprintf('%s - %s: PSD promedio ON/OFF', ...
        char(nombre_comparativa), ...
        char(metodo_actual.nombre_visible)), ...
        'Interpreter', 'none');

    legend( ...
        'ON P1 promedio', ...
        'OFF promedio', ...
        'Location', 'best');

    xlim([parametros.fmin_Hz parametros.fmax_Hz]/1e3);

    guardar_figura_png( ...
        fig, ...
        fullfile( ...
        carpeta_salida, ...
        sprintf('04_%s_%s_PSD_promedio_ON_OFF.png', ...
        char(nombre_comparativa), ...
        nombre_archivo_metodo)));
end

function generar_figuras_locales_tipo_laboratorio_terreno( ...
    resultados_metodos, ...
    tabla_global, ...
    leds, ...
    nombre_punto, ...
    nombre_comparativa, ...
    carpeta_salida_base, ...
    parametros)

    % Genera las figuras tipo laboratorio usando las curvas ya calculadas.
    % No crea carpetas nuevas: guarda directamente en carpeta_salida_base.

    ancho_grafica_local_kHz = parametros.ancho_grafica_tipo_laboratorio_kHz;

    nombres_metodos_tabla = ["Periodograma"; "Welch"; "Multitaper"];
    nombres_metodos_curvas = ["Periodograma"; "Welch"; "Multitaper local"];

    for i_led = 1:height(leds)

        led_actual = leds.led(i_led);
        fc_ref_kHz = leds.f_ref_kHz(i_led);

        fc_metodos_kHz = nan(3, 1);
        score_metodos_dB = nan(3, 1);

        f_per_kHz = [];
        score_per_dB = [];
        f_wel_kHz = [];
        score_wel_dB = [];
        f_mt_kHz = [];
        score_mt_dB = [];

        for i_met = 1:3

            metodo_busqueda = nombres_metodos_tabla(i_met);

            idx_tabla = ...
                tabla_global.led_evaluado == led_actual & ...
                tabla_global.metodo == metodo_busqueda;

            if any(idx_tabla)

                idx_primero = find(idx_tabla, 1, 'first');

                fc_metodos_kHz(i_met) = tabla_global.f_evaluada_kHz(idx_primero);
                score_metodos_dB(i_met) = tabla_global.score_dB(idx_primero);
            end

            idx_resultado = [];

            for k = 1:numel(resultados_metodos)

                if resultados_metodos(k).nombre_visible == metodo_busqueda
                    idx_resultado = k;
                    break;
                end
            end

            if isempty(idx_resultado)
                continue;
            end

            resultado = resultados_metodos(idx_resultado).resultado;

            switch char(metodo_busqueda)

                case 'Periodograma'
                    f_per_kHz = resultado.f_banda_kHz(:);
                    score_per_dB = resultado.score_banda_dB(:);

                case 'Welch'
                    f_wel_kHz = resultado.f_banda_kHz(:);
                    score_wel_dB = resultado.score_banda_dB(:);

                case 'Multitaper'
                    f_mt_kHz = resultado.f_banda_kHz(:);
                    score_mt_dB = resultado.score_banda_dB(:);
            end
        end

        if isempty(f_per_kHz) || isempty(f_wel_kHz) || isempty(f_mt_kHz)

            warning( ...
                'No se genero figura tipo laboratorio para %s porque faltan curvas.', ...
                char(led_actual));

            continue;
        end

        fc_promedio_kHz = mean(fc_metodos_kHz, 'omitnan');

        fmin_local_kHz = fc_ref_kHz - ancho_grafica_local_kHz;
        fmax_local_kHz = fc_ref_kHz + ancho_grafica_local_kHz;

        crear_figura_score_local_2D_terreno( ...
            f_per_kHz, ...
            score_per_dB, ...
            f_wel_kHz, ...
            score_wel_dB, ...
            f_mt_kHz, ...
            score_mt_dB, ...
            fc_ref_kHz, ...
            fc_promedio_kHz, ...
            fc_metodos_kHz, ...
            score_metodos_dB, ...
            cellstr(nombres_metodos_curvas), ...
            parametros.criterio_dB, ...
            fmin_local_kHz, ...
            fmax_local_kHz, ...
            char(nombre_punto), ...
            char(led_actual), ...
            char(nombre_comparativa), ...
            carpeta_salida_base);

        crear_figura_score_cascada_2D_terreno( ...
            f_per_kHz, ...
            score_per_dB, ...
            f_wel_kHz, ...
            score_wel_dB, ...
            f_mt_kHz, ...
            score_mt_dB, ...
            fc_ref_kHz, ...
            fc_promedio_kHz, ...
            fc_metodos_kHz, ...
            score_metodos_dB, ...
            parametros.criterio_dB, ...
            fmin_local_kHz, ...
            fmax_local_kHz, ...
            char(nombre_punto), ...
            char(led_actual), ...
            char(nombre_comparativa), ...
            carpeta_salida_base);
    end
end

function generar_figura_global( ...
    tabla_global, ...
    leds, ...
    metodos, ...
    carpeta_salida_base, ...
    parametros)

    nLED = height(leds);
    nMetodos = numel(metodos);

    matriz_scores = nan(nLED, nMetodos);

    for i = 1:nLED

        for m = 1:nMetodos

            idx = ...
                tabla_global.led_evaluado == leds.led(i) & ...
                tabla_global.metodo == metodos(m).nombre_visible;

            if any(idx)

                idx_primero = find(idx, 1, 'first');

                matriz_scores(i, m) = tabla_global.score_dB(idx_primero);
            end
        end
    end

    matriz_scores_grafico = matriz_scores;
    matriz_scores_grafico(matriz_scores_grafico < 0) = 0;

    fig = figure( ...
        'Color', 'w', ...
        'Position', [100 100 1300 750]);

    bar(matriz_scores_grafico);

    hold on;
    grid on;
    box on;

    yline( ...
        parametros.criterio_dB, ...
        '--', ...
        sprintf('Criterio %.1f dB', parametros.criterio_dB), ...
        'LineWidth', 1.1, ...
        'HandleVisibility', 'off');

    xlabel('LED evaluado');
    ylabel('Score local ON-OFF [dB]');

    title( ...
        'P1 - Comparativa global LED 1 y LED 2', ...
        'Interpreter', 'none');

    xticks(1:nLED);
    xticklabels(leds.led);

    leyenda = strings(1, nMetodos);

    for m = 1:nMetodos
        leyenda(m) = metodos(m).nombre_visible;
    end

    legend( ...
        leyenda, ...
        'Location', 'best');

    ylim([ ...
        0, ...
        max(parametros.criterio_dB + 1.5, max(matriz_scores_grafico(:)) + 3)]);

    guardar_figura_png( ...
        fig, ...
        fullfile( ...
        carpeta_salida_base, ...
        'figura_resumen_global_scores_P1_LEDs_1_2.png'));
end

function [t, y, Fs_estimado_Hz, N_original] = ...
    leer_csv_rigol_terreno(nombre_archivo, Fs_default)

    M = readmatrix(nombre_archivo);

    if isempty(M)

        error('El archivo esta vacio:\n%s', nombre_archivo);
    end

    columnas_validas = [];

    for c = 1:size(M, 2)

        if sum(isfinite(M(:, c))) > 10
            columnas_validas = [columnas_validas, c]; %#ok<AGROW>
        end
    end

    if isempty(columnas_validas)

        error( ...
            'No se detectaron columnas numericas validas en:\n%s', ...
            nombre_archivo);
    end

    M = M(:, columnas_validas);

    t = [];
    y = [];
    Fs_estimado_Hz = Fs_default;

    if size(M, 2) >= 2

        for c = 1:(size(M, 2) - 1)

            t_cand = M(:, c);
            y_cand = M(:, c + 1);

            idx_validos = isfinite(t_cand) & isfinite(y_cand);

            t_temp = t_cand(idx_validos);
            y_temp = y_cand(idx_validos);

            t_temp = t_temp(:);
            y_temp = y_temp(:);

            if numel(y_temp) < 10
                continue;
            end

            duracion_s = t_temp(end) - t_temp(1);

            if duracion_s <= 0 || ~isfinite(duracion_s)
                continue;
            end

            Fs_temp_Hz = (numel(t_temp) - 1)/duracion_s;

            error_Fs_pct = abs(Fs_temp_Hz - Fs_default)/Fs_default*100;

            if error_Fs_pct <= 20 && std(y_temp, 'omitnan') > 0

                t = t_temp;
                y = y_temp;
                Fs_estimado_Hz = Fs_temp_Hz;
                N_original = numel(y);
                return;
            end
        end
    end

    y = M(:, end);
    y = y(isfinite(y));
    y = y(:);

    if numel(y) < 10

        error( ...
            'El archivo contiene muy pocas muestras validas:\n%s', ...
            nombre_archivo);
    end

    t = (0:numel(y)-1)'/Fs_default;
    Fs_estimado_Hz = Fs_default;
    N_original = numel(y);
end

function guardar_figura_png(fig, archivo_png)

    drawnow;

    try

        exportgraphics( ...
            fig, ...
            archivo_png, ...
            'Resolution', 300);

    catch

        print( ...
            fig, ...
            archivo_png, ...
            '-dpng', ...
            '-r300');
    end
end

function guardar_tabla_png(tabla, titulo_tabla, archivo_png)

    if isempty(tabla)

        warning('La tabla esta vacia. No se guardara la figura.');
        return;
    end

    datos = formatear_tabla_para_figura(tabla);
    nombres = tabla.Properties.VariableNames;

    nFilas = height(tabla);
    nColumnas = width(tabla);

    ancho_columnas = zeros(1, nColumnas);

    for c = 1:nColumnas

        largo_maximo = length(nombres{c});

        for i = 1:nFilas
            largo_maximo = max(largo_maximo, length(datos{i, c}));
        end

        ancho_columnas(c) = max(80, min(170, 8*largo_maximo + 24));
    end

    margen_izquierdo = 30;
    margen_derecho = 30;
    margen_inferior = 25;

    alto_titulo = 55;
    alto_fila = 28;
    alto_encabezado = 30;

    ancho_tabla = sum(ancho_columnas);
    alto_tabla = alto_encabezado + nFilas*alto_fila;

    ancho_figura = margen_izquierdo + ancho_tabla + margen_derecho;
    alto_figura = margen_inferior + alto_tabla + alto_titulo + 15;

    fig = figure( ...
        'Color', 'w', ...
        'Units', 'pixels', ...
        'Position', [100, 100, ancho_figura, alto_figura]);

    ax = axes( ...
        'Parent', fig, ...
        'Units', 'pixels', ...
        'Position', [0, 0, ancho_figura, alto_figura]);

    axis(ax, [0 ancho_figura 0 alto_figura]);
    axis(ax, 'off');
    hold(ax, 'on');

    text( ...
        ax, ...
        ancho_figura/2, ...
        alto_figura - 28, ...
        titulo_tabla, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontWeight', 'bold', ...
        'FontSize', 15, ...
        'Interpreter', 'none');

    x0 = margen_izquierdo;
    y0 = margen_inferior + alto_tabla;

    color_encabezado = [0.93 0.93 0.93];
    color_fila_1 = [1 1 1];
    color_fila_2 = [0.94 0.94 0.94];
    color_borde = [0.65 0.65 0.65];

    x = x0;

    for c = 1:nColumnas

        rectangle( ...
            ax, ...
            'Position', [x, y0 - alto_encabezado, ancho_columnas(c), alto_encabezado], ...
            'FaceColor', color_encabezado, ...
            'EdgeColor', color_borde, ...
            'LineWidth', 0.8);

        text( ...
            ax, ...
            x + ancho_columnas(c)/2, ...
            y0 - alto_encabezado/2, ...
            nombres{c}, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontWeight', 'bold', ...
            'FontSize', 9, ...
            'Interpreter', 'none');

        x = x + ancho_columnas(c);
    end

    for i = 1:nFilas

        y = y0 - alto_encabezado - i*alto_fila;

        if mod(i, 2) == 0
            color_fila = color_fila_2;
        else
            color_fila = color_fila_1;
        end

        x = x0;

        for c = 1:nColumnas

            rectangle( ...
                ax, ...
                'Position', [x, y, ancho_columnas(c), alto_fila], ...
                'FaceColor', color_fila, ...
                'EdgeColor', [0.88 0.88 0.88], ...
                'LineWidth', 0.5);

            text( ...
                ax, ...
                x + ancho_columnas(c)/2, ...
                y + alto_fila/2, ...
                datos{i, c}, ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'middle', ...
                'FontSize', 9, ...
                'Interpreter', 'none');

            x = x + ancho_columnas(c);
        end
    end

    drawnow;

    print( ...
        fig, ...
        archivo_png, ...
        '-dpng', ...
        '-r300');
end

function datos = formatear_tabla_para_figura(tabla)

    nFilas = height(tabla);
    nColumnas = width(tabla);

    datos = cell(nFilas, nColumnas);
    nombres = tabla.Properties.VariableNames;

    for c = 1:nColumnas

        nombre = nombres{c};
        columna = tabla.(nombre);

        for i = 1:nFilas

            if iscell(columna)
                valor = columna{i};
            else
                valor = columna(i);
            end

            if isnumeric(valor)

                if isnan(valor)

                    texto = '';

                elseif contains(nombre, 'kHz', 'IgnoreCase', true)

                    texto = sprintf('%.4f', valor);

                elseif contains(nombre, 'Hz', 'IgnoreCase', true)

                    texto = sprintf('%.4f', valor);

                elseif contains(nombre, 'dB', 'IgnoreCase', true)

                    texto = sprintf('%.4f', valor);

                elseif contains(nombre, 'rep', 'IgnoreCase', true)

                    texto = sprintf('%.0f', valor);

                elseif contains(nombre, 'criterio', 'IgnoreCase', true)

                    texto = sprintf('%.1f', valor);

                else

                    texto = sprintf('%.4f', valor);
                end

            elseif islogical(valor)

                if valor
                    texto = 'Si';
                else
                    texto = 'No';
                end

            elseif isstring(valor)

                texto = char(valor);

            elseif ischar(valor)

                texto = valor;

            else

                texto = char(string(valor));
            end

            datos{i, c} = texto;
        end
    end
end

function nombre_limpio = limpiar_nombre(nombre)

    nombre_limpio = lower(nombre);
    nombre_limpio = strrep(nombre_limpio, ' ', '_');
    nombre_limpio = strrep(nombre_limpio, '/', '_');
    nombre_limpio = strrep(nombre_limpio, '\', '_');
    nombre_limpio = strrep(nombre_limpio, ':', '_');
end

function crear_figura_score_local_2D_terreno( ...
    f_per_kHz, score_per_dB, ...
    f_wel_kHz, score_wel_dB, ...
    f_mt_kHz, score_mt_dB, ...
    fc_ref_kHz, fc_promedio_kHz, ...
    fc_metodos_kHz, score_metodos_dB, ...
    metodos, criterio_dB, ...
    fmin_local_kHz, fmax_local_kHz, ...
    punto, led_actual, nombre_comparativa, carpeta_salida)

    fig = figure('Color','w','Position',[100 100 1600 820]);
    hold on;
    grid on;
    box on;

    idx_per = f_per_kHz >= fmin_local_kHz & f_per_kHz <= fmax_local_kHz;
    idx_wel = f_wel_kHz >= fmin_local_kHz & f_wel_kHz <= fmax_local_kHz;
    idx_mt  = f_mt_kHz  >= fmin_local_kHz & f_mt_kHz  <= fmax_local_kHz;

    plot(f_per_kHz(idx_per), score_per_dB(idx_per), ...
        'LineWidth', 0.85, ...
        'DisplayName','Periodograma');

    plot(f_wel_kHz(idx_wel), score_wel_dB(idx_wel), ...
        'LineWidth', 1.35, ...
        'DisplayName','Welch');

    plot(f_mt_kHz(idx_mt), score_mt_dB(idx_mt), ...
        'LineWidth', 1.35, ...
        'DisplayName','Multitaper');

    plot(fc_metodos_kHz, score_metodos_dB, 'ko', ...
        'MarkerSize', 8.5, ...
        'LineWidth', 1.6, ...
        'MarkerFaceColor','w', ...
        'DisplayName','Maximos locales');

    xline(fc_ref_kHz, '--', ...
        'LineWidth', 1.2, ...
        'HandleVisibility','off');

    yline(criterio_dB, '--', ...
        'LineWidth', 1.1, ...
        'HandleVisibility','off');

    yline(0, '--', ...
        'LineWidth', 1.0, ...
        'HandleVisibility','off');

    xlabel('Frecuencia [kHz]');
    ylabel('Score ON - OFF [dB]');

    title(sprintf('%s - %s: comparativa local de score por metodo', ...
        nombre_comparativa, led_actual), ...
        'Interpreter','none');

    xlim([fmin_local_kHz fmax_local_kHz]);

    y_min = min([score_per_dB(idx_per); score_wel_dB(idx_wel); score_mt_dB(idx_mt)], [], 'omitnan');
    y_max = max([score_per_dB(idx_per); score_wel_dB(idx_wel); score_mt_dB(idx_mt)], [], 'omitnan');

    if isempty(y_min) || isempty(y_max) || isnan(y_min) || isnan(y_max)
        ylim([-15 20]);
    else
        ylim([min(-6, y_min - 2), max(6, y_max + 4)]);
    end

    yl = ylim;

    text(fc_ref_kHz, ...
        yl(2) - 0.06*(yl(2)-yl(1)), ...
        sprintf('f_{ref} = %.3f kHz', fc_ref_kHz), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','top', ...
        'FontSize',9, ...
        'FontWeight','bold', ...
        'BackgroundColor','w', ...
        'Margin',0.6, ...
        'Interpreter','tex');

    text(fmax_local_kHz - 0.02*(fmax_local_kHz - fmin_local_kHz), ...
        criterio_dB + 0.35, ...
        sprintf('Criterio %.1f dB', criterio_dB), ...
        'HorizontalAlignment','right', ...
        'VerticalAlignment','bottom', ...
        'FontSize',9, ...
        'BackgroundColor','w', ...
        'Margin',0.5, ...
        'Interpreter','none');

    text(fmax_local_kHz - 0.02*(fmax_local_kHz - fmin_local_kHz), ...
        0 + 0.35, ...
        '0 dB', ...
        'HorizontalAlignment','right', ...
        'VerticalAlignment','bottom', ...
        'FontSize',9, ...
        'BackgroundColor','w', ...
        'Margin',0.5, ...
        'Interpreter','none');

    for i = 1:numel(metodos)

        if ~isfinite(fc_metodos_kHz(i)) || ~isfinite(score_metodos_dB(i))
            continue;
        end

        text(fc_metodos_kHz(i), score_metodos_dB(i) + 0.75, ...
            sprintf('%.3f kHz\n%.2f dB', ...
            fc_metodos_kHz(i), ...
            score_metodos_dB(i)), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','bottom', ...
            'FontSize',8, ...
            'BackgroundColor','w', ...
            'Margin',0.5, ...
            'Interpreter','none');
    end

    lgd = legend('Location','eastoutside');
    lgd.Box = 'on';

    nombre_led_archivo = strrep(led_actual, ' ', '_');

    archivo_png = fullfile(carpeta_salida, ...
        sprintf('figura_local_%s_%s_score_metodos_2D.png', ...
        nombre_comparativa, ...
        nombre_led_archivo));

    archivo_fig = fullfile(carpeta_salida, ...
        sprintf('figura_local_%s_%s_score_metodos_2D.fig', ...
        nombre_comparativa, ...
        nombre_led_archivo));

    exportgraphics(fig, archivo_png, 'Resolution', 300);
    savefig(fig, archivo_fig);
end

function crear_figura_score_cascada_2D_terreno( ...
    f_per_kHz, score_per_dB, ...
    f_wel_kHz, score_wel_dB, ...
    f_mt_kHz, score_mt_dB, ...
    fc_ref_kHz, fc_promedio_kHz, ...
    fc_metodos_kHz, score_metodos_dB, ...
    criterio_dB, ...
    fmin_local_kHz, fmax_local_kHz, ...
    punto, led_actual, nombre_comparativa, carpeta_salida)

    fig = figure('Color','w','Position',[100 100 1800 850]);
    hold on;
    grid on;
    box on;

    idx_per = f_per_kHz >= fmin_local_kHz & f_per_kHz <= fmax_local_kHz;
    idx_wel = f_wel_kHz >= fmin_local_kHz & f_wel_kHz <= fmax_local_kHz;
    idx_mt  = f_mt_kHz  >= fmin_local_kHz & f_mt_kHz  <= fmax_local_kHz;

    offset_periodograma = 0;
    offset_welch        = 32;
    offset_mt           = 65;

    plot(f_per_kHz(idx_per), score_per_dB(idx_per) + offset_periodograma, ...
        'LineWidth', 1.05, ...
        'DisplayName','Periodograma');

    plot(f_wel_kHz(idx_wel), score_wel_dB(idx_wel) + offset_welch, ...
        'LineWidth', 1.25, ...
        'DisplayName','Welch');

    plot(f_mt_kHz(idx_mt), score_mt_dB(idx_mt) + offset_mt, ...
        'LineWidth', 1.25, ...
        'DisplayName','Multitaper');

    yline(offset_periodograma, ':', 'HandleVisibility','off');
    yline(offset_welch, ':', 'HandleVisibility','off');
    yline(offset_mt, ':', 'HandleVisibility','off');

    yline(offset_periodograma + criterio_dB, '--', ...
        'LineWidth', 1.0, ...
        'HandleVisibility','off');

    yline(offset_welch + criterio_dB, '--', ...
        'LineWidth', 1.0, ...
        'HandleVisibility','off');

    yline(offset_mt + criterio_dB, '--', ...
        'LineWidth', 1.0, ...
        'HandleVisibility','off');

    plot(fc_metodos_kHz(1), score_metodos_dB(1) + offset_periodograma, ...
        'ko', ...
        'MarkerSize',9, ...
        'LineWidth',1.8, ...
        'MarkerFaceColor','w', ...
        'HandleVisibility','off');

    plot(fc_metodos_kHz(2), score_metodos_dB(2) + offset_welch, ...
        'ks', ...
        'MarkerSize',8.5, ...
        'LineWidth',1.7, ...
        'MarkerFaceColor','w', ...
        'HandleVisibility','off');

    plot(fc_metodos_kHz(3), score_metodos_dB(3) + offset_mt, ...
        'k*', ...
        'MarkerSize',11, ...
        'LineWidth',1.7, ...
        'HandleVisibility','off');

    text(fc_metodos_kHz(1), score_metodos_dB(1) + offset_periodograma + 1.5, ...
        sprintf('%.3f kHz\n%.2f dB', fc_metodos_kHz(1), score_metodos_dB(1)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',8, ...
        'BackgroundColor','w', ...
        'Margin',0.5, ...
        'Interpreter','none');

    text(fc_metodos_kHz(2), score_metodos_dB(2) + offset_welch + 1.5, ...
        sprintf('%.3f kHz\n%.2f dB', fc_metodos_kHz(2), score_metodos_dB(2)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',8, ...
        'BackgroundColor','w', ...
        'Margin',0.5, ...
        'Interpreter','none');

    text(fc_metodos_kHz(3), score_metodos_dB(3) + offset_mt + 1.5, ...
        sprintf('%.3f kHz\n%.2f dB', fc_metodos_kHz(3), score_metodos_dB(3)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',8, ...
        'BackgroundColor','w', ...
        'Margin',0.5, ...
        'Interpreter','none');

    xline(fc_ref_kHz, '--', ...
        'LineWidth',1.2, ...
        'HandleVisibility','off');

    xlabel('Frecuencia [kHz]');
    ylabel('Score ON-OFF desplazado [dB]');

    title(sprintf('%s - %s: cascada de score ON-OFF por metodo', ...
        nombre_comparativa, led_actual), ...
        'Interpreter','none');

    xlim([fmin_local_kHz fmax_local_kHz]);

    y_min = min(score_per_dB(idx_per), [], 'omitnan') - 5;
    y_max = offset_mt + max(score_mt_dB(idx_mt), [], 'omitnan') + 8;

    if isempty(y_min) || isempty(y_max) || isnan(y_min) || isnan(y_max)
        ylim([-15 80]);
    else
        ylim([y_min y_max]);
    end

    yl = ylim;

    text(fc_ref_kHz, ...
        yl(2) - 0.06*(yl(2)-yl(1)), ...
        sprintf('f_{ref} = %.3f kHz', fc_ref_kHz), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','top', ...
        'FontSize',9, ...
        'FontWeight','bold', ...
        'BackgroundColor','w', ...
        'Margin',0.6, ...
        'Interpreter','tex');

    x_texto = fmin_local_kHz + 0.02*(fmax_local_kHz - fmin_local_kHz);

    text(x_texto, offset_periodograma + 1.3, 'Periodograma', ...
        'FontWeight','bold', ...
        'FontSize',11, ...
        'BackgroundColor','w', ...
        'Margin',0.5, ...
        'Interpreter','none');

    text(x_texto, offset_welch + 1.3, 'Welch', ...
        'FontWeight','bold', ...
        'FontSize',11, ...
        'BackgroundColor','w', ...
        'Margin',0.5, ...
        'Interpreter','none');

    text(x_texto, offset_mt + 1.3, 'Multitaper', ...
        'FontWeight','bold', ...
        'FontSize',11, ...
        'BackgroundColor','w', ...
        'Margin',0.5, ...
        'Interpreter','none');

    lgd = legend('Location','eastoutside');
    lgd.Box = 'on';

    nombre_led_archivo = strrep(led_actual, ' ', '_');

    archivo_png = fullfile(carpeta_salida, ...
        sprintf('figura_cascada_%s_%s_score_metodos_2D.png', ...
        nombre_comparativa, ...
        nombre_led_archivo));

    archivo_fig = fullfile(carpeta_salida, ...
        sprintf('figura_cascada_%s_%s_score_metodos_2D.fig', ...
        nombre_comparativa, ...
        nombre_led_archivo));

    exportgraphics(fig, archivo_png, 'Resolution', 300);
    savefig(fig, archivo_fig);
end