%% T08_P3_welch_terreno.m
% Analisis Welch - P3 / LED terreno 3
%
% Antes de ejecutar este script, modificar las variables carpeta_ON
% y carpeta_OFF con las rutas locales donde se encuentran los archivos .csv
% de la medicion correspondiente.
%
% La carpeta_ON debe contener los archivos ON_P3_REP*.csv indicados
% en la lista archivos_ON.
% La carpeta_OFF debe contener los archivos OFF comunes indicados
% en la lista archivos_OFF.
%
% Ejemplo:
% carpeta_ON  = 'C:\Users\NombreUsuario\Desktop\Terreno_ON_M3';
% carpeta_OFF = 'C:\Users\NombreUsuario\Desktop\Terreno_OFF';

clear;
clc;
close all;

%% 1. Configuracion

carpeta_base = 'C:\Users\berni\OneDrive\Escritorio\Modulo Prof\Archivos Tesis\Toma de Datos\Pruebas en terreno';

carpeta_ON = fullfile(carpeta_base, 'Terreno_ON_M3');
carpeta_OFF = fullfile(carpeta_base, 'Terreno_OFF');

carpeta_salida = fullfile( ...
    carpeta_base, ...
    'Resultados_Terreno', ...
    'P3_LED3', ...
    '02_Welch');

if ~exist(carpeta_salida, 'dir')
    mkdir(carpeta_salida);
end

nombre_punto = "P3";
nombre_led = "LED terreno 3";
nombre_metodo = "Welch";

nRep = 3;

archivos_ON = cell(nRep, 1);
archivos_OFF = cell(nRep, 1);

for r = 1:nRep

    archivos_ON{r} = fullfile( ...
        carpeta_ON, ...
        sprintf('ON_P3_REP%d.csv', r));

    archivos_OFF{r} = fullfile( ...
        carpeta_OFF, ...
        sprintf('OFF_REP%d.csv', r));
end

% Banda de analisis
fmin_Hz = 30e3;
fmax_Hz = 90e3;

% Frecuencia detectada previamente mediante Periodograma P3
f_ref_periodograma_Hz = 57.6580e3;

% Confirmacion local alrededor de la frecuencia del Periodograma
usar_confirmacion_local = true;
ventana_confirmacion_Hz = 350;

% Criterios de deteccion
criterio_dB = 3;
umbral_repeticiones = nRep;

% Busqueda de candidatos
num_candidatos = 7;
distancia_minima_Hz = 50;
ventana_local_Hz = 200;

% Frecuencia de muestreo configurada en el osciloscopio
Fs_configurada_Hz = 50e6;

% Parametros Welch
Nseg_objetivo = 2^20;
fraccion_solapamiento = 0.50;

% Rango amplio para graficas
fmax_amplio_Hz = 5e6;

fprintf('\n============================================================\n');
fprintf('PUNTO 3 / LED TERRENO 3 - WELCH CORREGIDO\n');
fprintf('============================================================\n');
fprintf('Carpeta base:\n%s\n\n', carpeta_base);
fprintf('Carpeta ON:\n%s\n\n', carpeta_ON);
fprintf('Carpeta OFF:\n%s\n\n', carpeta_OFF);
fprintf('Carpeta salida:\n%s\n\n', carpeta_salida);
fprintf('Fs configurada: %.6f MSa/s\n', Fs_configurada_Hz/1e6);
fprintf('Nseg objetivo: %d muestras\n', Nseg_objetivo);
fprintf('Solapamiento: %.1f %%\n', fraccion_solapamiento*100);
fprintf('Referencia Periodograma P3: %.4f kHz\n', f_ref_periodograma_Hz/1e3);
fprintf('Ventana confirmacion local: +/- %.3f kHz\n', ventana_confirmacion_Hz/1e3);

%% 2. Verificacion de archivos

for r = 1:nRep

    if ~exist(archivos_ON{r}, 'file')

        error( ...
            'No existe el archivo ON de la repeticion %d:\n%s', ...
            r, ...
            archivos_ON{r});
    end

    if ~exist(archivos_OFF{r}, 'file')

        error( ...
            'No existe el archivo OFF de la repeticion %d:\n%s', ...
            r, ...
            archivos_OFF{r});
    end
end

fprintf('\nArchivos verificados correctamente.\n');

%% 3. Lectura y calculo Welch por repeticion

f_ref_Hz = [];

PSD_ON_mat_dB = [];
PSD_OFF_mat_dB = [];

info_reps = table();

for r = 1:nRep

    fprintf('\n------------------------------------------------------------\n');
    fprintf('Repeticion %d/%d\n', r, nRep);
    fprintf('ON : %s\n', archivos_ON{r});
    fprintf('OFF: %s\n', archivos_OFF{r});

    [tON, xON] = leer_csv_rigol_terreno(archivos_ON{r}, Fs_configurada_Hz);
    [tOFF, xOFF] = leer_csv_rigol_terreno(archivos_OFF{r}, Fs_configurada_Hz);

    N_ON_original = numel(xON);
    N_OFF_original = numel(xOFF);

    N_usado = min(N_ON_original, N_OFF_original);

    if N_usado < Nseg_objetivo

        error( ...
            ['La repeticion %d contiene menos muestras que el segmento ', ...
             'Welch configurado. Muestras disponibles: %d.'], ...
            r, ...
            N_usado);
    end

    tON = tON(1:N_usado);
    xON = xON(1:N_usado);

    tOFF = tOFF(1:N_usado);
    xOFF = xOFF(1:N_usado);

    duracion_ON_s = tON(end) - tON(1);
    duracion_OFF_s = tOFF(end) - tOFF(1);

    if duracion_ON_s <= 0 || duracion_OFF_s <= 0

        warning( ...
            ['No se detecto una duracion valida desde la columna de tiempo ', ...
             'en la repeticion %d. Se reconstruye el tiempo con Fs configurada.'], ...
            r);

        tON = (0:N_usado-1)'/Fs_configurada_Hz;
        tOFF = (0:N_usado-1)'/Fs_configurada_Hz;

        duracion_ON_s = tON(end) - tON(1);
        duracion_OFF_s = tOFF(end) - tOFF(1);
    end

    Fs_ON_duracion_Hz = (N_usado - 1) / duracion_ON_s;
    Fs_OFF_duracion_Hz = (N_usado - 1) / duracion_OFF_s;

    error_Fs_ON_pct = ...
        abs(Fs_ON_duracion_Hz - Fs_configurada_Hz) / ...
        Fs_configurada_Hz * 100;

    error_Fs_OFF_pct = ...
        abs(Fs_OFF_duracion_Hz - Fs_configurada_Hz) / ...
        Fs_configurada_Hz * 100;

    if error_Fs_ON_pct > 5

        warning( ...
            ['La Fs estimada por duracion para ON difiere mas de 5 %% ', ...
             'respecto de 50 MSa/s en la repeticion %d. ', ...
             'Se utilizara Fs configurada.'], ...
            r);
    end

    if error_Fs_OFF_pct > 5

        warning( ...
            ['La Fs estimada por duracion para OFF difiere mas de 5 %% ', ...
             'respecto de 50 MSa/s en la repeticion %d. ', ...
             'Se utilizara Fs configurada.'], ...
            r);
    end

    Fs_usada_Hz = Fs_configurada_Hz;

    xON = xON - mean(xON, 'omitnan');
    xOFF = xOFF - mean(xOFF, 'omitnan');

    xON(~isfinite(xON)) = 0;
    xOFF(~isfinite(xOFF)) = 0;

    Nseg = min(Nseg_objetivo, N_usado);

    noverlap = floor(fraccion_solapamiento*Nseg);

    if noverlap >= Nseg
        noverlap = Nseg - 1;
    end

    nfft = Nseg;

    ventana_welch = hann(Nseg, 'periodic');

    salto_segmento = Nseg - noverlap;

    num_segmentos = ...
        1 + floor((N_usado - Nseg)/salto_segmento);

    df_Hz = Fs_usada_Hz/nfft;

    fprintf('N ON original       = %d muestras\n', N_ON_original);
    fprintf('N OFF original      = %d muestras\n', N_OFF_original);
    fprintf('N usado             = %d muestras\n', N_usado);
    fprintf('Duracion ON         = %.9f s\n', duracion_ON_s);
    fprintf('Duracion OFF        = %.9f s\n', duracion_OFF_s);
    fprintf('Fs ON por duracion  = %.6f MSa/s\n', Fs_ON_duracion_Hz/1e6);
    fprintf('Fs OFF por duracion = %.6f MSa/s\n', Fs_OFF_duracion_Hz/1e6);
    fprintf('Fs usada            = %.6f MSa/s\n', Fs_usada_Hz/1e6);
    fprintf('Nseg                = %d muestras\n', Nseg);
    fprintf('noverlap            = %d muestras\n', noverlap);
    fprintf('Solapamiento        = %.2f %%\n', 100*noverlap/Nseg);
    fprintf('Numero de segmentos = %d\n', num_segmentos);
    fprintf('nfft                = %d\n', nfft);
    fprintf('df aproximada       = %.6f Hz\n', df_Hz);

    [Pxx_ON, fON_Hz] = pwelch( ...
        xON, ...
        ventana_welch, ...
        noverlap, ...
        nfft, ...
        Fs_usada_Hz, ...
        'onesided');

    [Pxx_OFF, fOFF_Hz] = pwelch( ...
        xOFF, ...
        ventana_welch, ...
        noverlap, ...
        nfft, ...
        Fs_usada_Hz, ...
        'onesided');

    fON_Hz = fON_Hz(:);
    fOFF_Hz = fOFF_Hz(:);

    PSD_ON_dB = 10*log10(Pxx_ON(:) + eps);
    PSD_OFF_dB = 10*log10(Pxx_OFF(:) + eps);

    if numel(fON_Hz) ~= numel(fOFF_Hz) || ...
            max(abs(fON_Hz - fOFF_Hz)) > 1e-9

        error( ...
            'Las grillas de frecuencia ON y OFF no coinciden en la repeticion %d.', ...
            r);
    end

    if max(fON_Hz) < fmax_Hz

        error( ...
            'La grilla Welch no cubre la banda de 30 a 90 kHz.');
    end

    if isempty(f_ref_Hz)

        f_ref_Hz = fON_Hz;

        PSD_ON_mat_dB = nan(numel(f_ref_Hz), nRep);
        PSD_OFF_mat_dB = nan(numel(f_ref_Hz), nRep);
    end

    PSD_ON_mat_dB(:, r) = interp1( ...
        fON_Hz, ...
        PSD_ON_dB, ...
        f_ref_Hz, ...
        'linear', ...
        NaN);

    PSD_OFF_mat_dB(:, r) = interp1( ...
        fOFF_Hz, ...
        PSD_OFF_dB, ...
        f_ref_Hz, ...
        'linear', ...
        NaN);

    info_reps = [info_reps; crear_fila_info( ...
        string(archivos_ON{r}), ...
        "ON", ...
        r, ...
        N_ON_original, ...
        N_usado, ...
        duracion_ON_s, ...
        Fs_ON_duracion_Hz, ...
        Fs_usada_Hz, ...
        error_Fs_ON_pct, ...
        Nseg, ...
        noverlap, ...
        num_segmentos, ...
        nfft, ...
        df_Hz)];

    info_reps = [info_reps; crear_fila_info( ...
        string(archivos_OFF{r}), ...
        "OFF", ...
        r, ...
        N_OFF_original, ...
        N_usado, ...
        duracion_OFF_s, ...
        Fs_OFF_duracion_Hz, ...
        Fs_usada_Hz, ...
        error_Fs_OFF_pct, ...
        Nseg, ...
        noverlap, ...
        num_segmentos, ...
        nfft, ...
        df_Hz)];

    clear tON tOFF xON xOFF
    clear Pxx_ON Pxx_OFF PSD_ON_dB PSD_OFF_dB
end

%% 4. Promedios y score ON-OFF

PSD_ON_prom_dB = mean(PSD_ON_mat_dB, 2, 'omitnan');
PSD_OFF_prom_dB = mean(PSD_OFF_mat_dB, 2, 'omitnan');

score_rep_dB = PSD_ON_mat_dB - PSD_OFF_prom_dB;
score_prom_dB = mean(score_rep_dB, 2, 'omitnan');

f_ref_Hz = f_ref_Hz(:);
PSD_ON_prom_dB = PSD_ON_prom_dB(:);
PSD_OFF_prom_dB = PSD_OFF_prom_dB(:);
score_prom_dB = score_prom_dB(:);

%% 5. Preparar banda de analisis

idx_banda = ...
    f_ref_Hz >= fmin_Hz & ...
    f_ref_Hz <= fmax_Hz;

if ~any(idx_banda)

    error( ...
        'No existen puntos dentro de la banda de 30 a 90 kHz.');
end

f_banda_Hz = f_ref_Hz(idx_banda);

PSD_ON_banda_dB = PSD_ON_prom_dB(idx_banda);
PSD_OFF_banda_dB = PSD_OFF_prom_dB(idx_banda);
score_banda_dB = score_prom_dB(idx_banda);

PSD_ON_banda_reps_dB = PSD_ON_mat_dB(idx_banda, :);
PSD_OFF_banda_reps_dB = PSD_OFF_mat_dB(idx_banda, :);
score_banda_reps_dB = score_rep_dB(idx_banda, :);

idx_validos = ...
    isfinite(f_banda_Hz) & ...
    isfinite(PSD_ON_banda_dB) & ...
    isfinite(PSD_OFF_banda_dB) & ...
    isfinite(score_banda_dB);

f_banda_Hz = f_banda_Hz(idx_validos);

PSD_ON_banda_dB = PSD_ON_banda_dB(idx_validos);
PSD_OFF_banda_dB = PSD_OFF_banda_dB(idx_validos);
score_banda_dB = score_banda_dB(idx_validos);

PSD_ON_banda_reps_dB = ...
    PSD_ON_banda_reps_dB(idx_validos, :);

PSD_OFF_banda_reps_dB = ...
    PSD_OFF_banda_reps_dB(idx_validos, :);

score_banda_reps_dB = ...
    score_banda_reps_dB(idx_validos, :);

f_banda_kHz = f_banda_Hz/1e3;

%% 6. Busqueda de candidatos

if usar_confirmacion_local

    idx_busqueda = ...
        f_banda_Hz >= f_ref_periodograma_Hz - ventana_confirmacion_Hz & ...
        f_banda_Hz <= f_ref_periodograma_Hz + ventana_confirmacion_Hz;

    if ~any(idx_busqueda)

        error( ...
            'No hay datos dentro de la ventana local alrededor de %.4f kHz.', ...
            f_ref_periodograma_Hz/1e3);
    end

else

    idx_busqueda = true(size(f_banda_Hz));
end

f_busqueda_Hz = f_banda_Hz(idx_busqueda);
score_busqueda_dB = score_banda_dB(idx_busqueda);

[score_max_busqueda_dB, idx_max_busqueda] = max(score_busqueda_dB);
f_max_busqueda_Hz = f_busqueda_Hz(idx_max_busqueda);

fprintf('\n============================================================\n');
fprintf('MAXIMO WELCH EN ZONA DE BUSQUEDA\n');
fprintf('============================================================\n');
fprintf('Frecuencia = %.3f Hz = %.4f kHz\n', ...
    f_max_busqueda_Hz, ...
    f_max_busqueda_Hz/1e3);
fprintf('Score      = %.4f dB\n', score_max_busqueda_dB);

[picos_dB, frecuencias_picos_Hz] = findpeaks( ...
    score_busqueda_dB, ...
    f_busqueda_Hz, ...
    'MinPeakDistance', ...
    distancia_minima_Hz);

idx_positivos = picos_dB > 0;

picos_dB = picos_dB(idx_positivos);

frecuencias_picos_Hz = ...
    frecuencias_picos_Hz(idx_positivos);

if isempty(picos_dB)

    warning( ...
        'No se encontraron picos positivos. Se utilizara el maximo de la zona de busqueda.');

    picos_dB = score_max_busqueda_dB;
    frecuencias_picos_Hz = f_max_busqueda_Hz;
end

[picos_dB, idx_orden] = sort(picos_dB, 'descend');

frecuencias_picos_Hz = ...
    frecuencias_picos_Hz(idx_orden);

num_candidatos_usados = ...
    min(num_candidatos, numel(picos_dB));

score_peak_dB = ...
    picos_dB(1:num_candidatos_usados);

fc_candidatas_Hz = ...
    frecuencias_picos_Hz(1:num_candidatos_usados);

nCandidatos = numel(fc_candidatas_Hz);

%% 7. Analisis local y repetibilidad

score_local_dB = nan(nCandidatos, 1);
f_local_Hz = nan(nCandidatos, 1);

ON_dB = nan(nCandidatos, 1);
OFF_dB = nan(nCandidatos, 1);

rep_positivas = zeros(nCandidatos, 1);
rep_3dB = zeros(nCandidatos, 1);

for i = 1:nCandidatos

    fc_Hz = fc_candidatas_Hz(i);

    idx_local = ...
        f_ref_Hz >= fc_Hz - ventana_local_Hz & ...
        f_ref_Hz <= fc_Hz + ventana_local_Hz;

    f_local_temp_Hz = f_ref_Hz(idx_local);
    score_local_temp_dB = score_prom_dB(idx_local);

    if isempty(score_local_temp_dB)
        continue;
    end

    [score_local_dB(i), idx_max_local] = ...
        max(score_local_temp_dB);

    f_local_Hz(i) = ...
        f_local_temp_Hz(idx_max_local);

    ON_dB(i) = interp1( ...
        f_ref_Hz, ...
        PSD_ON_prom_dB, ...
        f_local_Hz(i), ...
        'linear', ...
        NaN);

    OFF_dB(i) = interp1( ...
        f_ref_Hz, ...
        PSD_OFF_prom_dB, ...
        f_local_Hz(i), ...
        'linear', ...
        NaN);

    for r = 1:nRep

        score_rep_local_dB = interp1( ...
            f_ref_Hz, ...
            score_rep_dB(:, r), ...
            f_local_Hz(i), ...
            'linear', ...
            NaN);

        if isfinite(score_rep_local_dB)

            if score_rep_local_dB > 0
                rep_positivas(i) = rep_positivas(i) + 1;
            end

            if score_rep_local_dB >= criterio_dB
                rep_3dB(i) = rep_3dB(i) + 1;
            end
        end
    end
end

supera_3dB = score_local_dB >= criterio_dB & rep_3dB >= umbral_repeticiones;

tabla_candidatos = table( ...
    fc_candidatas_Hz, ...
    fc_candidatas_Hz/1e3, ...
    score_peak_dB, ...
    f_local_Hz, ...
    f_local_Hz/1e3, ...
    score_local_dB, ...
    ON_dB, ...
    OFF_dB, ...
    rep_positivas, ...
    rep_3dB, ...
    repmat(nRep, nCandidatos, 1), ...
    supera_3dB, ...
    'VariableNames', { ...
    'fc_Hz', ...
    'fc_kHz', ...
    'score_peak_dB', ...
    'f_local_Hz', ...
    'f_local_kHz', ...
    'score_local_dB', ...
    'ON_dB', ...
    'OFF_dB', ...
    'rep_positivas', ...
    'rep_3dB', ...
    'rep_totales', ...
    'supera_3dB'});

tabla_candidatos = sortrows( ...
    tabla_candidatos, ...
    'score_local_dB', ...
    'descend');

%% 8. Seleccion de frecuencia principal

idx_validos_principal = ...
    tabla_candidatos.score_local_dB >= criterio_dB & ...
    tabla_candidatos.rep_positivas == tabla_candidatos.rep_totales & ...
    tabla_candidatos.rep_3dB >= umbral_repeticiones;

if any(idx_validos_principal)

    tabla_validos = ...
        tabla_candidatos(idx_validos_principal, :);

    [~, idx_mejor] = ...
        max(tabla_validos.score_local_dB);

    fc_principal_Hz = ...
        tabla_validos.f_local_Hz(idx_mejor);

    score_principal_dB = ...
        tabla_validos.score_local_dB(idx_mejor);

    ON_principal_dB = ...
        tabla_validos.ON_dB(idx_mejor);

    OFF_principal_dB = ...
        tabla_validos.OFF_dB(idx_mejor);

    rep_positivas_principal = ...
        tabla_validos.rep_positivas(idx_mejor);

    rep_3dB_principal = ...
        tabla_validos.rep_3dB(idx_mejor);

else

    warning( ...
        ['No se encontraron candidatos con score >= %.1f dB y ', ...
         'repetibilidad completa. Se utilizara el mayor score dentro de la zona de busqueda.'], ...
        criterio_dB);

    fc_principal_Hz = ...
        tabla_candidatos.f_local_Hz(1);

    score_principal_dB = ...
        tabla_candidatos.score_local_dB(1);

    ON_principal_dB = ...
        tabla_candidatos.ON_dB(1);

    OFF_principal_dB = ...
        tabla_candidatos.OFF_dB(1);

    rep_positivas_principal = ...
        tabla_candidatos.rep_positivas(1);

    rep_3dB_principal = ...
        tabla_candidatos.rep_3dB(1);
end

fc_principal_kHz = fc_principal_Hz/1e3;

if score_principal_dB >= criterio_dB && ...
        rep_positivas_principal >= umbral_repeticiones && ...
        rep_3dB_principal >= umbral_repeticiones

    supera_criterio = "Si";

else

    supera_criterio = "No";
end

fprintf('\n============================================================\n');
fprintf('RESULTADO WELCH CORREGIDO\n');
fprintf('============================================================\n');
fprintf('Frecuencia principal = %.3f Hz = %.4f kHz\n', ...
    fc_principal_Hz, ...
    fc_principal_kHz);
fprintf('Score principal      = %.4f dB\n', ...
    score_principal_dB);
fprintf('Repeticiones > 0 dB  = %d/%d\n', ...
    rep_positivas_principal, ...
    nRep);
fprintf('Repeticiones >= 3 dB = %d/%d\n', ...
    rep_3dB_principal, ...
    nRep);

tabla_resultado = table( ...
    nombre_punto, ...
    nombre_led, ...
    nombre_metodo, ...
    f_ref_periodograma_Hz/1e3, ...
    ventana_confirmacion_Hz/1e3, ...
    fc_principal_kHz, ...
    score_principal_dB, ...
    ON_principal_dB, ...
    OFF_principal_dB, ...
    rep_positivas_principal, ...
    rep_3dB_principal, ...
    nRep, ...
    criterio_dB, ...
    supera_criterio, ...
    'VariableNames', { ...
    'punto', ...
    'led', ...
    'metodo', ...
    'f_ref_kHz', ...
    'ventana_kHz', ...
    'fc_detectada_kHz', ...
    'score_dB', ...
    'ON_prom_dB', ...
    'OFF_prom_dB', ...
    'rep_positivas', ...
    'rep_3dB', ...
    'rep_totales', ...
    'criterio_dB', ...
    'supera_3dB'});

tabla_score = table( ...
    f_banda_kHz(:), ...
    PSD_ON_banda_dB(:), ...
    PSD_OFF_banda_dB(:), ...
    score_banda_dB(:), ...
    'VariableNames', { ...
    'f_kHz', ...
    'PSD_ON_prom_dB', ...
    'PSD_OFF_prom_dB', ...
    'score_prom_dB'});

disp(tabla_resultado);
disp(tabla_candidatos);

%% 9. Guardar resultados

writetable( ...
    tabla_resultado, ...
    fullfile( ...
        carpeta_salida, ...
        'tabla_resultado_P3_welch.csv'));

writetable( ...
    tabla_candidatos, ...
    fullfile( ...
        carpeta_salida, ...
        'tabla_candidatos_P3_welch.csv'));

writetable( ...
    tabla_score, ...
    fullfile( ...
        carpeta_salida, ...
        'score_promedio_P3_welch.csv'));

writetable( ...
    info_reps, ...
    fullfile( ...
        carpeta_salida, ...
        'info_repeticiones_P3_welch.csv'));

%% 10. Tabla de candidatos como figura

tabla_figura = tabla_candidatos;

tabla_figura.fc_Hz = [];
tabla_figura.f_local_Hz = [];

tabla_figura.Properties.VariableNames = { ...
    'fc_kHz', ...
    'score_peak', ...
    'f_local_kHz', ...
    'score_local', ...
    'ON_dB', ...
    'OFF_dB', ...
    'rep_positivas', ...
    'rep_3dB', ...
    'rep_totales', ...
    'supera_3dB'};

guardar_tabla_como_figura( ...
    tabla_figura, ...
    'TABLA DE CANDIDATOS WELCH P3 - LED TERRENO 3', ...
    fullfile( ...
        carpeta_salida, ...
        '05_P3_welch_tabla_candidatos.png'), ...
    fullfile( ...
        carpeta_salida, ...
        '05_P3_welch_tabla_candidatos.fig'));

%% 11. Score ON-OFF

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1500 850]);

plot( ...
    f_banda_kHz, ...
    score_banda_dB, ...
    'LineWidth', 1.5);

hold on;
grid on;
box on;

yline( ...
    0, ...
    '--', ...
    '0 dB', ...
    'HandleVisibility', 'off');

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'HandleVisibility', 'off');

xline( ...
    f_ref_periodograma_Hz/1e3, ...
    '--', ...
    sprintf('Ref %.3f kHz', f_ref_periodograma_Hz/1e3), ...
    'LineWidth', 1.2, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

xline( ...
    fc_principal_kHz, ...
    ':', ...
    sprintf('Welch %.3f kHz', fc_principal_kHz), ...
    'LineWidth', 1.3, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');

title( ...
    'P3 / LED terreno 3 - Welch: score ON-OFF', ...
    'Interpreter', 'none');

xlim([fmin_Hz fmax_Hz]/1e3);
ylim([-3 4]);

guardar_figura( ...
    fig, ...
    carpeta_salida, ...
    '01_P3_welch_score_ON_OFF');

%% 12. Barras de candidatos

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1200 700]);

x = 1:height(tabla_candidatos);

bar( ...
    x, ...
    tabla_candidatos.score_local_dB, ...
    0.65);

hold on;
grid on;
box on;

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'LineWidth', 1.1, ...
    'LabelHorizontalAlignment', 'right', ...
    'HandleVisibility', 'off');

[~, idx_principal_barra] = min( ...
    abs(tabla_candidatos.f_local_Hz - fc_principal_Hz));

plot( ...
    idx_principal_barra, ...
    tabla_candidatos.score_local_dB(idx_principal_barra) + 0.9, ...
    'kp', ...
    'MarkerSize', 16, ...
    'LineWidth', 2, ...
    'DisplayName', 'Candidato principal');

xlabel('Frecuencia candidata [kHz]');
ylabel('Score local ON-OFF [dB]');

title( ...
    'P3 / LED terreno 3 - Welch: candidatos locales', ...
    'Interpreter', 'none');

xticks(x);

xticklabels( ...
    compose('%.3f', tabla_candidatos.f_local_kHz));

xtickangle(45);

for i = 1:height(tabla_candidatos)

    texto_barra = sprintf( ...
        '%.2f dB\n%d/%d', ...
        tabla_candidatos.score_local_dB(i), ...
        tabla_candidatos.rep_positivas(i), ...
        tabla_candidatos.rep_totales(i));

    if i == idx_principal_barra

        y_texto = ...
            tabla_candidatos.score_local_dB(i) + 1.45;

    else

        y_texto = ...
            tabla_candidatos.score_local_dB(i) + 0.55;
    end

    text( ...
        x(i), ...
        y_texto, ...
        texto_barra, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'FontSize', 9);
end

ylim([ ...
    min(0, min(tabla_candidatos.score_local_dB) - 1), ...
    max(criterio_dB + 1.5, max(tabla_candidatos.score_local_dB) + 3.2)]);

legend( ...
    {'Score local ON-OFF', 'Candidato principal'}, ...
    'Location', 'best');

guardar_figura( ...
    fig, ...
    carpeta_salida, ...
    '02_P3_welch_barras_candidatos');

%% 13. PSD promedio ON/OFF

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1500 850]);

plot( ...
    f_banda_kHz, ...
    PSD_ON_banda_dB, ...
    'LineWidth', 1.5);

hold on;

plot( ...
    f_banda_kHz, ...
    PSD_OFF_banda_dB, ...
    'LineWidth', 1.5);

xline( ...
    f_ref_periodograma_Hz/1e3, ...
    '--', ...
    sprintf('Ref %.3f kHz', f_ref_periodograma_Hz/1e3), ...
    'LineWidth', 1.2, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

xline( ...
    fc_principal_kHz, ...
    ':', ...
    sprintf('Welch %.3f kHz', fc_principal_kHz), ...
    'LineWidth', 1.3, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('PSD Welch [dB/Hz]');

title( ...
    'P3 / LED terreno 3 - Welch: PSD promedio ON/OFF', ...
    'Interpreter', 'none');

legend( ...
    'ON P3 promedio', ...
    'OFF promedio', ...
    'Location', 'best');

xlim([fmin_Hz fmax_Hz]/1e3);
ylim([-138 -130]);

guardar_figura( ...
    fig, ...
    carpeta_salida, ...
    '03_P3_welch_PSD_promedio_ON_OFF');

%% 14. Score por repeticion

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1500 850]);

hold on;

for r = 1:nRep

    plot( ...
        f_banda_kHz, ...
        score_banda_reps_dB(:, r), ...
        'LineWidth', 0.9);
end

plot( ...
    f_banda_kHz, ...
    score_banda_dB, ...
    'k', ...
    'LineWidth', 1.8);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');

title( ...
    'P3 / LED terreno 3 - Welch: score por repeticion', ...
    'Interpreter', 'none');

leyenda = cell(nRep + 1, 1);

for r = 1:nRep
    leyenda{r} = sprintf('REP%d', r);
end

leyenda{nRep + 1} = 'Promedio';

legend( ...
    leyenda, ...
    'Location', 'best', ...
    'AutoUpdate', 'off');

yline( ...
    0, ...
    '--', ...
    '0 dB', ...
    'HandleVisibility', 'off');

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'HandleVisibility', 'off');

xline( ...
    f_ref_periodograma_Hz/1e3, ...
    '--', ...
    'LineWidth', 1.2, ...
    'HandleVisibility', 'off');

xline( ...
    fc_principal_kHz, ...
    ':', ...
    'LineWidth', 1.2, ...
    'HandleVisibility', 'off');

xlim([fmin_Hz fmax_Hz]/1e3);
ylim([-6 6]);

guardar_figura( ...
    fig, ...
    carpeta_salida, ...
    '04_P3_welch_score_repeticiones');

%% 15. Rango amplio

fmax_amplio_usado_Hz = ...
    min(fmax_amplio_Hz, max(f_ref_Hz));

idx_amplio = ...
    f_ref_Hz >= 0 & ...
    f_ref_Hz <= fmax_amplio_usado_Hz;

[f_amplio_MHz, PSD_ON_amplio_dB, PSD_OFF_amplio_dB] = ...
    reducir_puntos_grafico( ...
        f_ref_Hz(idx_amplio)/1e6, ...
        PSD_ON_prom_dB(idx_amplio), ...
        PSD_OFF_prom_dB(idx_amplio), ...
        80000);

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1200 700]);

plot( ...
    f_amplio_MHz, ...
    PSD_ON_amplio_dB, ...
    'LineWidth', 1.2);

hold on;

plot( ...
    f_amplio_MHz, ...
    PSD_OFF_amplio_dB, ...
    'LineWidth', 1.2);

grid on;
box on;

xlabel('Frecuencia [MHz]');
ylabel('PSD Welch [dB/Hz]');

title( ...
    'P3 / LED terreno 3 - Welch: PSD promedio ON/OFF, rango amplio', ...
    'Interpreter', 'none');

legend( ...
    'LED encendido', ...
    'LED apagado', ...
    'Location', 'best');

xlim([0 fmax_amplio_usado_Hz/1e6]);
ylim([-150 -70]);

guardar_figura( ...
    fig, ...
    carpeta_salida, ...
    '06_P3_welch_ON_OFF_rango_amplio');

%% 16. Repeticiones ON

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1200 700]);

plot( ...
    f_banda_kHz, ...
    PSD_ON_banda_reps_dB, ...
    'LineWidth', 1.0);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('PSD Welch [dB/Hz]');

title( ...
    'P3 / LED terreno 3 - Welch: repeticiones ON en banda de analisis', ...
    'Interpreter', 'none');

legend( ...
    compose('ON P3 rep %d', 1:nRep), ...
    'Location', 'best');

xlim([fmin_Hz fmax_Hz]/1e3);
ylim([-140 -130]);

guardar_figura( ...
    fig, ...
    carpeta_salida, ...
    '07_P3_welch_repeticiones_ON_30_90kHz');

%% 17. Repeticiones OFF

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1200 700]);

plot( ...
    f_banda_kHz, ...
    PSD_OFF_banda_reps_dB, ...
    'LineWidth', 1.0);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('PSD Welch [dB/Hz]');

title( ...
    'P3 / LED terreno 3 - Welch: repeticiones OFF en banda de analisis', ...
    'Interpreter', 'none');

legend( ...
    compose('OFF rep %d', 1:nRep), ...
    'Location', 'best');

xlim([fmin_Hz fmax_Hz]/1e3);
ylim([-140 -130]);

guardar_figura( ...
    fig, ...
    carpeta_salida, ...
    '08_P3_welch_repeticiones_OFF_30_90kHz');

%% 18. Zona local

ancho_zoom_kHz = 1.0;

idx_zoom = ...
    f_banda_kHz >= f_ref_periodograma_Hz/1e3 - ancho_zoom_kHz & ...
    f_banda_kHz <= f_ref_periodograma_Hz/1e3 + ancho_zoom_kHz;

fig = figure( ...
    'Color', 'w', ...
    'Position', [100 100 1500 850]);

plot( ...
    f_banda_kHz(idx_zoom), ...
    score_banda_dB(idx_zoom), ...
    'LineWidth', 1.5);

hold on;
grid on;
box on;

yline( ...
    0, ...
    '--', ...
    '0 dB', ...
    'HandleVisibility', 'off');

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'HandleVisibility', 'off');

xline( ...
    f_ref_periodograma_Hz/1e3, ...
    '--', ...
    sprintf('Ref %.3f kHz', f_ref_periodograma_Hz/1e3), ...
    'LineWidth', 1.2, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

xline( ...
    fc_principal_kHz, ...
    ':', ...
    sprintf('Welch %.3f kHz', fc_principal_kHz), ...
    'LineWidth', 1.3, ...
    'LabelOrientation', 'aligned', ...
    'HandleVisibility', 'off');

xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');

title( ...
    'P3 / LED terreno 3 - Welch: zona local de deteccion', ...
    'Interpreter', 'none');

xlim([ ...
    f_ref_periodograma_Hz/1e3 - ancho_zoom_kHz, ...
    f_ref_periodograma_Hz/1e3 + ancho_zoom_kHz]);

ylim([-2 3]);

guardar_figura( ...
    fig, ...
    carpeta_salida, ...
    '09_P3_welch_zoom_local');

%% 19. Tabla resumen como figura

guardar_tabla_como_figura( ...
    tabla_resultado, ...
    'TABLA RESUMEN WELCH P3 - LED TERRENO 3', ...
    fullfile( ...
        carpeta_salida, ...
        '10_P3_welch_tabla_resultado.png'), ...
    fullfile( ...
        carpeta_salida, ...
        '10_P3_welch_tabla_resultado.fig'));

%% 20. Guardar variables

save( ...
    fullfile(carpeta_salida, 'datos_P3_welch.mat'), ...
    'f_ref_Hz', ...
    'f_banda_Hz', ...
    'f_banda_kHz', ...
    'PSD_ON_mat_dB', ...
    'PSD_OFF_mat_dB', ...
    'PSD_ON_prom_dB', ...
    'PSD_OFF_prom_dB', ...
    'PSD_ON_banda_dB', ...
    'PSD_OFF_banda_dB', ...
    'PSD_ON_banda_reps_dB', ...
    'PSD_OFF_banda_reps_dB', ...
    'score_rep_dB', ...
    'score_prom_dB', ...
    'score_banda_dB', ...
    'score_banda_reps_dB', ...
    'tabla_resultado', ...
    'tabla_candidatos', ...
    'tabla_score', ...
    'info_reps', ...
    'fc_principal_Hz', ...
    'fc_principal_kHz', ...
    'score_principal_dB', ...
    'criterio_dB', ...
    'Fs_configurada_Hz', ...
    'Nseg_objetivo', ...
    'fraccion_solapamiento', ...
    'distancia_minima_Hz', ...
    'ventana_local_Hz', ...
    'f_ref_periodograma_Hz', ...
    'ventana_confirmacion_Hz', ...
    'usar_confirmacion_local');

fprintf('\n============================================================\n');
fprintf('ANALISIS WELCH CORREGIDO FINALIZADO\n');
fprintf('Resultados guardados en:\n%s\n', carpeta_salida);
fprintf('============================================================\n');

%% Funciones locales

function [t, y] = leer_csv_rigol_terreno(nombre_archivo, Fs_configurada_Hz)

    M = readmatrix(nombre_archivo);

    if size(M, 2) < 2

        error( ...
            'El archivo no contiene al menos dos columnas:\n%s', ...
            nombre_archivo);
    end

    columnas_validas = [];

    for c = 1:size(M, 2)

        if sum(isfinite(M(:, c))) > 10
            columnas_validas = [columnas_validas c]; %#ok<AGROW>
        end
    end

    if numel(columnas_validas) < 1

        error( ...
            'No se detectaron columnas numericas validas:\n%s', ...
            nombre_archivo);
    end

    M = M(:, columnas_validas);

    t = [];
    y = [];

    if size(M, 2) >= 2

        for c = 1:(size(M, 2) - 1)

            t_cand = M(:, c);
            y_cand = M(:, c + 1);

            idx_validos = isfinite(t_cand) & isfinite(y_cand);

            t_temp = t_cand(idx_validos);
            y_temp = y_cand(idx_validos);

            if numel(y_temp) < 10
                continue;
            end

            t_temp = t_temp(:);
            y_temp = y_temp(:);

            duracion_temp = t_temp(end) - t_temp(1);

            if duracion_temp <= 0 || ~isfinite(duracion_temp)
                continue;
            end

            Fs_temp = (numel(t_temp) - 1) / duracion_temp;

            error_Fs_pct = abs(Fs_temp - Fs_configurada_Hz) / Fs_configurada_Hz * 100;

            if error_Fs_pct <= 10 && std(y_temp, 'omitnan') > 0

                t = t_temp;
                y = y_temp;
                return;
            end
        end
    end

    if isempty(y)

        y = M(:, end);
        y = y(isfinite(y));
        y = y(:);

        if numel(y) < 10

            error( ...
                'El archivo contiene muy pocas muestras validas:\n%s', ...
                nombre_archivo);
        end

        t = (0:numel(y)-1)'/Fs_configurada_Hz;
    end
end

function fila = crear_fila_info( ...
    archivo, ...
    condicion, ...
    repeticion, ...
    muestras_originales, ...
    muestras_usadas, ...
    duracion_s, ...
    Fs_duracion_Hz, ...
    Fs_usada_Hz, ...
    error_Fs_pct, ...
    Nseg, ...
    noverlap, ...
    num_segmentos, ...
    nfft, ...
    df_Hz)

    fila = table( ...
        archivo, ...
        condicion, ...
        repeticion, ...
        muestras_originales, ...
        muestras_usadas, ...
        duracion_s, ...
        Fs_duracion_Hz, ...
        Fs_usada_Hz, ...
        error_Fs_pct, ...
        Nseg, ...
        noverlap, ...
        num_segmentos, ...
        nfft, ...
        df_Hz, ...
        'VariableNames', { ...
        'Archivo', ...
        'Condicion', ...
        'Repeticion', ...
        'Muestras_originales', ...
        'Muestras_usadas', ...
        'Duracion_s', ...
        'Fs_duracion_Hz', ...
        'Fs_usada_Hz', ...
        'Error_Fs_pct', ...
        'Nseg', ...
        'Noverlap', ...
        'Numero_segmentos', ...
        'NFFT', ...
        'df_Hz'});
end

function guardar_figura(fig, carpeta_salida, nombre_archivo)

    archivo_png = fullfile( ...
        carpeta_salida, ...
        [nombre_archivo '.png']);

    archivo_fig = fullfile( ...
        carpeta_salida, ...
        [nombre_archivo '.fig']);

    drawnow;

    try

        exportgraphics( ...
            fig, ...
            archivo_png, ...
            'Resolution', 300);

    catch

        print( ...
            fig, ...
            archivo_png, ...
            '-dpng', ...
            '-r300');
    end

    savefig(fig, archivo_fig);
end

function guardar_tabla_como_figura( ...
    tabla, ...
    titulo_tabla, ...
    archivo_png, ...
    archivo_fig)

    if isempty(tabla)

        warning( ...
            'La tabla esta vacia. No se guardara la figura.');

        return;
    end

    datos_celdas = formatear_tabla_para_figura(tabla);

    nombres_columnas = tabla.Properties.VariableNames;

    nFilas = height(tabla);
    nColumnas = width(tabla);

    ancho_columnas = zeros(1, nColumnas);

    for c = 1:nColumnas

        largo_maximo_datos = 0;

        for i = 1:nFilas

            largo_maximo_datos = max( ...
                largo_maximo_datos, ...
                length(datos_celdas{i, c}));
        end

        largo_maximo = max( ...
            length(nombres_columnas{c}), ...
            largo_maximo_datos);

        ancho_columnas(c) = ...
            max(80, min(170, 8*largo_maximo + 28));
    end

    margen_izquierdo = 35;
    margen_derecho = 35;
    margen_inferior = 25;

    alto_titulo = 55;
    alto_fila = 30;
    alto_encabezado = 32;

    ancho_tabla = sum(ancho_columnas);

    alto_tabla = ...
        alto_encabezado + nFilas*alto_fila;

    ancho_figura = ...
        margen_izquierdo + ancho_tabla + margen_derecho;

    alto_figura = ...
        margen_inferior + alto_tabla + alto_titulo + 15;

    fig = figure( ...
        'Color', 'w', ...
        'Units', 'pixels', ...
        'Position', [100 100 ancho_figura alto_figura], ...
        'Visible', 'on');

    ax = axes( ...
        'Parent', fig, ...
        'Units', 'pixels', ...
        'Position', [0 0 ancho_figura alto_figura]);

    axis(ax, [0 ancho_figura 0 alto_figura]);
    axis(ax, 'off');

    hold(ax, 'on');

    text( ...
        ax, ...
        ancho_figura/2, ...
        alto_figura - 28, ...
        titulo_tabla, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontWeight', 'bold', ...
        'FontSize', 15, ...
        'Interpreter', 'none');

    x0 = margen_izquierdo;
    y0 = margen_inferior + alto_tabla;

    color_encabezado = [0.93 0.93 0.93];
    color_fila_1 = [1 1 1];
    color_fila_2 = [0.94 0.94 0.94];
    color_borde = [0.65 0.65 0.65];

    x = x0;

    for c = 1:nColumnas

        rectangle( ...
            ax, ...
            'Position', [ ...
                x, ...
                y0 - alto_encabezado, ...
                ancho_columnas(c), ...
                alto_encabezado], ...
            'FaceColor', color_encabezado, ...
            'EdgeColor', color_borde, ...
            'LineWidth', 0.8);

        text( ...
            ax, ...
            x + ancho_columnas(c)/2, ...
            y0 - alto_encabezado/2, ...
            nombres_columnas{c}, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontWeight', 'bold', ...
            'FontSize', 9, ...
            'Interpreter', 'none');

        x = x + ancho_columnas(c);
    end

    for i = 1:nFilas

        y = ...
            y0 - alto_encabezado - i*alto_fila;

        if mod(i, 2) == 0
            color_fila = color_fila_2;
        else
            color_fila = color_fila_1;
        end

        x = x0;

        for c = 1:nColumnas

            rectangle( ...
                ax, ...
                'Position', [ ...
                    x, ...
                    y, ...
                    ancho_columnas(c), ...
                    alto_fila], ...
                'FaceColor', color_fila, ...
                'EdgeColor', [0.88 0.88 0.88], ...
                'LineWidth', 0.5);

            text( ...
                ax, ...
                x + ancho_columnas(c)/2, ...
                y + alto_fila/2, ...
                datos_celdas{i, c}, ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'middle', ...
                'FontSize', 9, ...
                'Interpreter', 'none');

            x = x + ancho_columnas(c);
        end
    end

    drawnow;

    print( ...
        fig, ...
        archivo_png, ...
        '-dpng', ...
        '-r300');

    savefig(fig, archivo_fig);
end

function datos_celdas = formatear_tabla_para_figura(tabla)

    nFilas = height(tabla);
    nColumnas = width(tabla);

    datos_celdas = cell(nFilas, nColumnas);

    nombres_columnas = tabla.Properties.VariableNames;

    for c = 1:nColumnas

        nombre_columna = nombres_columnas{c};
        columna = tabla.(nombre_columna);

        for i = 1:nFilas

            if iscell(columna)
                valor = columna{i};
            else
                valor = columna(i);
            end

            if isnumeric(valor)

                if isnan(valor)

                    texto = '';

                elseif contains( ...
                        nombre_columna, ...
                        'kHz', ...
                        'IgnoreCase', true)

                    texto = sprintf('%.4f', valor);

                elseif contains( ...
                        nombre_columna, ...
                        'Hz', ...
                        'IgnoreCase', true)

                    texto = sprintf('%.0f', valor);

                elseif contains( ...
                        nombre_columna, ...
                        'dB', ...
                        'IgnoreCase', true)

                    texto = sprintf('%.4f', valor);

                elseif contains( ...
                        nombre_columna, ...
                        'rep', ...
                        'IgnoreCase', true)

                    texto = sprintf('%.0f', valor);

                else

                    texto = sprintf('%.4f', valor);
                end

            elseif islogical(valor)

                if valor
                    texto = 'Si';
                else
                    texto = 'No';
                end

            elseif isstring(valor)

                texto = char(valor);

            elseif ischar(valor)

                texto = valor;

            else

                texto = char(string(valor));
            end

            datos_celdas{i, c} = texto;
        end
    end
end

function [x_salida, y1_salida, y2_salida] = ...
    reducir_puntos_grafico(x, y1, y2, nMaximo)

    x = x(:);
    y1 = y1(:);
    y2 = y2(:);

    nPuntos = numel(x);

    if nPuntos > nMaximo

        indices = round( ...
            linspace(1, nPuntos, nMaximo));

    else

        indices = 1:nPuntos;
    end

    x_salida = x(indices);
    y1_salida = y1(indices);
    y2_salida = y2(indices);
end