%% T04_P2_periodogram_terreno.m
% Analisis Periodograma - P2 / LED terreno 2
%
% Antes de ejecutar este script, modificar las variables carpeta_ON
% y carpeta_OFF con las rutas locales donde se encuentran los archivos .csv
% de la medicion correspondiente.
%
% La carpeta_ON debe contener los archivos ON_P2_REP*.csv indicados
% en la lista archivos_ON.
% La carpeta_OFF debe contener los archivos OFF comunes indicados
% en la lista archivos_OFF.
%
% Ejemplo:
% carpeta_ON  = 'C:\Users\NombreUsuario\Desktop\Terreno_ON_M2';
% carpeta_OFF = 'C:\Users\NombreUsuario\Desktop\Terreno_OFF';

clear;
clc;
close all;

%% 1. Configuracion

carpeta_base = 'C:\Users\berni\OneDrive\Escritorio\Modulo Prof\Archivos Tesis\Toma de Datos\Pruebas en terreno';

carpeta_ON  = fullfile(carpeta_base, 'Terreno_ON_M2');
carpeta_OFF = fullfile(carpeta_base, 'Terreno_OFF');

carpeta_salida = fullfile( ...
    carpeta_base, ...
    'Resultados_Terreno', ...
    'P2_LED2', ...
    '01_Periodogram');

if ~exist(carpeta_salida, 'dir')
    mkdir(carpeta_salida);
end

nombre_punto = "P2";
nombre_led = "LED terreno 2";
nombre_metodo = "Periodograma";

nRep = 3;

archivos_ON = cell(nRep, 1);
archivos_OFF = cell(nRep, 1);

for r = 1:nRep
    archivos_ON{r} = fullfile( ...
        carpeta_ON, ...
        sprintf('ON_P2_REP%d.csv', r));

    archivos_OFF{r} = fullfile( ...
        carpeta_OFF, ...
        sprintf('OFF_REP%d.csv', r));
end

fmin_kHz = 30;
fmax_kHz = 90;

criterio_dB = 3;
umbral_repeticiones = 3;

num_candidatos = 7;
dist_min_candidatos_kHz = 0.3;

Fs_default = 50e6;

Nmax = Inf;
nfft_max = Inf;

fprintf('\n============================================================\n');
fprintf('PUNTO 2 / LED TERRENO 2 - PERIODOGRAMA\n');
fprintf('============================================================\n');
fprintf('Carpeta base:\n%s\n\n', carpeta_base);
fprintf('Carpeta ON:\n%s\n\n', carpeta_ON);
fprintf('Carpeta OFF:\n%s\n\n', carpeta_OFF);
fprintf('Carpeta salida:\n%s\n\n', carpeta_salida);

%% 2. Verificacion de archivos

for r = 1:nRep

    if ~exist(archivos_ON{r}, 'file')
        error( ...
            'No existe el archivo ON de la repeticion %d:\n%s', ...
            r, ...
            archivos_ON{r});
    end

    if ~exist(archivos_OFF{r}, 'file')
        error( ...
            'No existe el archivo OFF de la repeticion %d:\n%s', ...
            r, ...
            archivos_OFF{r});
    end
end

fprintf('Archivos verificados correctamente.\n');

%% 3. Procesamiento por repeticion

f_banda_ref_Hz = [];
f_full_ref_Hz = [];

PSD_ON_mat_dB = [];
PSD_OFF_mat_dB = [];

PSD_ON_full_mat_dB = [];
PSD_OFF_full_mat_dB = [];

info_reps = table();

for r = 1:nRep

    fprintf('\n------------------------------------------------------------\n');
    fprintf('Repeticion %d/%d\n', r, nRep);
    fprintf('ON : %s\n', archivos_ON{r});
    fprintf('OFF: %s\n', archivos_OFF{r});

    [tON, xON, FsON, N_ON_original] = ...
        leer_csv_rigol_terreno(archivos_ON{r}, Fs_default);

    [tOFF, xOFF, FsOFF, N_OFF_original] = ...
        leer_csv_rigol_terreno(archivos_OFF{r}, Fs_default);

    xON = xON(:);
    xOFF = xOFF(:);

    N_ON = numel(xON);
    N_OFF = numel(xOFF);

    if isfinite(Nmax)
        N_ON_usado = min(N_ON, Nmax);
        N_OFF_usado = min(N_OFF, Nmax);
    else
        N_ON_usado = N_ON;
        N_OFF_usado = N_OFF;
    end

    xON = xON(1:N_ON_usado);
    xOFF = xOFF(1:N_OFF_usado);

    xON = xON - mean(xON, 'omitnan');
    xOFF = xOFF - mean(xOFF, 'omitnan');

    xON(~isfinite(xON)) = 0;
    xOFF(~isfinite(xOFF)) = 0;

    if isfinite(nfft_max)
        nfft_ON = min(N_ON_usado, nfft_max);
        nfft_OFF = min(N_OFF_usado, nfft_max);
    else
        nfft_ON = N_ON_usado;
        nfft_OFF = N_OFF_usado;
    end

    nfft_ON = floor(nfft_ON);
    nfft_OFF = floor(nfft_OFF);

    [P_ON, fON] = periodogram( ...
        xON, ...
        rectwin(N_ON_usado), ...
        nfft_ON, ...
        FsON, ...
        'psd');

    [P_OFF, fOFF] = periodogram( ...
        xOFF, ...
        rectwin(N_OFF_usado), ...
        nfft_OFF, ...
        FsOFF, ...
        'psd');

    PSD_ON_dB = 10*log10(P_ON + eps);
    PSD_OFF_dB = 10*log10(P_OFF + eps);

    if isempty(f_full_ref_Hz)

        f_full_ref_Hz = fON(:);

        PSD_ON_full_mat_dB = nan( ...
            numel(f_full_ref_Hz), ...
            nRep);

        PSD_OFF_full_mat_dB = nan( ...
            numel(f_full_ref_Hz), ...
            nRep);
    end

    PSD_ON_full_mat_dB(:, r) = interp1( ...
        fON(:), ...
        PSD_ON_dB(:), ...
        f_full_ref_Hz, ...
        'linear', ...
        NaN);

    PSD_OFF_full_mat_dB(:, r) = interp1( ...
        fOFF(:), ...
        PSD_OFF_dB(:), ...
        f_full_ref_Hz, ...
        'linear', ...
        NaN);

    idx_ON_banda = ...
        fON >= fmin_kHz*1e3 & ...
        fON <= fmax_kHz*1e3;

    idx_OFF_banda = ...
        fOFF >= fmin_kHz*1e3 & ...
        fOFF <= fmax_kHz*1e3;

    fON_banda_Hz = fON(idx_ON_banda);
    fOFF_banda_Hz = fOFF(idx_OFF_banda);

    PSD_ON_banda_dB = PSD_ON_dB(idx_ON_banda);
    PSD_OFF_banda_dB = PSD_OFF_dB(idx_OFF_banda);

    if isempty(f_banda_ref_Hz)

        f_banda_ref_Hz = fON_banda_Hz(:);

        PSD_ON_mat_dB = nan( ...
            numel(f_banda_ref_Hz), ...
            nRep);

        PSD_OFF_mat_dB = nan( ...
            numel(f_banda_ref_Hz), ...
            nRep);
    end

    PSD_ON_mat_dB(:, r) = interp1( ...
        fON_banda_Hz, ...
        PSD_ON_banda_dB, ...
        f_banda_ref_Hz, ...
        'linear', ...
        NaN);

    PSD_OFF_mat_dB(:, r) = interp1( ...
        fOFF_banda_Hz, ...
        PSD_OFF_banda_dB, ...
        f_banda_ref_Hz, ...
        'linear', ...
        NaN);

    df_ON_Hz = FsON / nfft_ON;
    df_OFF_Hz = FsOFF / nfft_OFF;

    fila_info = table( ...
        r, ...
        N_ON_original, ...
        N_OFF_original, ...
        N_ON_usado, ...
        N_OFF_usado, ...
        FsON, ...
        FsOFF, ...
        nfft_ON, ...
        nfft_OFF, ...
        df_ON_Hz, ...
        df_OFF_Hz, ...
        'VariableNames', { ...
        'repeticion', ...
        'N_ON_original', ...
        'N_OFF_original', ...
        'N_ON_usado', ...
        'N_OFF_usado', ...
        'Fs_ON_Hz', ...
        'Fs_OFF_Hz', ...
        'nfft_ON', ...
        'nfft_OFF', ...
        'df_ON_Hz', ...
        'df_OFF_Hz'});

    info_reps = [info_reps; fila_info];

    fprintf('N ON original  = %d muestras\n', N_ON_original);
    fprintf('N OFF original = %d muestras\n', N_OFF_original);
    fprintf('N ON usado     = %d muestras\n', N_ON_usado);
    fprintf('N OFF usado    = %d muestras\n', N_OFF_usado);
    fprintf('Fs ON          = %.6f MSa/s\n', FsON/1e6);
    fprintf('Fs OFF         = %.6f MSa/s\n', FsOFF/1e6);
    fprintf('df ON          = %.6f Hz\n', df_ON_Hz);
    fprintf('df OFF         = %.6f Hz\n', df_OFF_Hz);
end

%% 4. Promedios y score ON-OFF

f_banda_kHz = f_banda_ref_Hz / 1e3;

PSD_ON_prom_dB = mean( ...
    PSD_ON_mat_dB, ...
    2, ...
    'omitnan');

PSD_OFF_prom_dB = mean( ...
    PSD_OFF_mat_dB, ...
    2, ...
    'omitnan');

PSD_ON_full_prom_dB = mean( ...
    PSD_ON_full_mat_dB, ...
    2, ...
    'omitnan');

PSD_OFF_full_prom_dB = mean( ...
    PSD_OFF_full_mat_dB, ...
    2, ...
    'omitnan');

score_mat_dB = PSD_ON_mat_dB - PSD_OFF_prom_dB;

score_prom_dB = mean( ...
    score_mat_dB, ...
    2, ...
    'omitnan');

rep_0dB = sum(score_mat_dB > 0, 2);
rep_3dB = sum(score_mat_dB >= criterio_dB, 2);

%% 5. Deteccion de frecuencia propia del Punto 2

[idx_candidatos, fc_candidatos_kHz, score_candidatos_dB] = ...
    seleccionar_candidatos_globales( ...
    f_banda_kHz, ...
    score_prom_dB, ...
    num_candidatos, ...
    dist_min_candidatos_kHz);

if isempty(idx_candidatos)
    error('No se encontraron candidatos dentro de la banda de analisis.');
end

idx_final = idx_candidatos(1);

fc_detectada_kHz = f_banda_kHz(idx_final);
score_detectado_dB = score_prom_dB(idx_final);

ON_detectado_dB = PSD_ON_prom_dB(idx_final);
OFF_detectado_dB = PSD_OFF_prom_dB(idx_final);

rep_0dB_detectado = rep_0dB(idx_final);
rep_3dB_detectado = rep_3dB(idx_final);

if score_detectado_dB >= criterio_dB && ...
        rep_3dB_detectado >= umbral_repeticiones

    supera_3dB = "Si";
else
    supera_3dB = "No";
end

tabla_resultado = table( ...
    nombre_punto, ...
    nombre_led, ...
    nombre_metodo, ...
    fc_detectada_kHz, ...
    score_detectado_dB, ...
    ON_detectado_dB, ...
    OFF_detectado_dB, ...
    rep_0dB_detectado, ...
    rep_3dB_detectado, ...
    nRep, ...
    criterio_dB, ...
    umbral_repeticiones, ...
    supera_3dB, ...
    'VariableNames', { ...
    'punto', ...
    'led', ...
    'metodo', ...
    'fc_detectada_kHz', ...
    'score_dB', ...
    'ON_prom_dB', ...
    'OFF_prom_dB', ...
    'rep_0dB', ...
    'rep_3dB', ...
    'rep_total', ...
    'criterio_dB', ...
    'umbral_repeticiones', ...
    'supera_3dB'});

tabla_candidatos = table();

for i = 1:numel(idx_candidatos)

    idx_i = idx_candidatos(i);

    if score_prom_dB(idx_i) >= criterio_dB && ...
            rep_3dB(idx_i) >= umbral_repeticiones

        supera_i = "Si";
    else
        supera_i = "No";
    end

    fila = table( ...
        nombre_punto, ...
        nombre_led, ...
        nombre_metodo, ...
        i, ...
        f_banda_kHz(idx_i), ...
        score_prom_dB(idx_i), ...
        PSD_ON_prom_dB(idx_i), ...
        PSD_OFF_prom_dB(idx_i), ...
        rep_0dB(idx_i), ...
        rep_3dB(idx_i), ...
        nRep, ...
        supera_i, ...
        'VariableNames', { ...
        'punto', ...
        'led', ...
        'metodo', ...
        'ranking', ...
        'fc_kHz', ...
        'score_dB', ...
        'ON_prom_dB', ...
        'OFF_prom_dB', ...
        'rep_0dB', ...
        'rep_3dB', ...
        'rep_total', ...
        'supera_3dB'});

    tabla_candidatos = [tabla_candidatos; fila];
end

tabla_score = table( ...
    f_banda_kHz(:), ...
    PSD_ON_prom_dB(:), ...
    PSD_OFF_prom_dB(:), ...
    score_prom_dB(:), ...
    rep_0dB(:), ...
    rep_3dB(:), ...
    'VariableNames', { ...
    'f_kHz', ...
    'PSD_ON_prom_dB', ...
    'PSD_OFF_prom_dB', ...
    'score_prom_dB', ...
    'rep_0dB', ...
    'rep_3dB'});

tabla_score_full = table( ...
    f_full_ref_Hz(:)/1e3, ...
    PSD_ON_full_prom_dB(:), ...
    PSD_OFF_full_prom_dB(:), ...
    'VariableNames', { ...
    'f_kHz', ...
    'PSD_ON_full_prom_dB', ...
    'PSD_OFF_full_prom_dB'});

%% 6. Mostrar resultados

fprintf('\n============================================================\n');
fprintf('RESULTADO FINAL - P2 / LED TERRENO 2 - PERIODOGRAMA\n');
fprintf('============================================================\n');
disp(tabla_resultado);

fprintf('\n============================================================\n');
fprintf('CANDIDATOS PRINCIPALES - P2 / LED TERRENO 2\n');
fprintf('============================================================\n');
disp(tabla_candidatos);

%% 7. Guardar tablas y datos

writetable( ...
    tabla_resultado, ...
    fullfile( ...
    carpeta_salida, ...
    'tabla_resultado_P2_periodogram.csv'));

writetable( ...
    tabla_candidatos, ...
    fullfile( ...
    carpeta_salida, ...
    'tabla_candidatos_P2_periodogram.csv'));

writetable( ...
    tabla_score, ...
    fullfile( ...
    carpeta_salida, ...
    'score_promedio_P2_periodogram.csv'));

writetable( ...
    tabla_score_full, ...
    fullfile( ...
    carpeta_salida, ...
    'PSD_promedio_full_P2_periodogram.csv'));

writetable( ...
    info_reps, ...
    fullfile( ...
    carpeta_salida, ...
    'info_repeticiones_P2_periodogram.csv'));

save( ...
    fullfile( ...
    carpeta_salida, ...
    'datos_P2_periodogram.mat'), ...
    'f_banda_kHz', ...
    'f_full_ref_Hz', ...
    'PSD_ON_mat_dB', ...
    'PSD_OFF_mat_dB', ...
    'PSD_ON_full_mat_dB', ...
    'PSD_OFF_full_mat_dB', ...
    'PSD_ON_prom_dB', ...
    'PSD_OFF_prom_dB', ...
    'PSD_ON_full_prom_dB', ...
    'PSD_OFF_full_prom_dB', ...
    'score_mat_dB', ...
    'score_prom_dB', ...
    'rep_0dB', ...
    'rep_3dB', ...
    'tabla_resultado', ...
    'tabla_candidatos', ...
    'tabla_score', ...
    'tabla_score_full', ...
    'info_reps', ...
    'criterio_dB', ...
    'umbral_repeticiones', ...
    'fmin_kHz', ...
    'fmax_kHz');

%% 8. Tabla de candidatos como figura

if ~isempty(tabla_candidatos)

    tabla_fig = table( ...
        tabla_candidatos.fc_kHz, ...
        tabla_candidatos.score_dB, ...
        tabla_candidatos.fc_kHz, ...
        tabla_candidatos.score_dB, ...
        tabla_candidatos.ON_prom_dB, ...
        tabla_candidatos.OFF_prom_dB, ...
        tabla_candidatos.rep_0dB, ...
        tabla_candidatos.rep_total, ...
        'VariableNames', { ...
        'fc_kHz', ...
        'score_peak', ...
        'f_local_kHz', ...
        'score_local', ...
        'ON_dB', ...
        'OFF_dB', ...
        'rep_positivas', ...
        'rep_totales'});

    guardar_tabla_como_figura( ...
        tabla_fig, ...
        'TABLA DE CANDIDATOS PERIODOGRAM P2 - LED TERRENO 2', ...
        fullfile( ...
        carpeta_salida, ...
        '05_P2_periodogram_tabla_candidatos.png'), ...
        fullfile( ...
        carpeta_salida, ...
        '05_P2_periodogram_tabla_candidatos.fig'));
end

%% 9. Grafico score promedio ON-OFF

fig = figure( ...
    'Color', ...
    'w', ...
    'Position', ...
    [100 100 1500 850]);

plot( ...
    f_banda_kHz, ...
    score_prom_dB, ...
    'LineWidth', ...
    1.1);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');

title( ...
    'P2 / LED terreno 2 - Periodograma: score ON-OFF', ...
    'Interpreter', ...
    'none');

yline( ...
    0, ...
    '--', ...
    '0 dB', ...
    'LabelHorizontalAlignment', ...
    'right');

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'LabelHorizontalAlignment', ...
    'right');

xline( ...
    fc_detectada_kHz, ...
    ':', ...
    'LineWidth', ...
    1.2);

yl = ylim;

text( ...
    fc_detectada_kHz, ...
    yl(2) - 0.05*range(yl), ...
    sprintf('%.3f kHz', fc_detectada_kHz), ...
    'Rotation', ...
    90, ...
    'VerticalAlignment', ...
    'top', ...
    'HorizontalAlignment', ...
    'right');

xlim([fmin_kHz fmax_kHz]);

guardar_png( ...
    fig, ...
    carpeta_salida, ...
    '01_P2_periodogram_score_ON_OFF');

%% 10. Grafico candidatos principales formato laboratorio

if ~isempty(tabla_candidatos)

    fig = figure( ...
        'Color', ...
        'w', ...
        'Position', ...
        [100 100 1200 700]);

    x = 1:height(tabla_candidatos);

    bar( ...
        x, ...
        tabla_candidatos.score_dB);

    hold on;
    grid on;
    box on;

    yline( ...
        criterio_dB, ...
        '--', ...
        sprintf('Criterio %.1f dB', criterio_dB), ...
        'LineWidth', ...
        1.1);

    [~, idx_best] = max(tabla_candidatos.score_dB);

    plot( ...
        idx_best, ...
        tabla_candidatos.score_dB(idx_best), ...
        'kp', ...
        'MarkerSize', ...
        16, ...
        'LineWidth', ...
        2, ...
        'DisplayName', ...
        'Candidato principal');

    xlabel('Frecuencia candidata [kHz]');
    ylabel('Score local ON-OFF [dB]');

    title( ...
        'P2 / LED terreno 2 - Periodograma: candidatos principales', ...
        'Interpreter', ...
        'none');

    xticks(x);

    xticklabels( ...
        compose( ...
        '%.3f', ...
        tabla_candidatos.fc_kHz));

    xtickangle(45);

    for i = 1:height(tabla_candidatos)

        text( ...
            x(i), ...
            tabla_candidatos.score_dB(i) + 0.3, ...
            sprintf( ...
            '%.2f dB\n%d/%d', ...
            tabla_candidatos.score_dB(i), ...
            tabla_candidatos.rep_0dB(i), ...
            tabla_candidatos.rep_total(i)), ...
            'HorizontalAlignment', ...
            'center', ...
            'FontSize', ...
            8);
    end

    ylim([ ...
        0, ...
        max(tabla_candidatos.score_dB) + 2]);

    legend( ...
        'Score local ON-OFF', ...
        'Criterio 3 dB', ...
        'Candidato principal', ...
        'Location', ...
        'best');

    saveas( ...
        fig, ...
        fullfile( ...
        carpeta_salida, ...
        '02_P2_periodogram_barras_candidatos.png'));

    savefig( ...
        fig, ...
        fullfile( ...
        carpeta_salida, ...
        '02_P2_periodogram_barras_candidatos.fig'));
end

%% 11. Grafico PSD promedio ON/OFF en banda de analisis

fig = figure( ...
    'Color', ...
    'w', ...
    'Position', ...
    [100 100 1500 850]);

plot( ...
    f_banda_kHz, ...
    PSD_ON_prom_dB, ...
    'LineWidth', ...
    1.0);

hold on;

plot( ...
    f_banda_kHz, ...
    PSD_OFF_prom_dB, ...
    'LineWidth', ...
    1.0);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('PSD Periodogram [dB/Hz]');

title( ...
    'P2 / LED terreno 2 - Periodograma: PSD promedio ON/OFF', ...
    'Interpreter', ...
    'none');

legend( ...
    'ON P2 promedio', ...
    'OFF promedio', ...
    'Location', ...
    'best');

xline( ...
    fc_detectada_kHz, ...
    ':', ...
    'LineWidth', ...
    1.2, ...
    'HandleVisibility', ...
    'off');

yl = ylim;

text( ...
    fc_detectada_kHz, ...
    yl(2) - 0.05*range(yl), ...
    sprintf('%.3f kHz', fc_detectada_kHz), ...
    'Rotation', ...
    90, ...
    'VerticalAlignment', ...
    'top', ...
    'HorizontalAlignment', ...
    'right');

xlim([fmin_kHz fmax_kHz]);

guardar_png( ...
    fig, ...
    carpeta_salida, ...
    '03_P2_periodogram_PSD_promedio_ON_OFF');

%% 12. Grafico score por repeticion

fig = figure( ...
    'Color', ...
    'w', ...
    'Position', ...
    [100 100 1500 850]);

hold on;

for r = 1:nRep

    plot( ...
        f_banda_kHz, ...
        score_mat_dB(:, r), ...
        'LineWidth', ...
        0.9);
end

plot( ...
    f_banda_kHz, ...
    score_prom_dB, ...
    'k', ...
    'LineWidth', ...
    1.8);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');

title( ...
    'P2 / LED terreno 2 - Periodograma: score por repeticion', ...
    'Interpreter', ...
    'none');

leyenda = cell(nRep + 1, 1);

for r = 1:nRep
    leyenda{r} = sprintf('REP%d', r);
end

leyenda{nRep + 1} = 'Promedio';

legend( ...
    leyenda, ...
    'Location', ...
    'best', ...
    'AutoUpdate', ...
    'off');

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'LabelHorizontalAlignment', ...
    'right', ...
    'HandleVisibility', ...
    'off');

xline( ...
    fc_detectada_kHz, ...
    ':', ...
    'LineWidth', ...
    1.2, ...
    'HandleVisibility', ...
    'off');

xlim([fmin_kHz fmax_kHz]);

guardar_png( ...
    fig, ...
    carpeta_salida, ...
    '04_P2_periodogram_score_repeticiones');

%% 13. Grafico PSD promedio ON/OFF en rango amplio

fmax_amplio_Hz = min( ...
    5e6, ...
    max(f_full_ref_Hz));

idx_amplio = ...
    f_full_ref_Hz >= 0 & ...
    f_full_ref_Hz <= fmax_amplio_Hz;

[f_plot_MHz, ON_plot_dB, OFF_plot_dB] = ...
    reducir_puntos_grafico( ...
    f_full_ref_Hz(idx_amplio)/1e6, ...
    PSD_ON_full_prom_dB(idx_amplio), ...
    PSD_OFF_full_prom_dB(idx_amplio), ...
    80000);

fig = figure( ...
    'Color', ...
    'w', ...
    'Position', ...
    [100 100 1200 700]);

plot( ...
    f_plot_MHz, ...
    ON_plot_dB, ...
    'LineWidth', ...
    1.2);

hold on;

plot( ...
    f_plot_MHz, ...
    OFF_plot_dB, ...
    'LineWidth', ...
    1.2);

grid on;
box on;

xlabel('Frecuencia [MHz]');
ylabel('PSD Periodogram [dB/Hz]');

title( ...
    'P2 / LED terreno 2 - Periodograma: PSD promedio ON/OFF, rango amplio', ...
    'Interpreter', ...
    'none');

legend( ...
    'LED encendido', ...
    'LED apagado', ...
    'Location', ...
    'best');

xlim([0 fmax_amplio_Hz/1e6]);

saveas( ...
    fig, ...
    fullfile( ...
    carpeta_salida, ...
    '06_P2_periodogram_ON_OFF_rango_amplio.png'));

savefig( ...
    fig, ...
    fullfile( ...
    carpeta_salida, ...
    '06_P2_periodogram_ON_OFF_rango_amplio.fig'));

%% 14. Grafico repeticiones ON en banda de analisis

fig = figure( ...
    'Color', ...
    'w', ...
    'Position', ...
    [100 100 1200 700]);

plot( ...
    f_banda_kHz, ...
    PSD_ON_mat_dB, ...
    'LineWidth', ...
    1.0);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('PSD Periodogram [dB/Hz]');

title( ...
    'P2 / LED terreno 2 - Periodograma: repeticiones ON en banda de analisis', ...
    'Interpreter', ...
    'none');

legend( ...
    compose('ON P2 rep %d', 1:nRep), ...
    'Location', ...
    'best');

xlim([fmin_kHz fmax_kHz]);

saveas( ...
    fig, ...
    fullfile( ...
    carpeta_salida, ...
    '07_P2_periodogram_repeticiones_ON_30_90kHz.png'));

savefig( ...
    fig, ...
    fullfile( ...
    carpeta_salida, ...
    '07_P2_periodogram_repeticiones_ON_30_90kHz.fig'));

%% 15. Grafico repeticiones OFF en banda de analisis

fig = figure( ...
    'Color', ...
    'w', ...
    'Position', ...
    [100 100 1200 700]);

plot( ...
    f_banda_kHz, ...
    PSD_OFF_mat_dB, ...
    'LineWidth', ...
    1.0);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('PSD Periodogram [dB/Hz]');

title( ...
    'P2 / LED terreno 2 - Periodograma: repeticiones OFF en banda de analisis', ...
    'Interpreter', ...
    'none');

legend( ...
    compose('OFF rep %d', 1:nRep), ...
    'Location', ...
    'best');

xlim([fmin_kHz fmax_kHz]);

saveas( ...
    fig, ...
    fullfile( ...
    carpeta_salida, ...
    '08_P2_periodogram_repeticiones_OFF_30_90kHz.png'));

savefig( ...
    fig, ...
    fullfile( ...
    carpeta_salida, ...
    '08_P2_periodogram_repeticiones_OFF_30_90kHz.fig'));

%% 16. Grafico local alrededor de la frecuencia detectada

ancho_local_kHz = 2;

idx_local = ...
    f_banda_kHz >= fc_detectada_kHz - ancho_local_kHz & ...
    f_banda_kHz <= fc_detectada_kHz + ancho_local_kHz;

fig = figure( ...
    'Color', ...
    'w', ...
    'Position', ...
    [100 100 1500 850]);

plot( ...
    f_banda_kHz(idx_local), ...
    score_prom_dB(idx_local), ...
    'LineWidth', ...
    1.2);

grid on;
box on;

xlabel('Frecuencia [kHz]');
ylabel('Score ON - OFF [dB]');

title( ...
    'P2 / LED terreno 2 - Periodograma: zona local de deteccion', ...
    'Interpreter', ...
    'none');

yline( ...
    0, ...
    '--', ...
    '0 dB', ...
    'LabelHorizontalAlignment', ...
    'right', ...
    'HandleVisibility', ...
    'off');

yline( ...
    criterio_dB, ...
    '--', ...
    sprintf('Criterio %.1f dB', criterio_dB), ...
    'LabelHorizontalAlignment', ...
    'right', ...
    'HandleVisibility', ...
    'off');

xline( ...
    fc_detectada_kHz, ...
    ':', ...
    sprintf('%.3f kHz', fc_detectada_kHz), ...
    'LineWidth', ...
    1.2, ...
    'LabelVerticalAlignment', ...
    'top', ...
    'HandleVisibility', ...
    'off');

xlim([ ...
    fc_detectada_kHz - ancho_local_kHz, ...
    fc_detectada_kHz + ancho_local_kHz]);

guardar_png( ...
    fig, ...
    carpeta_salida, ...
    '09_P2_periodogram_zoom_local');

fprintf('\n============================================================\n');
fprintf('ANALISIS FINALIZADO\n');
fprintf('Resultados guardados en:\n%s\n', carpeta_salida);
fprintf('============================================================\n');

%% Funciones locales

function [t, y, Fs, N_original] = ...
        leer_csv_rigol_terreno(nombre_archivo, Fs_default)

    M = readmatrix(nombre_archivo);

    if size(M, 2) < 2
        error( ...
            'El archivo no tiene al menos dos columnas numericas:\n%s', ...
            nombre_archivo);
    end

    t = M(:, 1);
    y = M(:, 2);

    idx = isfinite(t) & isfinite(y);

    t = t(idx);
    y = y(idx);

    N_original = numel(y);

    if N_original < 10
        error( ...
            'El archivo tiene muy pocas muestras validas:\n%s', ...
            nombre_archivo);
    end

    dt = diff(t);
    dt = dt(isfinite(dt) & dt > 0);

    if isempty(dt)
        Fs = Fs_default;
    else
        Fs = 1 / median(dt, 'omitnan');
    end

    if ~isfinite(Fs) || Fs <= 0
        Fs = Fs_default;
    end
end

function [idx_sel, f_sel_kHz, score_sel_dB] = ...
        seleccionar_candidatos_globales( ...
        f_kHz, ...
        score_dB, ...
        num_candidatos, ...
        dist_min_kHz)

    f_kHz = f_kHz(:);
    score_dB = score_dB(:);

    idx_validos = find( ...
        isfinite(f_kHz) & ...
        isfinite(score_dB));

    if isempty(idx_validos)

        idx_sel = [];
        f_sel_kHz = [];
        score_sel_dB = [];

        return;
    end

    [~, orden_local] = sort( ...
        score_dB(idx_validos), ...
        'descend');

    idx_ordenados = idx_validos(orden_local);

    idx_sel = [];

    for i = 1:numel(idx_ordenados)

        idx_actual = idx_ordenados(i);
        f_actual = f_kHz(idx_actual);

        if isempty(idx_sel)

            idx_sel = idx_actual;
        else

            f_previas = f_kHz(idx_sel);

            if all(abs(f_actual - f_previas) >= dist_min_kHz)
                idx_sel = [idx_sel; idx_actual];
            end
        end

        if numel(idx_sel) >= num_candidatos
            break;
        end
    end

    f_sel_kHz = f_kHz(idx_sel);
    score_sel_dB = score_dB(idx_sel);
end

function guardar_png(fig, carpeta_salida, nombre_archivo)

    archivo_png = fullfile( ...
        carpeta_salida, ...
        [nombre_archivo '.png']);

    archivo_fig = fullfile( ...
        carpeta_salida, ...
        [nombre_archivo '.fig']);

    try
        exportgraphics( ...
            fig, ...
            archivo_png, ...
            'Resolution', ...
            300);
    catch
        saveas( ...
            fig, ...
            archivo_png);
    end

    savefig( ...
        fig, ...
        archivo_fig);
end

function guardar_tabla_como_figura( ...
        tabla, ...
        titulo_tabla, ...
        archivo_png, ...
        archivo_fig)

    if isempty(tabla)
        warning('La tabla esta vacia. No se guardara figura de tabla.');
        return;
    end

    data_cell = formatear_tabla_para_figura(tabla);

    nombres = tabla.Properties.VariableNames;

    nfilas = height(tabla);
    ncols = width(tabla);

    ancho_col = zeros(1, ncols);

    for c = 1:ncols

        textos_columna = data_cell(:, c);
        largo_max_datos = 0;

        for i = 1:nfilas

            largo_max_datos = max( ...
                largo_max_datos, ...
                length(textos_columna{i}));
        end

        largo_max = max( ...
            length(nombres{c}), ...
            largo_max_datos);

        ancho_col(c) = 8*largo_max + 24;
        ancho_col(c) = max(75, min(150, ancho_col(c)));
    end

    margen_izq = 30;
    margen_der = 30;
    margen_inf = 25;

    alto_titulo = 55;
    alto_fila = 28;
    alto_header = 30;

    ancho_tabla = sum(ancho_col);
    alto_tabla = alto_header + nfilas*alto_fila;

    ancho_fig = ...
        margen_izq + ...
        ancho_tabla + ...
        margen_der;

    alto_fig = ...
        margen_inf + ...
        alto_tabla + ...
        alto_titulo + ...
        15;

    fig = figure( ...
        'Color', ...
        'w', ...
        'Units', ...
        'pixels', ...
        'Position', ...
        [100 100 ancho_fig alto_fig], ...
        'Visible', ...
        'on');

    ax = axes( ...
        'Parent', ...
        fig, ...
        'Units', ...
        'pixels', ...
        'Position', ...
        [0 0 ancho_fig alto_fig]);

    axis(ax, [0 ancho_fig 0 alto_fig]);
    axis(ax, 'off');

    hold(ax, 'on');

    text( ...
        ax, ...
        ancho_fig/2, ...
        alto_fig - 28, ...
        titulo_tabla, ...
        'HorizontalAlignment', ...
        'center', ...
        'VerticalAlignment', ...
        'middle', ...
        'FontWeight', ...
        'bold', ...
        'FontSize', ...
        15, ...
        'Interpreter', ...
        'none');

    x0 = margen_izq;
    y0 = margen_inf + alto_tabla;

    color_header = [0.93 0.93 0.93];
    color_fila_1 = [1 1 1];
    color_fila_2 = [0.94 0.94 0.94];
    color_borde = [0.65 0.65 0.65];

    x = x0;

    for c = 1:ncols

        rectangle( ...
            ax, ...
            'Position', ...
            [ ...
            x, ...
            y0 - alto_header, ...
            ancho_col(c), ...
            alto_header], ...
            'FaceColor', ...
            color_header, ...
            'EdgeColor', ...
            color_borde, ...
            'LineWidth', ...
            0.8);

        text( ...
            ax, ...
            x + ancho_col(c)/2, ...
            y0 - alto_header/2, ...
            nombres{c}, ...
            'HorizontalAlignment', ...
            'center', ...
            'VerticalAlignment', ...
            'middle', ...
            'FontWeight', ...
            'bold', ...
            'FontSize', ...
            9, ...
            'Interpreter', ...
            'none');

        x = x + ancho_col(c);
    end

    for i = 1:nfilas

        y = y0 - alto_header - i*alto_fila;

        if mod(i, 2) == 0
            color_fila = color_fila_2;
        else
            color_fila = color_fila_1;
        end

        x = x0;

        for c = 1:ncols

            rectangle( ...
                ax, ...
                'Position', ...
                [ ...
                x, ...
                y, ...
                ancho_col(c), ...
                alto_fila], ...
                'FaceColor', ...
                color_fila, ...
                'EdgeColor', ...
                [0.88 0.88 0.88], ...
                'LineWidth', ...
                0.5);

            text( ...
                ax, ...
                x + ancho_col(c)/2, ...
                y + alto_fila/2, ...
                data_cell{i, c}, ...
                'HorizontalAlignment', ...
                'center', ...
                'VerticalAlignment', ...
                'middle', ...
                'FontSize', ...
                9, ...
                'Interpreter', ...
                'none');

            x = x + ancho_col(c);
        end
    end

    drawnow;

    print( ...
        fig, ...
        archivo_png, ...
        '-dpng', ...
        '-r300');

    savefig( ...
        fig, ...
        archivo_fig);
end

function data_cell = formatear_tabla_para_figura(tabla)

    nfilas = height(tabla);
    ncols = width(tabla);

    data_cell = cell(nfilas, ncols);

    nombres = tabla.Properties.VariableNames;

    for c = 1:ncols

        nombre = nombres{c};
        col = tabla.(nombre);

        for i = 1:nfilas

            if iscell(col)
                valor = col{i};
            else
                valor = col(i);
            end

            if isnumeric(valor)

                if isnan(valor)

                    texto = '';

                elseif contains( ...
                        nombre, ...
                        'kHz', ...
                        'IgnoreCase', ...
                        true)

                    texto = sprintf('%.4f', valor);

                elseif contains( ...
                        nombre, ...
                        'Hz', ...
                        'IgnoreCase', ...
                        true)

                    texto = sprintf('%.0f', valor);

                elseif contains( ...
                        nombre, ...
                        'dB', ...
                        'IgnoreCase', ...
                        true)

                    texto = sprintf('%.4f', valor);

                elseif contains( ...
                        nombre, ...
                        'rep', ...
                        'IgnoreCase', ...
                        true)

                    texto = sprintf('%.0f', valor);

                else
                    texto = sprintf('%.4f', valor);
                end

            elseif islogical(valor)

                if valor
                    texto = 'Si';
                else
                    texto = 'No';
                end

            elseif isstring(valor)

                if strlength(valor) == 0
                    texto = '';
                else
                    texto = char(valor);
                end

            elseif ischar(valor)

                texto = valor;

            else
                texto = char(string(valor));
            end

            data_cell{i, c} = texto;
        end
    end
end

function [x_out, y1_out, y2_out] = ...
        reducir_puntos_grafico(x, y1, y2, nmax)

    x = x(:);
    y1 = y1(:);
    y2 = y2(:);

    n = numel(x);

    if n > nmax
        idx = round(linspace(1, n, nmax));
    else
        idx = 1:n;
    end

    x_out = x(idx);
    y1_out = y1(idx);
    y2_out = y2(idx);
end